<div class="col-md-6 events-list-wrapper" data-event="<?php echo($wo['event']['id']);?>">
	<div class="events-list-cover">
		<a href="<?php echo $wo['event']['url']; ?>" class="event_cover" data-ajax="?link1=show-event&eid=<?php echo($wo['event']['id']);?>">
			<img src="<?php echo $wo['event']['cover']; ?>" class="events-list-cover-img">
			<ul>
				<li>
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-map-pin"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg> 
					<?php echo $wo['event']['location'];?>
				</li>
			</ul>
		</a>
		<div class="event-l-info">
			<a href="<?php echo $wo['event']['url']; ?>" data-ajax="?link1=show-event&eid=<?php echo($wo['event']['id']);?>">
				<p class="events-list-name"><?php echo $wo['event']['name']; ?></p>
			</a>
			<ul>
				<li>
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>
					<?php echo $wo['event']['start_date'];?>
				</li>
			</ul>
			<div class="options-buttons text-center">
				<span class="user-follow-button">
					<?php echo Wo_GetGoingButton($wo['event']['id']);?>
				</span>
				<span class="user-follow-button">
					<?php echo Wo_GetInterestedButton($wo['event']['id']);?>
				</span>
			</div>
		</div>
	</div>
	<div class="clear"></div>
</div>
