<div class="col-md-4 col-sm-6 col-xs-12 blog">
	<a href="<?php echo $wo['blog-style']['url'] ?>">
		<span class="avatar-wrapper">
			<img src="<?php echo $wo['blog-style']['thumbnail'];?>" alt="Article Picture">
		</span>
		<h5><?php echo $wo['page_categories'][$wo['blog-style']['category']]; ?></h5>
		<h2 class="blog-title"><?php echo $wo['blog-style']['title'] ?></h2>
		<span class="blog-info"><?php echo Wo_Time_Elapsed_String($wo['blog-style']['posted']); ?></span>
	</a>
</div>