<div class="modal fade matdialog" id="delete-blog" >
   <div class="modal-dialog modal-sm">
      <div class="modal-content">
         <div class="modal-header">
            <h4 class="modal-title"><?php echo $wo['lang']['delete_post']; ?></h4>
         </div>
         <div class="modal-body">
            <p><?php echo $wo['lang']['confirm_delete_post']; ?></p>
         </div>
         <div class="modal-footer">
		 <button  type="button" class="matbtn btn btn-default wabe" data-dismiss="modal"><?php echo $wo['lang']['cancel']; ?></button>
            <button  type="button" onclick="Wo_Del_Article($('#delete-blog').attr('data-blog-id'))" class="btn matbtn btn-main wabe"><?php echo $wo['lang']['delete']; ?></button>
            
         </div>
      </div>
   </div>
</div>
