<div class="col-md-4 col-sm-6" data-blog-id="<?php echo $wo['article']['id']; ?>">
	<div class="sun_article_list">
		<a href="<?php echo $wo['article']['url']; ?>" data-ajax="?link1=read-blog&id=<?php echo $wo['article']['id']; ?>">
			<div class="avatar">
				<img src="<?php echo $wo['article']['thumbnail']; ?>" alt="<?php echo $wo['article']['title']; ?>">
			</div>
		</a>
		<div class="blog-h-desc">
		 	<div class="blog-meta-desc">
				<div class="postMeta">
					<time><?php echo date("d M Y",$wo['article']['posted']); ?></time>
					<span class="middot">/</span>
					<?php echo $wo['lang']['by'] ?>
					<a href="<?php echo $wo['article']['author']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['article']['author']['username']; ?>"><?php echo $wo['article']['author']['name']; ?></a>
				</div>
		 	</div>
			<h3 class="art-title" title="<?php echo $wo['article']['title']; ?>"><a href="<?php echo $wo['article']['url']; ?>"><?php echo $wo['article']['title']; ?></a></h3>
			<p class="desc">
				<?php 
				$desc = str_replace('<br>', '', $wo['article']['description']);
				echo $desc = mb_substr($desc, 0, 110, "UTF-8") . ".."; ?>
			</p>
			<div class="postFooter">
				<div class="u-floatLeft">
					<a href="<?php echo $wo['article']['url']; ?>" class="main"><?php echo $wo['lang']['read_more'] ?></a>
					<span class="middot main">|</span>
					<a class="main" href="<?php echo $wo['article']['category_link']; ?>" data-ajax="?link1=blog-category&id=<?php echo $wo['article']['category']; ?>"><?php echo $wo['page_categories'][$wo['article']['category']]; ?></a>
				</div>
			</div>
		</div>
	</div>
</div>