<div class="featureblog" data-rm-blog="<?php echo $wo['blog']['id']; ?>">
	<div class="blog-h-list view-blog" id="<?php echo $wo['blog']['id']; ?>">
		<a href="<?php echo $wo['blog']['url']; ?>" data-ajax="?link1=read-blog&id=<?php echo $wo['blog']['id']; ?>">
			<div class="avatar <?php echo Wo_RightToLeft('pull-left');?>">
				<img width="200" src="<?php echo $wo['blog']['thumbnail']; ?>" alt="<?php echo $wo['blog']['title']; ?>">
			</div>
		</a>
		<div class="blog-h-desc">
			<a class="main postCategory" href="<?php echo $wo['blog']['category_link']; ?>" data-ajax="?link1=blog-category&id=<?php echo $wo['blog']['category']; ?>">
				<h5><?php echo $wo['page_categories'][$wo['blog']['category']]; ?></h5>
			</a>
			<a href="<?php echo $wo['blog']['url']; ?>">
				<h3 class="art-title"><?php echo $wo['blog']['title']; ?></h3>
			</a>
		 	<div class="blog-meta-desc">
			 	<div class="postMeta--author-avatar">
				 	<a href="<?php echo $wo['blog']['author']['url']?>">
						<img src="<?php echo $wo['blog']['author']['avatar']?>" alt="User Image">
					</a>
				</div>
				<div class="postMeta--author-text">
					<a class="main" href="<?php echo $wo['blog']['author']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['blog']['author']['username']; ?>">
						<?php echo $wo['blog']['author']['name']; ?>
				 	</a>
					<span class="middot">·</span>
					<time>
						<?php echo date("d M Y",$wo['blog']['posted']); ?>
					</time>
				</div>
		 	</div>
			
			<p class="desc">
				<?php 
				$desc = str_replace('<br>', '', $wo['blog']['description']);
				echo $desc = mb_substr($desc, 0, 100, "UTF-8") . ".."; ?>
			</p>
		</div>
	</div>
</div>