<?php
$wo['setting_page'] = 'general-setting';
$pages_array = array(
   'general-setting',
   'profile-setting',
   'social-links',
   'delete-page',
   'avatar-setting',
   'design-setting',
   'admins'
   );
if (!empty($_GET['link3'])) {
   if (in_array($_GET['link3'], $pages_array)) {
      $wo['setting_page'] = $_GET['link3'];
   }
}
?>
<style>.wo_settings_page h3, .wo_settings_page .modal-footer .btn{background-color: #f79f58;border-color: #f79f58;}</style>
<div class="page-margin">
   <div class="row setting-panel">
      <div class="col-md-2 offnavmenu"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
      <div class="col-md-7 cushomewider" style="padding-left: 0px;">
         <?php echo Wo_LoadPage("page-setting/" . $wo['setting_page']); ?>
      </div>
      <div class="col-md-3 sidebar cushomesmaller">
          <?php echo Wo_LoadPage('page-setting/page-setting-sidebar');?>
      </div>
   </div>
</div>