<div class="wo_game_style col-xs-6 col-sm-4 col-md-3" id="game_<?php echo $wo['game']['id'];?>">
	<a href="<?php echo $wo['game']['url'];?>" data-ajax="?link1=game&id=<?php echo $wo['game']['id'];?>">
		<div class="game-name"><?php echo $wo['game']['game_name']; ?></div>
		<img src="<?php echo $wo['game']['game_avatar'];?>" alt="<?php echo $wo['game']['game_name']; ?> Profile Picture" />
		<div class="btn btn-link"><?php echo $wo['lang']['play'];?></div>
	</a>
</div>