<div class="movies-film-wrapper col-exs-6 col-xs-4 col-sm-3 col-md-3" data-film-id="<?php echo $wo['film']['id']; ?>">
	<figure>
		<a href="<?php echo $wo['film']['url']; ?>">
			<img src="<?php echo $wo['film']['cover']; ?>" alt="" class="responsive-img">
		</a>
		<h3 title="<?php echo $wo['film']['name']; ?>"><a href="<?php echo $wo['film']['url']; ?>"><?php echo $wo['film']['name']; ?></a></h3>
		<p><?php echo $wo['film']['genre']; ?></p>
	</figure>
</div>