<?php $replies = Wo_CountCommentReplies($wo['comment']['id']);?>
<div class="comment comment-container" id="comment_<?php echo $wo['comment']['id'];?>" data-comment-id ="<?php echo $wo['comment']['id'];?>">
   <a class="<?php echo Wo_RightToLeft('pull-left'); ?>" href="<?php echo $wo['comment']['publisher']['url']?>">
   <img class="avatar <?php echo Wo_RightToLeft('pull-left'); ?>" src="<?php echo $wo['comment']['publisher']['avatar']?>" alt="avatar">
   </a>
   <div class="comment-body">
      <div class="comment-heading">
         <span class="user-popover" data-id="<?php echo $wo['comment']['publisher']['id'];?>" data-type="<?php echo $wo['comment']['publisher']['type'];?>">
         <a href="<?php echo $wo['comment']['publisher']['url']?>">
            <h4 class="user">
               <?php echo $wo['comment']['publisher']['name']?>
            </h4>
         </a>
         </span>
         <?php  if($wo['comment']['publisher']['verified'] == 1) {   ?>
         <span class="verified-color" data-toggle="tooltip" title="<?php echo $wo['lang']['verified_user'];?>"><i class="fa fa-check-circle"></i></span>
         <?php } ?>

         <div class="<?php echo Wo_RightToLeft('pull-right');?> comment-options" style="margin: 0px 5px;">
            <?php if ($wo['comment']['onwer'] === true) { ?>
            <span class="pointer comment-icons" id="editComment" onclick="Wo_OpenCommentEditBox(<?php echo $wo['comment']['id']?>);" data-toggle="tooltip" title="Edit" style="margin-right: 5px;">
               <i class="zmdi zmdi-edit" style="font-size: 13px;"></i>
            </span>
            <?php } ?>
            <?php if ($wo['comment']['post_onwer'] === true|| $wo['comment']['onwer'] === true) {?>
            <span class="pointer" id="deleteComment" onclick="Wo_DeleteComment(<?php echo $wo['comment']['id']?>);" data-toggle="tooltip" title="Delete">
               <i class="zmdi zmdi-delete" style="font-size: 13px;"></i>
            </span>
            <?php } ?>
         </div>
         <span class="time ajax-time" title="<?php echo date('c',$wo['comment']['time']);?>"><?php echo $wo['comment']['time']?></span>
         <div class="comment-text"><?php echo $wo['comment']['text']?></div>
         <div class="comment-image">
            <?php if (!empty($wo['comment']['c_file'])): ?>
               <a href="<?php echo Wo_GetMedia($wo['comment']['c_file']);?>" target="_blank"><img src="<?php echo Wo_GetMedia($wo['comment']['c_file']);?>" alt="Comment image"></a>
            <?php endif ?>
         </div>
         <div class="clear"></div>   
      </div>
      <?php if ($wo['config']['second_post_button'] == 'reaction') { ?>
            <!-- reaction -->
              <div class="like-stat  stat-item post-like-status" style="float: left;margin: -2px 10px 0px 0px;">
                  <span class="like-emo lightbox-comment-reactions-icons-<?php echo $wo['comment']['id']; ?>">
                  <?php echo Wo_GetPostReactions($wo['comment']['id'],"comment");?>
                  </span>
              </div>
              <div class="wo-reaction wo-reaction-lightbox-comment stat-item" id="comment_reactions" data-id="<?php echo $wo['comment']['id']; ?>">
                    <span class="like-btn like-btn-lightbox-comment" data-id="<?php echo $wo['comment']['id']; ?>">
                        <?php
                        if (Wo_IsReacted($wo['comment']['id'], $wo['story']['user_id'],"comment") === true) {
                            echo '<span class="lightbox-comment-status-reaction-'.$wo['comment']['id'].' active-like"><i class="zmdi zmdi-thumb-up" style="font-size: 13px;color: #2196f3;"></i>  <span class="c_likes-'.$wo['comment']['id'].'"></span></span>';
                        } else {
                            echo '<span class="lightbox-comment-status-reaction-'.$wo['comment']['id'].'"><i class="zmdi zmdi-thumb-up" style="font-size: 13px;color: #888;"></i>  </span>';
                        }
                        ?>
                    </span>
                  <ul class="reactions-box reactions-lightbox-comment-container-<?php echo $wo['comment']['id']; ?>" data-id="<?php echo $wo['comment']['id']; ?>" style="margin-top: 0px;left: -5px;top: -46px;">
                      <li class="reaction reaction-like" data-reaction="Like" onclick="Wo_RegisterCommentReaction(<?php echo $wo['comment']['id']; ?>,'Like');">
						<div class="emoji emoji--like">
							<div class="emoji__hand"><div class="emoji__thumb"></div></div>
						</div>
					</li>
                    <li class="reaction reaction-love" data-reaction="Love" onclick="Wo_RegisterCommentReaction(<?php echo $wo['comment']['id']; ?>,'Love');">
						<div class="emoji emoji--love">
							<div class="emoji__heart"></div>
						</div>
					</li>
                    <li class="reaction reaction-haha" data-reaction="HaHa" onclick="Wo_RegisterCommentReaction(<?php echo $wo['comment']['id']; ?>,'HaHa');">
						<div class="emoji emoji--haha">
							<div class="emoji__face">
								<div class="emoji__eyes"></div>
								<div class="emoji__mouth">
									<div class="emoji__tongue"></div>
								</div>
							</div>
						</div>
					</li>
                    <li class="reaction reaction-wow" data-reaction="Wow" onclick="Wo_RegisterCommentReaction(<?php echo $wo['comment']['id']; ?>,'Wow');">
						<div class="emoji emoji--wow">
							<div class="emoji__face">
								<div class="emoji__eyebrows"></div>
								<div class="emoji__eyes"></div>
								<div class="emoji__mouth"></div>
							</div>
						</div>
					</li>
                    <li class="reaction reaction-sad" data-reaction="Sad" onclick="Wo_RegisterCommentReaction(<?php echo $wo['comment']['id']; ?>,'Sad');">
						<div class="emoji emoji--sad">
							<div class="emoji__face">
								<div class="emoji__eyebrows"></div>
								<div class="emoji__eyes"></div>
								<div class="emoji__mouth"></div>
							</div>
						</div>
					</li>
                    <li class="reaction reaction-angry" data-reaction="Angry" onclick="Wo_RegisterCommentReaction(<?php echo $wo['comment']['id']; ?>,'Angry');">
						<div class="emoji emoji--angry">
							<div class="emoji__face">
								<div class="emoji__eyebrows"></div>
								<div class="emoji__eyes"></div>
								<div class="emoji__mouth"></div>
							</div>
						</div>
					</li>
                  </ul>
              </div>

        <?php } ?>
      <span class="comment-options">
        <?php if ($wo['config']['second_post_button'] == 'reaction') { ?>

        <?php }else{ ?>
            <span class="comment-icons" style="display: inline-block;">
                <span class="pointer" id="LikeComment" onclick="Wo_RegisterCommentLike(<?php echo $wo['comment']['id']; ?>);">
                <?php if($wo['comment']['is_comment_liked'] !== true) { ?>
                <i class="zmdi zmdi-thumb-up" style="font-size: 13px;"></i>
                <?php } else { ?>
                <i class="zmdi zmdi-thumb-up active-like" style="font-size: 13px;"></i>
                <?php } ?>
                </span>
                <span id="comment-likes">
                <?php echo $wo['comment']['comment_likes'];?>
                </span> ·
            </span>
            <div style="display: inline-block;">
            <span class="pointer" id="WonderComment" onclick="Wo_RegisterCommentWonder(<?php echo $wo['comment']['id']; ?>);">
                <?php if($wo['comment']['is_comment_wondered'] !== true) { ?>
                <i class="zmdi zmdi-<?php echo $wo['second_post_button_icon'];?>" style="font-size: 13px;"></i>
                <?php } else {  ?>
                <i class="zmdi zmdi-<?php echo $wo['second_post_button_icon'];?> active-wonder" style="font-size: 13px;"></i>
                <?php } ?>
                </span>
            <span id="comment-wonders">
                <?php echo $wo['comment']['comment_wonders'];?>
            </span>
            </div>
            <?php if ($replies == 0) { ?>
            ·
            <span class="pointer" id="ReplyComment" onclick="Wo_OpenReplyBox(<?php echo $wo['comment']['id']; ?>);" style="display: inline-block;">
                <i class="zmdi zmdi-comment" style="font-size: 13px;"></i>
                <?php echo $replies;?>
            </span>
            <?php } ?>
        </span> 
      <?php } ?>
      <div class="comment-edit">
         <input type="text" class="form-control" value="<?php echo $wo['comment']['Orginaltext']?>" onkeyup="Wo_EditComment(this.value,<?php echo $wo['comment']['id']?>, event)" placeholder="<?php echo $wo['lang']['edit_comment']; ?>" dir="auto">
      </div>
	  <div class="delete-comment" id="delete-comment" style="margin-top: 10px;position: relative;display:none">
			<div style="width: 100%;padding: 10px 24px;box-shadow: none;border: 1px solid #ddd;">
				<div>
					<h4><?php echo $wo['lang']['delete_comment']; ?></h4>
				</div>
				<div>
					<p><?php echo $wo['lang']['confirm_delete_comment']; ?></p>
				</div>
				<div>
					<button id="delete-all-post" type="button" class="mdbtn btn btn-main"><i class="zmdi zmdi-delete" style="font-size: 19px;margin-top: -2px;margin-right: 5px;"></i> <?php echo $wo['lang']['delete']; ?></button>
				</div>
			</div>
		</div>
      <div class="comment-replies">
         <div class="comment-replies-text">
          <div class="reply-container"></div>
         </div>
         <?php if ($replies > 0) { ?>
         <div class="view-more-replies" onclick="Wo_ViewMoreReplies(<?php echo $wo['comment']['id'];?>);">
            <i class="fa fa-share fa-fw"></i> <?php echo $replies;?> <?php echo $wo['lang']['replies']?>
         </div>
         <?php } ?>
         <div class="comment-reply">
            <input type="text" class="form-control textarea" onkeyup="Wo_RegisterReply(this.value,<?php echo $wo['comment']['id']; ?>,<?php echo $wo['story']['publisher']['user_id']; ?>, event, <?php echo (!empty($wo['story']['publisher']['page_id'])) ? $wo['story']['publisher']['page_id'] : '0'; ?>)" placeholder="<?php echo $wo['lang']['reply_to_comment'];?>" dir="auto">
         </div>
      </div>
   </div>
</div>