<div class="ads-cont-wrapper">
	<?php if (count($wo['trans']) > 0): ?>
		<table class="table table-striped">
			<thead>
				<tr>
					<th><b><?php echo $wo['lang']['type']; ?></b></th>
					<th width="300"><b><?php echo $wo['lang']['status']; ?></b></th>
					<th><b><?php echo $wo['lang']['date']; ?></b></th>
					<th><b><?php echo $wo['lang']['amount']; ?></b></th>
				</tr>
			</thead>
			<tbody id="user-ads">
				<?php foreach ($wo['trans'] as $key => $transaction): ?>
					<tr data-ad-id="<?php echo $transaction['id']; ?>">
						<td><span><?php echo $transaction['kind']; ?></span></td>
						<td width="300"><span><?php echo $transaction['notes']; ?></span></td>
						<td><span><?php echo $transaction['transaction_dt']; ?></span></td>
						<td><span><?php echo Wo_GetCurrency($wo['config']['ads_currency']); ?><?php echo sprintf('%.2f', $transaction['amount'] ); ?></span></td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	<?php else: ?>
		<h5 class="search-filter-center-text empty_state">
			<svg xmlns="http://www.w3.org/2000/svg" class="feather" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M15,14V11H18V9L22,12.5L18,16V14H15M14,7.7V9H2V7.7L8,4L14,7.7M7,10H9V15H7V10M3,10H5V15H3V10M13,10V12.5L11,14.3V10H13M9.1,16L8.5,16.5L10.2,18H2V16H9.1M17,15V18H14V20L10,16.5L14,13V15H17Z"></path></svg> <?php echo $wo['lang']['no_transactions_found']; ?>
		</h5>
	<?php endif; ?>
</div>