<?php echo Wo_LoadPage('welcome/welcome-header');?>
<div class="wrapper">
 <?php echo Wo_LoadPage('welcome/welcome-header-logo');?>
  
    <?php
			$allow_switch = false;
			if ($wo['config']['sms_provider'] == 'twilio') {
        if( $wo['config']['sms_twilio_username'] !== "" AND  $wo['config']['sms_twilio_password'] !== "" ){
					if( $wo['config']['emailValidation'] == 1 ) {
						if( $wo['config']['sms_or_email'] == "sms" ) {
							$allow_switch = true;
						}
					}
				}
			} else if ($wo['config']['sms_provider'] == 'bulksms') {
        if( $wo['config']['sms_username'] !== "" AND  $wo['config']['sms_password'] !== "" ){
					if( $wo['config']['emailValidation'] == 1 ) {
						if( $wo['config']['sms_or_email'] == "sms" ) {
							$allow_switch = true;
						}
					}
				}
			} else if ($wo['config']['sms_provider'] == 'infobip') {
        if( $wo['config']['infobip_username'] !== "" AND  $wo['config']['infobip_password'] !== "" ){
					if( $wo['config']['emailValidation'] == 1 ) {
						if( $wo['config']['sms_or_email'] == "sms" ) {
							$allow_switch = true;
						}
					}
				}
			}
		?> 

    <?php if( $allow_switch ){ ?>
			<form  class="x_chooser login">
				<p class="title"><?php echo $wo['lang']['forgot_your_password']; ?></p>
        <button type="button" class="btn btn-main" id="recover_password_by_email" style="width: 47%;margin: 5px;">Recover by email</button>
        <button type="button" class="btn btn-main" id="recover_password_by_sms" style="width: 49%;margin: 5px;right:  0 !important;left: inherit;">Recover by sms</button>
			</form>
		<?php } ?>

    <form id="forgot-form" class="fadeInUp animated animated_9 recover_password_by_email login" method="post" <?php if( $allow_switch ){ echo 'style="display: none;"'; } ?>>
			<p class="title"><?php echo $wo['lang']['forgot_your_password']; ?></p>
      <input name="recoveremail" id="recoveremail" type="text" placeholder="<?php echo $wo['lang']['email'];?>" autofocus/>
      <?php if($wo['config']['reCaptcha'] == 1) {?>
        <div class="form-group" style="margin-top:10px;">
          <div class="g-recaptcha" data-sitekey="<?php echo $wo['config']['reCaptchaKey']?>"></div>
        </div>
      <?php } ?>
      <i class="zmdi zmdi-email"></i>
      <button>
      <i class="spinner"></i>
      <span class="state"><i class="zmdi zmdi-refresh zmdi-hc-fw"></i> <?php echo $wo['lang']['recover_password'];?></span>
      </button>
		</form>

    <form id="forgot-form-sms" class="fadeInUp animated animated_9 recover_password_by_sms login" method="post" style="display: none;">
			<p class="title"><?php echo $wo['lang']['forgot_your_password']; ?></p>
      <input name="recoverphone" id="recoverphone" type="text" placeholder="<?php echo $wo['lang']['phone_number'];?>" autofocus/>
      <i class="zmdi zmdi-phone"></i>
      <button>
      <i class="spinner"></i>
      <span class="state_sms"><i class="zmdi zmdi-refresh zmdi-hc-fw"></i> <?php echo $wo['lang']['recover_password'];?></span>
      </button>
		</form>

  <?php echo Wo_LoadPage('footer/welcome-b');?>
</div>

<script>
var working = false;
var $this = $('#forgot-form');
var $state = $this.find('button > .state');
var forgot_button_text = "<i class='zmdi zmdi-refresh zmdi-hc-fw'></i> <?php echo $wo['lang']['recover_password']?>";

var $this_sms = $('#forgot-form-sms');
var $state_sms = $this_sms.find('button > .state_sms');

$(function() {
  $('#recover_password_by_email').click(function(){
		$('.x_chooser').hide();
		$('.recover_password_by_email').show();
	});
	$('#recover_password_by_sms').click(function(){
		$('.x_chooser').hide();
		$('.recover_password_by_sms').show();
  });
  
  Wo_SetTimer();
  $this.ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=recover',
    beforeSend: function() {
      working = true;
      $this.addClass('loading');
      $state.html('<?php echo $wo['lang']['please_wait'] ?>');
    },
    success: function(data) {
      if (data.status == 200) {
        $this.addClass('ok');
        $state.html('<?php echo $wo['lang']['email_sent'] ?>');
        setTimeout(function () {
          $this.removeClass('ok loading');
          $state.html(forgot_button_text);
        }, 5000);
      } else {
        $state.html(forgot_button_text);
        $this.removeClass('ok loading', function () {
         $state.html(data.errors);
        });
      }
      working = false;
    }
  });

  $this_sms.ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=recoversms',
    beforeSend: function() {
      working = true;
      $this.addClass('loading');
      $state_sms.html('<?php echo $wo['lang']['please_wait'] ?>');
    },
    success: function(data) {
      if (data.status == 200) {
        $this_sms.addClass('ok');
        $state_sms.html('<?php echo $wo['lang']['recoversms_sent'] ?>');
				setTimeout(function () {
          $this.removeClass('ok loading');
          window.location.href = data.location;
        }, 5000);
      } else {
        $state.html(forgot_button_text);
        $this_sms.removeClass('ok loading', function () {
         $state_sms.html(data.errors);
        });
      }
      working = false;
    }
  });

});
</script>
