<?php echo Wo_LoadPage('welcome/welcome-header');?>
<div class="wrapper">
  <?php echo Wo_LoadPage('welcome/welcome-header-logo');?>
  <form class="login" id="reset-form" method="post">
    <p class="title"><?php echo $wo['lang']['reset_new_password_label']?></p>
    <input name="password" type="password" placeholder="<?php echo $wo['lang']['new_password'];?>" autofocus/>
    <i class="zmdi zmdi-dialpad"></i>
    <input type="hidden" name="id" value="<?php echo $_GET['code'];?>">
    <button>
       <i class="spinner"></i>
       <span class="state"><i class="zmdi zmdi-sign-in zmdi-hc-fw"></i> <?php echo $wo['lang']['reset_password'];?></span>
    </button>
  </form>
  <?php echo Wo_LoadPage('footer/welcome');?>
</div>
<?php echo Wo_LoadPage('welcome/welcome-users-profiles');?>
<script>
var working = false;
var $this = $('#reset-form');
var $state = $this.find('button > .state');
var reset_button_text = "<i class='zmdi zmdi-sign-in zmdi-hc-fw'></i> <?php echo $wo['lang']['reset_password']?>";
$(function() {
  $this.ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=reset_password',
    beforeSend: function() {
      working = true;
      $this.addClass('loading');
      $state.html('<?php echo $wo['lang']['please_wait'] ?>');
    },
    success: function(data) {
      if (data.status == 200) {
        $this.addClass('ok');
        $state.html('<?php echo $wo['lang']['welcome_'] ?>');
        setTimeout(function () {
         window.location.href = data.location;
        }, 1000);
      } else {
        $state.html(reset_button_text);
        $this.removeClass('ok loading', function () {
         $state.html(data.errors);
        });
      } 
      working = false;
    }
  });
});
</script>