<div id="welcomeheader">
<div class="container">
<div class="logo">
		<a href="<?php echo $wo['config']['site_url'];?>"><img src="<?php echo $wo['config']['theme_url'];?>/img/logo.<?php echo $wo['config']['logo_extension'];?>" alt="Logo"> </a>
	</div>
<div class="welcome-header">
     <?php if ($wo['config']['user_registration'] == 1): ?>
     	<div class="absul-right">
   		   <button class="mdbtn create-account" data-toggle="modal" data-target="#wellogmodal"><?php echo $wo['lang']['login']?></button>
   	    </div>
     <?php endif ?>
   	<div class="clear"></div>
</div>
</div>
</div>