<?php echo Wo_LoadPage('forum/headers/header'); ?>
<div role="tabpanel" class="tab-pane active list-group" id="threadreply">
		<div class="">
			<div class="blocksubhead"><?php echo $wo['lang']['reply']; ?>
			> <?php echo $wo['reply']['post_subject']; ?>
			</div>
		</div>
		<div class="col-md-12" id="quotereply-alert"></div>
		<div class="col-md-12">
			<form  class="form" id="quotereply" method="post">
				<div class="form-group">
					<label for="subject" class="col-md-2"><?php echo $wo['lang']['subject']; ?>:</label>
					<div class="col-md-10">
						<div class="form-group">
							<input type="text" name="subject" class="form-control" value="<?php echo($wo['reply']['post_subject']); ?>">
							
						    <div class="clear"></div>
						</div>
					</div>
					<div class="clear"></div>
				</div>

				<div class="form-group">
					<label for="replythread" class="col-md-2"><?php echo $wo['lang']['edit']; ?>:</label>
					<div class="col-md-10">
						<textarea id="newquotereply" name="content"><?php echo(br2nlf($wo['reply']['post_text'])); ?></textarea>
					</div>
					<div class="clear"></div>
				</div>
		        <div class="form-group">
		          <label class="col-md-2"></label>
		          <div class="col-sm-10">
		             <button type="submit" class="btn btn-main">
		             
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-save"><path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z"></path><polyline points="17 21 17 13 7 13 7 21"></polyline><polyline points="7 3 7 8 15 8"></polyline></svg> <?php echo $wo['lang']['save']; ?>
		             </button>
		          </div>
		          <div class="clear"></div>
		       </div>
              <div class="clear"></div>
			</form>
		</div>
		<div class="clear"></div>
	</div>
<?php if (isset($wo['bbcodeditor']) && $wo['bbcodeditor']): ?>
<script>
	jQuery(document).ready(function($) {


		$('#quotereply').ajaxForm({

	      url: Wo_Ajax_Requests_File()  +  '?f=editreply&rid=<?php echo $wo['reply']['id']; ?>&tid=<?php echo $wo['reply']['thread_id']; ?>&hash=' + $('.main_session').val(),
	      beforeSend: function() {
	        Wo_progressIconLoader($('#quotereply').find('button'));
	      },
	      success: function(data) {
	        scrollToTop();
	        if (data['status'] == 200) {
	        	
	         	$("#quotereply-alert").html('<div class="alert alert-success">'+ data['message'] +'</div>');
	         	window.location = data.url;
	          
	        } else {
	        	
	         	$("#quotereply-alert").html('<div class="alert alert-danger">' + data['message'] + '</div>');
	        } 
	        Wo_progressIconLoader($('#quotereply').find('button'));
	      }
		});
		$('#newquotereply').bbcode();
		$("#newquotereply").autogrow({vertical: true, horizontal: false});

	});

</script>
	
<?php endif ?>

<?php echo Wo_LoadPage('forum/headers/footer'); ?>