<?php echo Wo_LoadPage('forum/headers/header'); ?>
	<div role="tabpanel" class="tab-pane active list-group" id="threadreply">
		<div class="w-100">
			<div class="blocksubhead">
			<?php echo $wo['lang']['threads']; ?> 
			>
			<?php echo $wo['lang']['reply']; ?> 
			>
			<?php echo $wo['thread']['headline']; ?>
			</div>
		</div>
		<div class="col-md-12" id="newtopicreply-alert"></div>
		<div class="col-md-12">
			<form action="#" class="form" id="newtopicreply" method="post">
				<div class="form-group">
					<label for="subject" class="col-md-2"><?php echo $wo['lang']['subject']; ?>:</label>
					<div class="col-md-10">
						<input type="text" class="form-control" name="subject" id="subject" value="<?php echo $wo['thread']['headline']; ?>">
					</div>
				</div>
				<div class="form-group">
					<label for="replythread" class="col-md-2"><?php echo $wo['lang']['your_reply']; ?>:</label>
					<div class="col-md-10">
						<textarea id="replythread" name="content"></textarea>
					</div>
					<div class="clear"></div>
				</div>
		        <div class="form-group ">
		          <label class="col-md-2"></label>
		          <div class="col-sm-10">
		             <button type="submit" class="btn btn-main">
		                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-corner-up-left"><polyline points="9 14 4 9 9 4"></polyline><path d="M20 20v-7a4 4 0 0 0-4-4H4"></path></svg> <?php echo $wo['lang']['reply']; ?>
		             </button>
		          </div>
		       </div>
			</form>
		</div>
	</div>
<?php if (isset($wo['bbcodeditor']) && $wo['bbcodeditor']): ?>

<script>
	jQuery(document).ready(function($) {

		$('#newtopicreply').ajaxForm({

	      url: Wo_Ajax_Requests_File()  +  '?f=threadreply&tid=<?php echo $wo['thread']['id']; ?>&fid=<?php echo $wo['thread']['forum']; ?>&q=0&hash=' + $('.main_session').val(),
	      dataType:'json',
	      beforeSend: function() {
	        Wo_progressIconLoader($('#newtopicreply').find('button'));
	      },
	      success: function(data) {
	        scrollToTop();
	        if (data['status'] == 200) {
	        	
	         	$("#newtopicreply-alert").html('<div class="alert alert-success">'+ data['message'] +'</div>');
	         	window.location = data.url;
	          
	        } else {
	        	
	         	$("#newtopicreply-alert").html('<div class="alert alert-danger">' + data['message'] + '</div>');
	        } 
	        Wo_progressIconLoader($('#newtopicreply').find('button'));
	      }
		});
		
		$('#replythread').bbcode();
		$("#replythread").autogrow({vertical: true, horizontal: false});
	});
</script>
	
<?php endif ?>

<?php echo Wo_LoadPage('forum/headers/footer'); ?>