<div class="profile-style wonderful-user">
	<a href="<?php echo $wo['UsersList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['UsersList']['username']?>" class="user-image">
		<div class="avatar <?php echo Wo_RightToLeft('pull-left');?>">
			<img src="<?php echo $wo['UsersList']['avatar'];?>" alt="<?php echo $wo['UsersList']['name']; ?> Profile Picture" />
		</div>
	</a>
	<div class="info-part">
		<span class="user-popover" data-id="<?php echo $wo['UsersList']['id'];?>" data-type="<?php echo $wo['UsersList']['type'];?>">
			<a href="<?php echo $wo['UsersList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['UsersList']['username']?>" class="user-namelink">
				<span class="user-name" title="<?php echo $wo['UsersList']['name']; ?>">
					<?php echo $wo['UsersList']['name']; ?>
					<?php  if($wo['UsersList']['verified'] == 1) {   ?>
					<span class="verified-color">
						<i class="fa fa-check-circle" data-toggle="tooltip" title="<?php echo $wo['lang']['verified_user'];?>"></i>
					</span>
					<?php  } ?>
				</span>
			</a>
		</span>
		<div class="user-username">
			@<?php echo $wo['UsersList']['username']; ?>
		</div>
		<?php if($wo['config']['user_lastseen'] == 1 && $wo['UsersList']['showlastseen'] != 0) { ?>
		<div class="user-lastseen">
			<?php echo Wo_UserStatus($wo['UsersList']['user_id'],$wo['UsersList']['lastseen']); ?>
		</div>
		<?php } ?>
	
		<div class="user-follow-btn">
			<div class="user-follow-button">
				<?php echo Wo_GetFollowButton($wo['UsersList']['user_id']);?>
			</div>
		</div>
	</div>
</div>