<div class="sidebar-user-data">
   <a href="<?php echo $wo['album']['url'];?>" data-ajax="?link1=post&id=<?php echo $wo['album']['id']?>" data-toggle="tooltip" title = "<?php echo $wo['album']['album_name']; ?>">
      <div class="sidebar-listed-user-avatar">
         <img src="<?php echo $wo['album']['first_image']?>">
      </div>
      <div class="sidebar-listed-user-name"><?php echo $wo['album']['album_name'];?></div>
   </a>
</div>