<div class="sidebar-user-data">
   <div class="sidebar-listed-user-avatar">
         <a class="avatarc" href="<?php echo $wo['GroupList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['GroupList']['username']?>">
            <img src="<?php echo $wo['GroupList']['avatar']?>">
         </a>
		 <a href="<?php echo $wo['GroupList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['GroupList']['username']?>">
            <div class="sidebar-listed-user-name"><?php echo $wo['GroupList']['name'];?></div>
         </a>
   </div>
</div>