<div class="sidebar-user-data">
   <div class="sidebar-listed-user-avatar">
         <a class="avatarc" href="<?php echo $wo['PageList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['PageList']['username']?>">
            <img src="<?php echo $wo['PageList']['avatar']?>">
         </a>
		 <a href="<?php echo $wo['PageList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['PageList']['username']?>">
            <div class="sidebar-listed-user-name"><?php echo $wo['PageList']['user_name'];?></div>
         </a>
   </div>
</div>