<div class="page-margin">
	<div class="row">
		<div class="col-md-2 leftcol"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
		<div class="col-md-7 middlecol wo-create-forms">
			<div class="wo_settings_page">
				<div class="sun_head_onboard shortpwidth event">
					<img class="sho_img" src="<?php echo $wo['config']['theme_url'];?>/img/cads/event.svg" alt="<?php echo $wo['lang']['event'] ?>" />
					<span class="go_back_link">
						<a href="<?php echo Wo_SeoLink('index.php?link1=my-events'); ?>" data-ajax="?link1=my-events">
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-left"><polyline points="15 18 9 12 15 6"></polyline></svg><?php echo $wo['lang']['my_events'];?>
						</a>
					</span>
					<div class="sun_head_onboard_innr">
						<h2><?php echo $wo['lang']['create'];?> <?php echo $wo['lang']['event'];?></h2>
					</div>
				</div>
				
				<form  class="form form-horizontal" method="post" id="insert-event" >
					<div class="setting-panel row">
						<div class="form-group col-lg-12">
							<label class="col-md-12" for="event-name"><?php echo $wo['lang']['name']; ?>:</label>  
							<div class="col-md-12">
								<input name="event-name" id="event-name" type="text" class="form-control"> 
							</div>
						</div>
						<div class="form-group">
							<label class="col-md-12" for="event-description"><?php echo $wo['lang']['description'] ?>:</label>  
							<div class="col-md-12">
								<textarea name="event-description" id="event-description" class="form-control" rows="5"></textarea>
							</div>
						</div>
						<div class="form-group col-lg-12">
							<label class="col-md-12" for="event-locat"><?php echo $wo['lang']['location']; ?>:</label>  
							<div class="col-md-12">
								<input id="event-locat" name="event-locat" type="text" class="form-control"> 
							</div>
						</div>
						<?php if ($wo['config']['google_map'] == 1) { ?>
						<div class="form-group col-lg-12" id="review-location">
							<div class="col-md-12" id="place"></div>
						</div>
					    <?php } ?>
						<div class="form-group col-lg-12">
							<label class="col-md-12" for="event-start"><?php echo $wo['lang']['start_date']; ?></label>  
							<div class="col-md-6">
								<input type="text" class="form-control date" id="event-start" name="event-start-date">
							</div>
							<div class="col-md-6">
								<input type="text" class="form-control time1" name="event-start-time">
							</div>
						</div>
						<div class="form-group col-lg-12">
							<label class="col-md-12" for="event-end-date"><?php echo $wo['lang']['end_date']; ?>:</label>  
							<div class="col-md-6">
								<input type="text" class="form-control date1" name="event-end-date" id="event-end-date">
							</div>
							<div class="col-md-6">
								<input type="text" class="form-control time1" name="event-end-time">
							</div>
						</div>
						
						<div class="form-group col-lg-12">
							<label class="col-md-12" for="event-description"><?php echo $wo['lang']['cover'] ?>:</label>  
							<div class="col-md-12">
								<div class="select_ev_covr" id="select-cover">
									<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M5,3A2,2 0 0,0 3,5V19A2,2 0 0,0 5,21H14.09C14.03,20.67 14,20.34 14,20C14,19.32 14.12,18.64 14.35,18H5L8.5,13.5L11,16.5L14.5,12L16.73,14.97C17.7,14.34 18.84,14 20,14C20.34,14 20.67,14.03 21,14.09V5C21,3.89 20.1,3 19,3H5M19,16V19H16V21H19V24H21V21H24V19H21V16H19Z" /></svg>
									<?php echo $wo['lang']['select_image'] ?>    
								</div>
							</div>
						</div>
					</div>
					
					<div class="setting-update-alert" id="event-alert"></div>
	   
					<div class="form-group last-sett-btn modal-footer">
						<div class="ball-pulse"><div></div><div></div><div></div></div>
						<button type="submit" class="btn btn-main setting-panel-mdbtn"><?php echo $wo['lang']['publish']; ?></button>
					</div>
					<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
					<input type="file" name="event-cover" class="hidden" id="event-cover">
				</form>
			</div>
		</div>
		<!-- .col-md-8 -->
		<?php echo Wo_LoadPage('sidebar/content');?>
	</div>
</div>
<script src="https://cdn.jsdelivr.net/npm/jquery-ui-timepicker-addon@1.6.3/dist/jquery-ui-timepicker-addon.min.js"></script>
<script>
  jQuery(document).ready(function($) {
      $( ".date" ).datepicker({ dateFormat: 'yy-mm-dd', minDate: 'today',prevText: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M15.41,16.58L10.83,12L15.41,7.41L14,6L8,12L14,18L15.41,16.58Z" /></svg>',nextText: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M8.59,16.58L13.17,12L8.59,7.41L10,6L16,12L10,18L8.59,16.58Z" /></svg>'});
      $( ".date1" ).datepicker({ dateFormat: 'yy-mm-dd', minDate: '+1day',prevText: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M15.41,16.58L10.83,12L15.41,7.41L14,6L8,12L14,18L15.41,16.58Z" /></svg>',nextText: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M8.59,16.58L13.17,12L8.59,7.41L10,6L16,12L10,18L8.59,16.58Z" /></svg>'});
      $( ".time1" ).timepicker();
      $("#select-cover").click(function(event) {
        $("#event-cover").click()
      });
      <?php if ($wo['config']['google_map'] == 1) { ?>
      $("#event-locat").change(function(event) {
        if ($(this).val().length >= 3) {
          $("#review-location #place").html('<iframe width="100%" frameborder="0" style="border:0;margin-top: 10px;" src="https://www.google.com/maps/embed/v1/place?key=<?php echo $wo['config']['google_map_api']; ?>&q=' + $("#event-locat").val() + '&language=en"></iframe>')
        }else{
          $("#review-location #place").html('<iframe width="100%" frameborder="0" style="border:0;margin-top: 10px;" src="https://www.google.com/maps/embed/v1/place?key=<?php echo $wo['config']['google_map_api']; ?>&q=us&language=en"></iframe>')
        }
      });
     <?php } ?>

      $("#event-cover").change(function(event) {
        $("#select-cover").html("<img src='" + window.URL.createObjectURL(this.files[0]) + "' alt='Picture'>")
      });

      $('#insert-event').ajaxForm({
            url: Wo_Ajax_Requests_File() + '?f=insert-event',
            beforeSend: function() {
              $('.wo_settings_page').find('.last-sett-btn .ball-pulse').fadeIn(100);
            },
            success: function(data) {
              scrollToTop();
              if (data['status'] == 200) {
                $("#event-alert").html('<div class="alert alert-success">'+ data['message'] +'</div>');
                window.location = data['url'];
              }
              else if (data['message']) {
                $("#event-alert").html('<div class="alert alert-danger">' + data['message'] + '</div>');
              } 
              $('.wo_settings_page').find('.last-sett-btn .ball-pulse').fadeOut(100);
            }
      });
  });
</script>