<div class="posts-container list-group">
	<div class="no-posts">
	<h1>
		<span class="zmdi-hc-stack zmdi-hc-lg bouncemation" style="-webkit-filter: drop-shadow(0px 9px 7px #ff98006e);filter: drop-shadow(0px 9px 7px #ff98006e);">
			<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #FF9800;"></i>
			<i class="zmdi zmdi-assignment-alert zmdi-hc-stack-1x zmdi-hc-inverse"></i>
		</span>
	</h1>
    <?php echo $wo['lang']['there_are_no_saved_posts'];?>
    </div>
</div>