<div class="posts-container list-group">
	<div class="no-posts">
		<h1>
			<span class="zmdi-hc-stack zmdi-hc-lg" style="-webkit-filter: drop-shadow(0px 9px 7px #e6890082);filter: drop-shadow(0px 9px 7px #e6890082);">
				<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #e68900;"></i>
				<i class="zmdi zmdi-alert-polygon zmdi-hc-stack-1x zmdi-hc-inverse"></i>
			</span>
		</h1>
		<?php echo $wo['lang']['no_posts_found'];?>
	</div>
</div>