<div class="posts-container list-group">
    <div class="no-posts">
		<h1>
			<span class="zmdi-hc-stack zmdi-hc-lg" style="-webkit-filter: drop-shadow(0px 9px 7px #8BC34A82);filter: drop-shadow(0px 9px 7px #8BC34A82);">
				<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #8BC34A;"></i>
				<i class="zmdi zmdi-storage zmdi-hc-stack-1x zmdi-hc-inverse"></i>
			</span>
		</h1>
        <?php echo $wo['lang']['no_one_posted'] ?> 
    </div>
</div>