<div class="post-container user-ad-container" id="<?php echo $wo['story']['id']; ?>">
	<div class="post-advertisement">
		<div class="sop-icon hidden-xs">
			<a href="<?php echo Wo_SeoLink('index.php?link1=ads'); ?>" target="_blank"><?php echo $wo['lang']['sponsored'];?></a>
		</div>
		<div class="panel panel-white panel-shadow">
			<div class="ads-heading">
				<div class="<?php echo Wo_RightToLeft('pull-left');?> ads-image">
					<a data-ajax="?link1=timeline&u=<?php echo $wo['story']['user_data']['username']?>" href="<?php echo $wo['story']['user_data']['url']?>">
						<img src="<?php echo $wo['story']['user_data']['avatar']; ?>" class="responsive-img">
					</a>
				</div>
		
				<div class="<?php echo Wo_RightToLeft('pull-right');?>">
					<span class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-down"><polyline points="6 9 12 15 18 9"></polyline></svg>
						</a>
						<ul class="dropdown-menu post-privacy-menu post-options" role="menu">
							<li>
								<div class="pointer" onclick="openInNewTab('https://www.facebook.com/sharer/sharer.php?u=<?php echo $wo['story']['url']; ?>', '<?php echo $wo['story']['id']; ?>')">
									<?php echo $wo['lang']['share'];?>
								</div>
							</li>
						</ul>
					</span>
				</div>
		 
				<div class="ads-meta">
					<div class="title h5">
						<a data-ajax="?link1=timeline&u=<?php echo $wo['story']['user_data']['username']?>" href="<?php echo $wo['story']['user_data']['url']?>">
							<b><?php echo $wo['story']['name']; ?></b>
						</a>
						<h6>
							<span class="time ajax-time" title="<?php echo date('c', $wo['story']['posted']); ?>">
								<?php echo Wo_Time_Elapsed_String($wo['story']['posted']); ?>
							</span>
							<?php if (strlen($wo['story']['location']) > 3): ?>
							<span class="time">
								<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-map-pin" style="width: 14px;height: 14px;"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg> <?php echo $wo['story']['location']; ?>
							</span>
							<?php endif;?>
						</h6>
					</div>
				</div>
				
				<div class="ads-headline">
					<p><?php echo htmlspecialchars_decode($wo['story']['description']); ?></p>
				</div>
				
				<div class="ads-cover rads-<?php echo $wo['story']['bidding']; ?> wo_post_ad" id="<?php echo $wo['story']['id']; ?>">
					<a href="<?php echo $wo['story']['url']; ?>" class="text-dnone">
						<h3><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-link"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"></path><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"></path></svg> <?php echo $wo['story']['headline']; ?></h3>
						<img src="<?php echo $wo['story']['ad_media']; ?>" alt="picture" class="responsive-img"/>
						<div class="ads-description">          
							<?php echo Wo_UrlDomain($wo['story']['url']); ?>        
						</div>
					</a>
				</div>
			</div>
			<div class="clear"></div>
		</div>
	</div>
</div>
<script>
function openInNewTab(url, id) {
   var myWindow = window.open(url, "", "width=600,height=700");
   return false;
}
</script>