<style>.setting-avatar {
    width: 100px;
    margin-right: 10px;
    margin: 0 auto;
    display: block;
}
</style>
<div class="container-fluid">
    <div class="block-header">
        <h2>Manage Features > Chat Stickers > Manage stickers</h2>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h2>Manage Stickers</h2>
                </div>
                <div class="body">
                   <input type="hidden" id="hash_id" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                   <div class="clearfix"></div>
                   <div class="table-responsive1">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                                <tr>
                                      <th>ID</th>
					                  <th>Name</th>
					                  <th>Media</th>
					                  <th>Added</th>
					                  <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                               <?php 
				                foreach (Wo_GetAllStickers(50000) as $wo['stickerlist']) {
				                  echo Wo_LoadAdminPage('manage-stickers/list');
				                }
				               ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->

<script>
$(function () {
	$('table').DataTable();
});

jQuery(document).ready(function($) {
   $(".delete-sticker").click(function(event) {
	    	$("#delete-sticker").attr('data-sticker-ident', $(this).attr('id')).modal('show');
	    });
});

function Wo_DeleteSticker(sticker_id) {
  if (confirm("Are you sure you want to delete this sticker?'") == false) {
    return false;
  }
  $('#StickerID_' + sticker_id).fadeOut(300, function() {
    $(this).remove();
  });
  $.get(Wo_Ajax_Requests_File(),{f:'admin_setting',s:'delete_sticker',sticker_id: sticker_id});
}
</script>