<tr data-status-id="<?php echo $wo['status']['id']?>">
   <td><?php echo $wo['status']['id']?></td>
   <td>
      <span><?php echo $wo['status']['expires']; ?></span>
   </td>
   <td>
      <a href="<?php echo $wo['status']['user_data']['url']; ?>">
        <img src="<?php echo $wo['status']['user_data']['avatar']; ?>" class="setting-avatar" alt="<?php echo $wo['status']['user_data']['name']?> Avatar Picture">
         <?php echo $wo['status']['user_data']['name']; ?>
      </a>
   </td>
   <td>
     <div class="ajax-time" title="<?php echo date('c',$wo['status']['posted']); ?>">
         <?php echo Wo_Time_Elapsed_String($wo['status']['posted']);?>
     </div>
   </td>
   <td>
      <button onclick="Wo_DeleteStatus(<?php echo $wo['status']['id']; ?>)" type="button" class="btn btn-danger waves-effect waves-light">DELETE</button>
   </td>
</tr>