<style>
@font-face {
    font-family: OpenSansLight;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/OpenSansLight/OpenSansLight.woff") format("woff");
    font-weight: normal;
}
@font-face {
    font-family: OpenSansRegular;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/OpenSansRegular/OpenSansRegular.woff") format("woff");
    font-weight: normal;
}
@font-face {
    font-family: OpenSansSemiBold;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/OpenSansSemiBold/OpenSansSemiBold.woff") format("woff");
    font-weight: normal;
}
@font-face {
    font-family: OpenSansBold;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/OpenSansBold/OpenSansBold.woff") format("woff");
    font-weight: normal;
}
.navbar-default {
    background: <?php echo $wo['config']['header_background'];?>; border: none;
    height:45px;
}
.round-check input[type="checkbox"]:checked + label:before {
    background: <?php echo $wo['config']['btn_background_color'];?> !important;
}
.group-messages-wrapper a{
    color: <?php echo $wo['config']['btn_background_color'];?> !important;
}
ul.profile-completion-bar li.completion-bar div.completion-bar-status {
    background: <?php echo $wo['config']['btn_background_color'];?> !important;
}
.featured-users{
    background: #fff !important;
}
.result-bar {
    background: <?php echo $wo['config']['btn_background_color'];?> !important;
}
.featured-users .sidebar-title-back, .featured-users .pro-me-here a {
    color: #444 !important;
}

.avtive {
    border-color: <?php echo $wo['config']['btn_background_color'];?> !important;
}
.loader {
  background-color: transparent !important;
}
.loader:before {
    background-color: #8dd9ff;
}
.left-sidebar ul li a i {
    color: <?php echo $wo['config']['btn_background_color'];?> !important;
}
.cs-loader-inner, .main  {
    color: <?php echo $wo['config']['btn_background_color'];?>;
}
.login input:focus, ul.profile-completion-bar li.completion-bar div.completion-bar-wrapper {
    border-color: <?php echo $wo['config']['btn_background_color'];?> !important;
}
.login:not(.loading) button:hover {
    background: <?php echo $wo['config']['btn_hover_background_color'];?> !important;
    color: <?php echo $wo['config']['btn_color'];?>;
}
.wo_setting_sidebar ul .list-group-item{
    background: <?php echo $wo['config']['btn_background_color'];?> !important;
}
.wo_setting_sidebar ul .list-group-item a{
    color: <?php echo $wo['config']['btn_color'];?>;
}
.wo_settings_page .setting-panel input[type=text]:focus, .wo_settings_page .setting-panel input[type=email]:focus, .wo_settings_page .setting-panel input[type=password]:focus, .wo_settings_page .setting-panel select:focus, .wo_settings_page .setting-panel textarea:focus {
    border-color: #03A9F4;
}

#search-nearby-users .nearby-users-relationship-collapse li.active .friends_toggle{
    border-color: <?php echo $wo['config']['btn_background_color'];?>;
}
#search-nearby-users .nearby-users-relationship-collapse li.active .friends_toggle:after{
    background: <?php echo $wo['config']['btn_background_color'];?>;
}
.my_pages_header ul li.active a{
    color: <?php echo $wo['config']['btn_background_color'];?>;
    border-color: <?php echo $wo['config']['btn_background_color'];?>;
}
.login button, .postCategory h5, .wo_search_page .nav-tabs li.active a {
    background: <?php echo $wo['config']['btn_background_color'];?> !important;
    color: <?php echo $wo['config']['btn_color'];?> !important;
}
.main-blog-sidebar .popular-categories li, #category-page .popular-categories li.active{ 
    background-color: <?php echo $wo['config']['btn_background_color'];?>;
}
.main-blog-sidebar .popular-categories li a, #category-page .popular-categories li.active a{
    color: <?php echo $wo['config']['btn_color'];?>;
}
.mejs-controls .mejs-time-rail .mejs-time-current, .mejs-controls .mejs-horizontal-volume-slider .mejs-horizontal-volume-current, .mejs-controls .mejs-volume-button .mejs-volume-slider .mejs-volume-current {
    background-color: <?php echo $wo['config']['btn_background_color'];?> !important;
    background: <?php echo $wo['config']['btn_background_color'];?> !important;
    background-image: <?php echo $wo['config']['btn_background_color'];?> !important;
}
.navbar-default .navbar-nav>.open>a, .navbar-default .navbar-nav>.open>a:focus, .navbar-default .navbar-nav>.open>a:hover {
    color: <?php echo $wo['config']['header_color'];?> !important;
    background-color: <?php echo $wo['config']['header_hover_border'];?> !important;
}
.navbar-default .navbar-nav>.active>a, .navbar-default .navbar-nav>.active>a:focus, .navbar-default .navbar-nav>.active>a:hover, .nav-names li:hover {
    color: <?php echo $wo['config']['header_color'];?> !important;
    background-color: <?php echo $wo['config']['header_hover_border'];?> !important;
}
body {
    background-color: <?php echo $wo['config']['body_background'];?>;
}
.navbar-default .navbar-nav>li>a {
    color: <?php echo $wo['config']['header_color'];?>;
    font-size: 13px;
}
a.unread-update {
    color: <?php echo $wo['config']['header_color'];?> !important;
}
.btn-main {
    color: <?php echo $wo['config']['btn_color'];?>;
    background-color: <?php echo $wo['config']['btn_background_color'];?>;
    border-color: <?php echo $wo['config']['btn_background_color'];?>;
}
.btn-main:hover {
    color: <?php echo $wo['config']['btn_hover_color'];?>;
    background-color: <?php echo $wo['config']['btn_hover_background_color'];?>;
    border-color: <?php echo $wo['config']['btn_hover_background_color'];?>;
}
.active-wonder {
    color: <?php echo $wo['config']['btn_background_color'];?>;
}
.admin-panel .col-md-9 .list-group-item:first-child, .setting-panel .col-md-8 .list-group-item:first-child, .profile-lists .list-group-item:first-child, .col-md-8 .list-group-item:first-child, .col-md-3.custom .list-group-item:first-child, .col-sm-4 .list-group-item:first-child, .col-md-7 .list-group-item:first-child, .col-md-9 .list-group-item:first-child, .red-list .list-group-item:first-child, .active.list-group-item:first-child {
     color: #444;
     background-color: #fcfcfc;
     border-bottom: 1px solid #f1f1f1;
     padding: 18px;
}
.admin-panel .col-md-9 .list-group-item:first-child a, .setting-panel .col-md-8 .list-group-item:first-child a, .profile-lists .list-group-item:first-child a, .col-md-8 .list-group-item:first-child a, .col-md-7 .list-group-item:first-child a, .active.list-group-item:first-child a {
    color: #444 !important;
}
.list-group-item.black-list.active-list, .red-list.active-list {
    color: <?php echo $wo['config']['btn_color'];?>;
    background-color: <?php echo $wo['config']['btn_background_color'];?>;
}
.list-group-item.black-list {
    background: <?php echo $wo['config']['btn_background_color'];?>;
}
.profile-top-line {
    background-color: <?php echo $wo['config']['btn_background_color'];?>;
}
#bar {
    background-color: <?php echo $wo['config']['btn_background_color'];?>;
}
.list-group-item.black-list a{
    color: <?php echo $wo['config']['btn_color'];?>;
}
.list-group-item.black-list.active-list a{
    color: <?php echo $wo['config']['btn_background_color'];?>;
}
.main-color, .small-text a {
    color: <?php echo $wo['config']['btn_background_color'];?> !important;
}
.nav-tabs>li.active>a, .nav-tabs>li.active>a:focus, .nav-tabs>li.active>a:hover {
    color: <?php echo $wo['config']['btn_color'];?>;
    cursor: default;
    color: <?php echo $wo['config']['btn_background_color'];?>;
    border-bottom: 1px solid <?php echo $wo['config']['btn_background_color'];?>;
    background-color: transparent
}
.btn-active {
    color: <?php echo $wo['config']['btn_color'];?>;
    background: <?php echo $wo['config']['btn_background_color'];?>;
    outline: none;
    border: 1px solid <?php echo $wo['config']['btn_background_color'];?>
}
.btn-active:hover, .btn-active:focus {
    border: 1px solid <?php echo $wo['config']['btn_hover_background_color'];?>;
    color: <?php echo $wo['config']['btn_hover_color'];?>;
    background: <?php echo $wo['config']['btn_hover_background_color'];?>;
}
.btn-active-color:hover {
    background: <?php echo $wo['config']['btn_hover_background_color'];?>;
}
.chat-tab .online-toggle {
    background: <?php echo $wo['config']['btn_background_color'];?>;
}
.profile-style .user-follow-button button.btn-active, .btn-login, .btn-register {
    background: <?php echo $wo['config']['btn_background_color'];?>;
    color: <?php echo $wo['config']['btn_color'];?>;
}
.profile-style .user-follow-button button.btn-active:hover, .btn-login:hover, .btn-login:focus, .btn-register:hover, .btn-register:focus {
    color: <?php echo $wo['config']['btn_hover_color'];?>;
    background: <?php echo $wo['config']['btn_hover_background_color'];?>;
}
.panel-login>.panel-heading a.active {
    color: <?php echo $wo['config']['btn_background_color'];?>;
    font-size: 18px;
}
.hash {
    color: <?php echo $wo['config']['btn_background_color'];?>;
}
.message-text .hash {
    color: #fff !important;
}
.search-container .search-input {
    color: <?php echo $wo['config']['header_color'];?> !important;
    background: <?php echo $wo['config']['header_search_color'];?> !important;
}
.chat-messages-wrapper .outgoing {
    background: <?php echo $wo['config']['chat_outgoing_background'];?>;
}
.normal-container {
    width: 100%;
    height: 100%;
    margin-top: 15px;
}
.active.fa-thumbs-up {
    color: <?php echo $wo['config']['btn_background_color'];?>;
}
.api-ex-urls {
    background-color: <?php echo $wo['config']['btn_background_color'];?>; color: <?php echo $wo['config']['btn_color'];?>;
}
.user-username {
    color: <?php echo $wo['config']['btn_background_color'];?>;
}
.upload-image {
    border: 3px dashed <?php echo $wo['config']['btn_background_color'];?>;
}
.events-tab-list li { background-color: <?php echo $wo['config']['btn_background_color'];?>; }
.events-tab-list li:hover { background-color: <?php echo $wo['config']['btn_background_color'];?>; }
.active-e-tab { background-color: <?php echo $wo['config']['btn_background_color'];?> !important; }
.main { color: <?php echo $wo['config']['btn_background_color'];?> !important; }
.events-list-dropup-menu ul li a:hover { background: <?php echo $wo['config']['btn_background_color'];?>; }
.usr-offline { color: <?php echo $wo['config']['btn_background_color'];?>; }
.blog-dd-ul li span:hover, .blog-dd-ul li a:hover { background: <?php echo $wo['config']['btn_background_color'];?> !important; }
.blog_publ {background: <?php echo $wo['config']['btn_background_color'];?> ; border: 1px solid <?php echo $wo['config']['btn_background_color'];?> ; }
.ads-navbar-wrapper {
    background-color: <?php echo $wo['config']['btn_background_color'];?> !important;
}
.slide-film-desc:hover, .movies-top-breadcrumb li:hover, .movies-top-breadcrumb li a:hover{
    color: <?php echo $wo['config']['btn_background_color'];?> !important;
}
.movies h3.latest-movies, h3.recommended-movies {
    border-left: 3px solid  <?php echo $wo['config']['btn_background_color'];?>;
}

.wo_user_profile .user-bottom-nav li .menuactive {
    border-bottom: 2px solid <?php echo $wo['config']['btn_background_color'];?>;
    color:<?php echo $wo['config']['btn_background_color'];?>;
}
.ads-navbar-wrapper ul li a.active {
     background-color: <?php echo $wo['config']['btn_hover_background_color'];?> !important;
}

<?php 
if ($wo['config']['chatSystem'] == 1 && $wo['page'] != 'get_news_feed' && $wo['page'] != 'welcome' && $wo['page'] != 'movies' && $wo['loggedin'] == true && $wo['page'] != 'messages') { ?>
body, .navbar-default, .wo_about_wrapper_parent{padding-right: 205px;}
@media (max-width:1140px){.wo_about_wrapper_parent{padding-right: 0px;}}
<?php } ?>

<?php if($wo['language_type'] == 'rtl' && $wo['config']['chatSystem'] == 1 && $wo['page'] != 'get_news_feed' && $wo['page'] != 'welcome' && $wo['page'] != 'movies' && $wo['page'] != 'messages' && $wo['loggedin'] == true) { ?>
body, .navbar-default, .wo_about_wrapper_parent{padding-left: 205px;padding-right: 0px;}
@media (max-width:1140px){.wo_about_wrapper_parent{padding-left: 0px;}}
<?php } ?>

#welcomeheader .mdbtn:hover{background-color: <?php echo $wo['config']['header_color'];?>;color: <?php echo $wo['config']['header_background'];?>;border-color: <?php echo $wo['config']['header_color'];?>;}

.post .panel.active_shadow {
    box-shadow: 0 0 0 1.5px <?php echo $wo['config']['btn_background_color'];?> !important;
}

.ui-widget-header .ui-state-default, .wo_adv_search_filter_side .ui-slider .ui-slider-range, .wo_adv_search_filter_side .ui-slider .ui-slider-handle {
    background-color: <?php echo $wo['config']['btn_background_color'];?>;
}

.reaction-like::before {
    content: "<?php echo $wo['lang']['like'];?>";
}
.reaction-love::before {
    content: "<?php echo $wo['lang']['love'];?>";
}
.reaction-haha::before {
    content: "<?php echo $wo['lang']['haha'];?>";
}
.reaction-wow::before {
    content: "<?php echo $wo['lang']['wow'];?>";
}
.reaction-sad::before {
    content: "<?php echo $wo['lang']['sad'];?>";
}
.reaction-angry::before {
    content: "<?php echo $wo['lang']['angry'];?>";
}

.navbar-default .dropdown-menu.ani-acc-menu >li>a:hover {
    color: <?php echo $wo['config']['btn_color'];?>;background-color: <?php echo $wo['config']['btn_background_color'];?>;
}

@media (min-width: 992px){
#wo_msg_right_prt .text-sender-container .outgoing .message-model .message p {
    color: <?php echo $wo['config']['btn_color'];?>;background-color: <?php echo $wo['config']['btn_background_color'];?>;
}
#wo_nw_msg_page .wo_msg_tabs, #wo_nw_msg_page .messages-users-list {
    color: <?php echo $wo['config']['header_color'];?>;
    background: <?php echo $wo['config']['header_background'];?>;
}
#wo_nw_msg_page .wo_msg_tabs a {
    color: <?php echo $wo['config']['header_color'];?>;
}
#wo_nw_msg_page .wo_msg_tabs .active a {
    color: <?php echo $wo['config']['btn_background_color'];?>;
}
#wo_nw_msg_page .messages-recipients-list .msg_ava_name {
    color: <?php echo $wo['config']['header_color'];?> !important;
}
#wo_nw_msg_page .messages-recipients-list.active .msg_ava_name {
    color: #333 !important;
}
}
<?php if ($wo['config']['google_map'] == 0) { ?>
#filterby-post li {
    width: 16.5%;
}
<?php }?>
</style>