<?php 
$message_count = Wo_CountMessages(array('new' => true,'user_id' => $wo['chatList']['user_id']));  
?>
<div class="recipient-chat-user" id ="online_<?php echo $wo['chatList']['user_id'];?>" >
   <div class="user-info" onclick="Wo_OpenChatTab(<?php echo $wo['chatList']['user_id'];?>);">
      <div class="<?php echo Wo_RightToLeft('pull-right');?>" style="margin-right:5px; margin-top:7px;">
         <span class="new-message-alert <?php echo ($message_count == 0) ? 'hidden' : ''; ?>">
         <?php echo $message_count; ?>
         </span>
         <span class="chat-loading-icon"></span>
      </div>
      <span class="chat-user-text" id="chat-tab-id">
         <div class="avatar <?php echo Wo_RightToLeft('pull-left');?>">
			<div class="icon online">
				<i class="fa fa-circle"></i>
			</div>
            <img src="<?php echo $wo['chatList']['avatar'];?>" alt="<?php echo $wo['chatList']['avatar'];?> Profile Picture" />
         </div>
         <span class="wo_cen_onuser"><?php echo $wo['chatList']['name']; ?></span>
      </span>
      <!--<div class="user-lastseen" >
         <span class="online-text"> <?php echo $wo['lang']['online']; ?></span>
      </div>-->
   </div>
</div>
<div class="clear"></div>