<div class="wo_settings_page">
   <h3>
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg>
    <?php echo $wo['lang']['delete_page'];?> 
    </h3>

   <form action="#" method="post" class="form-horizontal setting-delete-page-form">
         <div class="setting-delete-page-alert setting-update-alert"></div>
         <div class="setting-panel row">
         <div class="form-group col-lg-12">
            <label class="col-md-12" for="password"><?php echo $wo['lang']['password']; ?></label>
            <div class="col-md-12">
               <input id="password" name="password" type="password" class="form-control input-md">
            </div>
         </div>
         </div>
         <input type="hidden" name="page_id" value="<?php echo $wo['setting']['page_id'];?>">
         <div class="form-group last-sett-btn modal-footer">
      <div class="ball-pulse"><div></div><div></div><div></div></div>
      <button type="submit" class="btn btn-main setting-panel-mdbtn">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-check-circle"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path><polyline points="22 4 12 14.01 9 11.01"></polyline></svg> 
        <?php echo $wo['lang']['delete']; ?>
      </button>
    </div>

      <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
   </form>

</div>
<script type="text/javascript">
$(function() {
  $('form.setting-delete-page-form').ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=pages&s=delete_page',
    beforeSend: function() {
      $('.wo_settings_page').find('.last-sett-btn .ball-pulse').fadeIn(100);
    },
    success: function(data) {
      if (data.status == 200) {
        $('.setting-delete-page-alert').html('<div class="alert alert-success">' + data.message + '</div>');
        $('.alert-success').fadeIn('fast', function() {
          window.setTimeout(function() {
            window.location.href = data.location;
          },2000);
        });
      } else {
        var errors = data.errors.join("<br>");
        $('.setting-delete-page-alert').html('<div class="alert alert-danger">' + errors + '</div>');
        $('.alert-danger').fadeIn(300);
      }
      $('.wo_settings_page').find('.last-sett-btn .ball-pulse').fadeOut(100);
    }
  });
});
</script>