<ul class="nav navbar-nav navbar-right <?php echo Wo_RightToLeft('pull-right');?>">
   <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
      <i class="zmdi zmdi-account" style="font-size: 17px;margin: -1px 4px 0px 0px;"></i> <?php echo $wo['lang']['guest']; ?> 
      <span class="caret"></span>
      </a>
      <ul class="dropdown-menu" role="menu">
         <li>
            <a href="<?php echo Wo_SeoLink('index.php?link1=welcome&last_url=' . $wo['actual_link']);?>">
            <?php echo $wo['lang']['login']; ?>
            </a>
         </li>
         <li>
            <a href="<?php echo Wo_SeoLink('index.php?link1=welcome&last_url=' . $wo['actual_link']);?>">
            <?php echo $wo['lang']['register']; ?>
            </a>
         </li>
         <li>
            <a href="<?php echo $wo['config']['site_url'] . '/?mode=change' ?>">
                <?php echo $wo['lang']['night_mode']; ?>
            </a>
         </li>
      </ul>
   </li>
</ul>