<div class="home-sidebar profile-style" style="margin-right: 0px;">
<a href="<?php echo $wo['UsersList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['UsersList']['username']?>" style="white-space: nowrap;max-width: 150px;overflow: hidden;text-overflow: ellipsis;display: inline-block;">
    <div class="avatar <?php echo Wo_RightToLeft('pull-left');?>">
            <img src="<?php echo $wo['UsersList']['avatar'];?>" alt="<?php echo $wo['UsersList']['name']; ?> Profile Picture" />
     </div>
     <span class="user-popover" data-id="<?php echo $wo['UsersList']['id'];?>" data-type="<?php echo $wo['UsersList']['type'];?>">
    
        <span class="user-name">
            <?php echo $wo['UsersList']['name']; ?>
            <?php  if($wo['UsersList']['verified'] == 1) {   ?>
            <span class="verified-color">
            <i class="fa fa-check-circle" data-toggle="tooltip" title="<?php echo $wo['lang']['verified_user'];?>"></i>
            </span>
            <?php  } ?>
        </span>
    
    </span>
   <!-- <div class="user-username">
        @<?php echo $wo['UsersList']['username']; ?>
    </div>-->
    <?php if($wo['config']['user_lastseen'] == 1 && $wo['UsersList']['showlastseen'] != 0) { ?>
    <div class="user-lastseen togglastsee">
        <?php echo Wo_UserStatus($wo['UsersList']['user_id'],$wo['UsersList']['lastseen']); ?>
    </div>
    <?php } ?>
	</a>
	<div class="<?php echo Wo_RightToLeft('pull-right');?> user-follow-btn" style="position: relative;">
        <div class="user-follow-button">
            <?php echo Wo_GetFollowButton($wo['UsersList']['user_id']);?>
        </div>
    </div>
</div>