<tr id="<?php echo $wo['lang_key'];?>">
   <td><?php echo $wo['lang_id'];?></td>
   <td><?php echo $wo['lang_key'];?></td>
   <td id="edit_<?php echo $wo['lang_key'];?>"><?php echo $wo['langs'];?></td>
   <td>
      <button type="button" class="btn btn-default waves-effect btn-lang m-r-20" data-id="<?php echo $wo['lang_key'];?>" data-toggle="modal" data-target="#defaultModal">EDIT</button>
   </td>
</tr>