<div class="page-margin">
	<div class="row">
		<div class="col-md-2 leftcol"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
		<div class="col-md-7 middlecol wo-create-forms">
			<h3 class="wo_create_form_cover">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-play-circle"><circle cx="12" cy="12" r="10"></circle><polygon points="10 8 16 12 10 16 10 8"></polygon></svg>
				<?php echo $wo['lang']['create_new_status'];?>
				<!-- <span class="<?php echo Wo_RightToLeft('pull-right');?>">
					<a data-ajax="?link1=timeline&u=<?php echo $wo['user']['username'];?>" href="<?php echo $wo['user']['url']; ?>">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-left"><polyline points="15 18 9 12 15 6"></polyline></svg><?php echo $wo['lang']['status'];?>
					</a>
				</span> -->
				<div class="clear"></div>
			</h3>

            <div class="wo_settings_page">
				<form class="create-user-story form-horizontal" method="post">
					<div class="setting-panel row">
						<!-- Text input-->
						<!-- <div class="form-group col-lg-12">
							<label class="col-md-12" for="group_name"><?php echo $wo['lang']['title'];?> *</label>  
							<div class="col-md-12">
								<input name="title" type="text" class="form-control input-md">
							</div>
						</div> -->
						<div class="form-group col-lg-12">
							<label class="col-md-12" for="about"><?php echo $wo['lang']['whats_going'];?></label>  
							<div class="col-md-12">
								<textarea name="description" id="" rows="3" class="form-control input-md"></textarea>
							</div>
						</div>
						<div class="form-group col-lg-12">
							<label class="col-md-12" for="group_name"><?php echo $wo['lang']['select'];?> *</label>
      						<div class="col-md-12" title="Select media">
      							<div id="select-status-media">
      								<p class="img">			
      									<span>
											<span style="display:block">
											<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-image"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><circle cx="8.5" cy="8.5" r="1.5"></circle><polyline points="21 15 16 10 5 21"></polyline></svg>
											</span>
											<?php echo $wo['lang']['select']; ?>
											<?php echo $wo['lang']['photos']; ?> &amp; <?php echo $wo['lang']['videos']; ?>
										</span>
      									
      								</p>
      							</div>
      						</div>
						</div>
						<div class="form-group hidden col-lg-12" id="user-story-total">
							<label class="col-md-12"></label>  
							<div class="col-md-12">
								<input type="text" class="form-control input-md bg_read_input" readonly>
							</div>
						</div>
					</div>
					 
					<div class="create-status-alert hidden">
						<div class="alert alert-danger">
                           <p><?php echo $wo['lang']['max_number_status'] ?></p>
                        </div>
					</div>
					
					<div class="form-group last-sett-btn modal-footer">
                        <div class="ball-pulse"><div></div><div></div><div></div></div>
						<button type="submit" class="btn btn-main setting-panel-mdbtn">
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus"><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line></svg>
							<?php echo $wo['lang']['create'];?>
						</button>
					</div>

					<input type="file" name="statusMedia[]" class="hidden" id="user-storymedia" multiple="multiple">
				</form>
			</div>
		</div>
		<!-- .col-md-8 -->
		<?php echo Wo_LoadPage('sidebar/content');?>
	</div>
	<!-- .row -->
</div>

<script>
   jQuery(document).ready(function($) {
      $("#user-storymedia").change(function () {
        var numFiles = this.files.length;
        if (numFiles > 20) {
         $("#user-storymedia").val('');
         $(".create-status-alert").removeClass('hidden');
        }
        else{
            $("#user-story-total input").val(numFiles + ' file(s) selected');
            $("#user-story-total").removeClass('hidden').slideDown(200);
        }

      });

      $("#select-status-media").click(function(event) {
         $("#user-storymedia").click();
      });

      $('.create-user-story').ajaxForm({
       url: Wo_Ajax_Requests_File() + '?f=status&s=new',
       type:"POST",
       beforeSend: function() {
        $('.wo_settings_page').find('.last-sett-btn .ball-pulse').fadeIn(100);
       },
       success: function(data) {
        scrollToTop();
        if (data['status'] == 200) {
          $(".create-status-alert").removeClass('hidden').html('<div class="alert alert-success">'+ data['message'] +'</div>');
          window.location = '<?php echo $wo['config']['site_url']; ?>';
        } 

        else if (data['message']) {
          $(".create-status-alert").removeClass('hidden').html('<div class="alert alert-danger">' + data['message'] + '</div>');
        } 

        $('.wo_settings_page').find('.last-sett-btn .ball-pulse').fadeOut(100);
      }});

   });
</script>