<div class="page-margin list-group"> 
   	  <div class="center-container">
        <h2><i class="fa fa-lg fa-fw fa-frown-o" style="color: <?php echo $wo['config']['btn_background_color'];?>"></i> 
        <?php echo $wo['lang']['oops_something_went_wrong'];?><br></h2>
        <h4><a href="<?php echo Wo_SeoLink('index.php?link1=go-pro');?>" data-ajax="?link1=go-pro" class="btn btn-lg btn-main">
        <?php echo $wo['lang']['try_again'];?></a></h4>
      </div>
</div>