<div class="wo_settings_page sun_sett_page">
	<h3><?php echo $wo['lang']['page_information'];?></h3>

	<form  method="post" class="form-horizontal setting-information-form">
		<div class="setting-information-alert setting-update-alert"></div>
		
		<div class="setting-panel row">
			<!-- Text input-->
            <div class="sun_input col-lg-6">
				<input id="company" name="company" type="text" class="form-control input-md" value="<?php echo $wo['setting']['company'];?>" placeholder="<?php echo $wo['lang']['company'];?>">
				<label class="plr15" for="company"><?php echo $wo['lang']['company'];?></label>  
            </div>
            <!-- Text input-->
            <div class="sun_input col-lg-6">
				<input id="phone" name="phone" type="text" class="form-control input-md" value="<?php echo $wo['setting']['phone'];?>" placeholder="<?php echo $wo['lang']['phone_number'];?>">
				<label class="plr15" for="phone"><?php echo $wo['lang']['phone_number'];?></label>  
            </div>

            <!-- Text input-->
            <div class="sun_input col-lg-6">
				<input id="address" name="address" type="text" class="form-control input-md" value="<?php echo $wo['setting']['address'];?>" placeholder="<?php echo $wo['lang']['location'];?>">
				<label class="plr15" for="address"><?php echo $wo['lang']['location'];?></label>  
            </div>
            <!-- Text input-->
            <div class="sun_input col-lg-6">
				<input id="website" name="website" type="text" class="form-control input-md" value="<?php echo $wo['setting']['website'];?>" placeholder="<?php echo $wo['lang']['website'];?>">
				<label class="plr15" for="website"><?php echo $wo['lang']['website']; ?></label>  
				<span class="help-block"><?php echo $wo['lang']['site_eg'];?></span>
            </div>
			
			<!-- Text input-->
			<div class="sun_input col-lg-12">
				<?php $text = br2nl($wo['setting']['about']); ?>         
				<textarea class="form-control" id="page_description" name="page_description" cols="20" rows="3" placeholder="<?php echo $wo['lang']['about'];?>"><?php echo $text;?></textarea>
				<label class="plr15" for="page_description"><?php echo $wo['lang']['about'];?></label>
			</div>
		</div>
         <div class="form-group last-sett-btn modal-footer">
			<div class="ball-pulse"><div></div><div></div><div></div></div>
			<button type="submit" class="btn btn-main setting-panel-mdbtn"><?php echo $wo['lang']['save']; ?></button>
		</div>
		<input type="hidden" name="page_id" value="<?php echo $wo['setting']['page_id'];?>">
		<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
	</form>
</div>
<script type="text/javascript">
   $(function() {
     $('form.setting-information-form').ajaxForm({
       url: Wo_Ajax_Requests_File() + '?f=pages&s=update_information_setting',
       beforeSend: function() {
         $('.wo_settings_page').find('.last-sett-btn .ball-pulse').fadeIn(100);
       },
       success: function(data) {
         if (data.status == 200) {
           scrollToTop();
           $('.setting-information-alert').html('<div class="alert alert-success">' + data.message + '</div>');
           $('.alert-success').fadeIn('fast', function() {
             $(this).delay(2500).slideUp(500, function() {
               $(this).remove();
             });
           });
         } else {
           var errors = data.errors.join("<br>");
           scrollToTop();
           $('.setting-profile-alert').html('<div class="alert alert-danger">' + errors + '</div>');
           $('.alert-danger').fadeIn(300);
         }
         $('.wo_settings_page').find('.last-sett-btn .ball-pulse').fadeOut(100);
       }
     });
   });
   <?php if ($wo['config']['google_map'] == 1) { ?>
   var pac_input = document.getElementById('address');
     (function pacSelectFirst(input) {
       // store the original event binding function
       var _addEventListener = (input.addEventListener) ? input.addEventListener : input.attachEvent;
       function addEventListenerWrapper(type, listener) {
         // Simulate a 'down arrow' keypress on hitting 'return' when no pac suggestion is selected,
         // and then trigger the original listener.
         if(type == "keydown") {
           var orig_listener = listener;
           listener = function (event) {
             var suggestion_selected = $(".pac-item-selected").length > 0;
             if(event.which == 13 && !suggestion_selected) {
               var simulated_downarrow = $.Event("keydown", {
                 keyCode: 40,
                 which: 40
               });
               orig_listener.apply(input, [simulated_downarrow]);
             }
             orig_listener.apply(input, [event]);
           };
         }
         // add the modified listener
         _addEventListener.apply(input, [type, listener]);
       }
       if(input.addEventListener)
         input.addEventListener = addEventListenerWrapper;
       else if(input.attachEvent)
         input.attachEvent = addEventListenerWrapper;
     })(pac_input);
   
     $(function () {
        var autocomplete = new google.maps.places.Autocomplete(pac_input);
     });
   <?php } ?>
</script>