<div class="blog-ls-box" data-rm-blog="<?php echo $wo['blog']['id'];?>">
    <div class="view-blog" id="<?php echo $wo['blog']['id']; ?>">
        <div class="article-image">
        	<img src="<?php echo $wo['blog']['thumbnail']; ?>" alt="<?php echo $wo['blog']['title']; ?>">
        </div>
        <div class="art-text">

          	<a class="main" href="<?php echo $wo['blog']['url']; ?>">
	         	<h4>
	         		<?php echo Wo_ShortText($wo['blog']['title'],30); ?>
	         	</h4>
            </a>

            <p class="art-description">
          	<?php echo $wo['blog']['description'];?>	
          	</p>

            <div class="blog-meta-desc">
	            <span class="<?php echo Wo_RightToLeft('pull-left');?>"> 
	            	<time>
		              	<i class="fa fa-clock-o  fa-fw"></i> 
		              	<?php echo date("d M Y",$wo['blog']['posted']); ?>
	            	</time>
	            	<small>
	            		<i class="fa fa-eye  fa-fw"></i> <?php echo $wo['blog']['view']; ?>
	            	</small>
	            </span>
		        <?php if ($wo['blog']['is_post_admin']):?>
		            <div class="dropdown dropup <?php echo Wo_RightToLeft('pull-right');?>">
		            	<i class="dropdown-toggle blog-dd-menu fa fa-angle-up" data-toggle="dropdown"></i>
			            <ul class="dropdown-menu post-privacy-menu post-options <?php echo Wo_RightToLeft('pull-right');?>" role="menu">
			                <li class="pointer"><a class="delete-blog" id="<?php echo $wo['blog']['id'];?>"><i class="fa fa-trash-o fa-fw" aria-hidden="true"></i> <?php echo $wo['lang']['delete']; ?></a></li>
			                <li><a href="<?php echo Wo_SeoLink('index.php?link1=edit-blog&id=' . $wo['blog']['id']) ?>" id="<?php echo $wo['blog']['id'];?>"><i class="fa fa-pencil-square-o fa-fw" aria-hidden="true"></i> <?php echo $wo['lang']['edit']; ?></a></li>
			            </ul>
		            </div>
	            <?php endif;?>
	            <div class="clear"></div>
            </div>
            
        </div>
    </div>
</div>