<div class="featureblog" data-rm-blog="<?php echo $wo['blog']['id']; ?>">
	<div class="blog-h-list view-blog" id="<?php echo $wo['blog']['id']; ?>">
		<a href="<?php echo $wo['blog']['url']; ?>" data-ajax="?link1=read-blog&id=<?php echo $wo['blog']['id']; ?>">
			<div class="avatar <?php echo Wo_RightToLeft('pull-left');?>">
				<img width="200" src="<?php echo $wo['blog']['thumbnail']; ?>" alt="<?php echo $wo['blog']['title']; ?>">
			</div>
		</a>
		<div class="blog-h-desc">
			<a class="main postCategory" href="<?php echo $wo['blog']['category_link']; ?>" data-ajax="?link1=blog-category&id=<?php echo $wo['blog']['category']; ?>">
				<h5><?php echo $wo['page_categories'][$wo['blog']['category']]; ?></h5>
			</a>
			<a href="<?php echo $wo['blog']['url']; ?>">
				<h3 class="art-title"><?php echo $wo['blog']['title']; ?></h3>
			</a>
		 	<div class="blog-meta-desc">
			 	<div class="postMeta--author-avatar">
				 	<a href="<?php echo $wo['blog']['author']['url']?>">
						<img src="<?php echo $wo['blog']['author']['avatar']?>" alt="User Image">
					</a>
				</div>
				<div class="postMeta--author-text">
					<a class="main" href="<?php echo $wo['blog']['author']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['blog']['author']['username']; ?>">
						<?php echo $wo['blog']['author']['name']; ?>
				 	</a>
					<span class="middot">·</span>
					<time>
						<?php echo date("d M Y",$wo['blog']['posted']); ?>
					</time>
				</div>
		 	</div>
			
			<p class="desc">
				<?php 
				$desc = str_replace('<br>', '', $wo['blog']['description']);
				echo $desc = mb_substr($desc, 0, 100, "UTF-8") . ".."; ?>
			</p>
			
			<div class="postFooter row">
				<div class="u-floatLeft <?php echo Wo_RightToLeft('pull-left');?>">
					<a href="<?php echo $wo['blog']['url']; ?>" class="main">
						<?php echo $wo['lang']['read_more'] ?>
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg>
					</a>
				</div>
				<div class="u-floatRight <?php echo Wo_RightToLeft('pull-right');?>">
					<a href="<?php echo $wo['blog']['url']; ?>#respond" class="metaFont metaLink">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-message-circle"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"></path></svg>
						<span class="hidden-xs"> <?php echo $wo['lang']['comments'] ?></span>
					</a>
				</div>
			</div>
		</div>
	</div>
</div>