<span class="user-follow-request-<?php echo $wo['follow']['user_id'];?>">
<span class="accept-btns">
<button type="button" onclick="Wo_AcceptFollowRequest(<?php echo $wo['follow']['user_id'];?>)" class="wabe btn btn-default btn-sm" style="height: 30px;">
<i class="fa fa-clock-o progress-icon" data-icon="clock-o"></i>
<span class="button-text"> <?php echo $wo['lang']['accept'];?></span>
</button>
</span>
</span>