<span id="Follow-<?php echo $wo['follow']['user_id']?>">
    <button type="button" onclick="Wo_RegisterFollow(<?php echo $wo['follow']['user_id'];?>)" class="btn btn-default btn-sm wabe" id="add-friend-btn" style="height:30px;">
       <i class="zmdi zmdi-account-add" style="font-size: 15px;margin: -2px 3px 0px 0px;"></i>
       <span class="button-text"> <?php echo $wo['lang']['add_friend'];?></span>
    </button>
</span>