<span id="join-<?php echo $wo['join']['id']?>">
    <button type="button" onclick="Wo_RegisterGroupJoin(<?php echo $wo['join']['id'];?>, <?php echo ($wo['join']['join_privacy'] == 2) ? 1 : 0;?>)" class="wabe btn-requested btn btn-default btn-sm" id="group-join-btn" style="height:30px;">
       <i class="zmdi zmdi-time" style="font-size: 15px;margin: -2px 3px 0px 0px;"></i>
       <span class="button-text"> <?php echo $wo['lang']['requested'];?></span>
    </button>
</span>