<span id="like-<?php echo $wo['like']['page_id']?>">
    <button type="button" onclick="Wo_RegisterPageLike(<?php echo $wo['like']['page_id'];?>)" class="wabe btn btn-active btn-default btn-sm" style="height:30px">
       <i class="zmdi zmdi-check" style="font-size: 15px;margin: -2px 3px 0px 0px;"></i>
       <span class="button-text"> <?php echo $wo['lang']['liked'];?></span>
    </button>
</span>