<div class="profile-style user-data nearby_user_wrapper" id="<?php echo $wo['UsersList']['user_data']['id']; ?>">
  <div class="avatar <?php echo Wo_RightToLeft('pull-left');?>">
      <img src="<?php echo $wo['UsersList']['user_data']['avatar'];?>" alt="<?php echo $wo['UsersList']['user_data']['name']; ?> Profile Picture" />
    </div>
  <span class="user-popover" data-id="<?php echo $wo['UsersList']['user_data']['id'];?>" data-type="<?php echo $wo['UsersList']['user_data']['type'];?>">
  <a href="<?php echo $wo['UsersList']['user_data']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['UsersList']['user_data']['username'];?>"><?php echo $wo['UsersList']['user_data']['name']; ?></a>
  <?php if($wo['UsersList']['user_data']['verified'] == 1) {   ?>
        <span class="verified-color"><i class="fa fa-check-circle" title="<?php echo $wo['lang']['verified_user'];?>"></i></span>
  <?php  } ?>
  
  </span>
  <?php if($wo['config']['user_lastseen'] == 1 && $wo['UsersList']['user_data']['showlastseen'] != 0): ?>
  <div class="user-lastseen">
    <?php
      if ($wo['UsersList']['user_data']['age'] && $wo['UsersList']['user_data']['birth_privacy'] == 0) {
        echo $wo['UsersList']['user_data']['age'];
      } else {
        echo Wo_UserStatus($wo['UsersList']['user_data']['user_id'], $wo['UsersList']['user_data']['lastseen']);
      }
    ?>
  </div>

  <?php endif; ?>
  <?php if (!empty($wo['UsersList']['user_geoinfo']) && (!empty($wo['user']['lat']) && !empty($wo['user']['lng'])) && ($wo['UsersList']['distance'] > 0)): ?>
    <div class="user-follow-button pull-left pointer">
     <small data-toggle='tooltip' title="<?php echo $wo['lang']['show_location']; ?>">
       <span onclick="Wo_ShowUserLocationMap('<?php echo $wo['UsersList']['user_geoinfo']?>');">
        <i class="fa fa-map-marker" aria-hidden="true"></i> <?php echo $wo['lang']['close_to_u']; ?> <?php echo number_format($wo['UsersList']['distance'],3); ?>/k
       </span>
     </small>
    </div>
  <?php endif; ?>

  <div class="user-follow-button pull-right">
    <?php echo Wo_GetFollowButton($wo['UsersList']['user_data']['user_id']);?>
  </div>
  <div class="clear"></div>
</div>
