<tr tabindex="1" class="mythread-list" data-thread-ident="<?php echo $wo['thread']['id']; ?>">
	<td class="">
		<div class="threadcont-inner">
	    	<div >
	    		<a class="flink" 
	    		href="<?php echo $wo['thread']['url'];?>" data-ajax="?link1=showthread&tid=<?php echo $wo['thread']['id'];?>"
	    		>
		        	<?php 
		        		
		        		if(strlen($wo['thread']['headline']) > 55){
		        			echo Wo_GetShortTitle($wo['thread']['headline'], false, 50);
		        		}
		      			else {
		      				echo $wo['thread']['headline'];
		      			}
		        	?>	
	        	</a>
	    	</div>
	    	<div class="thread-info">
		    	<span class="blog-meta-desc"><i><?php echo $wo['lang']['by']; ?></i> <a href="<?php echo $wo['thread']['author_url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['thread']['user_data']['username']; ?>"><?php echo $wo['thread']['user_data']['username']; ?></a></span>
		    	<span>
		        	<?php echo Wo_Time_Elapsed_String($wo['thread']['posted']); ?>
		    	</span>
	    	</div>

		</div>
	</td>

	<td class="small">
		<h6><?php echo $wo['thread']['views']; ?> <?php echo $wo['lang']['views']; ?></h6> 
	</td>
	<td class="small">
		<h6>
		<?php if ($wo['thread']['last_post'] > 0): ?>
			<?php echo Wo_Time_Elapsed_String($wo['thread']['last_post']); ?>
		<?php else: ?>
			<?php echo $wo['lang']['never'] ?>
		<?php endif; ?>
				
		</h6>
	</td>
	<td class="small ">
		<a class="btn btn-default" href="<?php echo $wo['thread']['edit_url']; ?>" data-ajax="?link1=edithread&tid=<?php echo $wo['thread']['id'];?>">
	        <i class=" fa fa-pencil-square-o" aria-hidden="true"></i>        
        </a>
		<a class="btn btn-default delete-thread" id="<?php echo $wo['thread']['id']; ?>">
			<i class=" fa fa-trash" aria-hidden="true"></i>
		</a>
	</td>
</tr>