(function(d){d.fn.scroller=function(a){if("undefined"==typeof a&&"undefined"!=typeof d(this).attr("data-options")&&""!=d(this).attr("data-options")){var h=d(this).attr("data-options");eval("var aux_opts = "+h);a=aux_opts}a=d.extend({type:"normal",totalWidth:void 0,totalwidth:void 0,settings_multiplier:3,settings_skin:"skin_default",settings_scrollbar:"on",settings_scrollbyhover:"off",settings_fadeoutonleave:"off",settings_replacewheelxwithy:"off",settings_refresh:0,settings_autoheight:"off",settings_forcesameheight:"off",
    settings_fullwidth:"off",settings_hidedefaultsidebars:"off",settings_dragmethod:"drag",settings_autoresizescrollbar:"off",settings_slideshow:"0",scrollBg:"off",force_onlyy:"off",objecter:void 0,secondCon:null,secondCon_tw:null,secondCon_cw:null,secondCon_enable_mouse_scroll:"off",settings_smoothing:"off",enable_easing:"off",settings_disableSpecialIosFeatures:"off",settings_makeFunctional:!1,settings_chrome_multiplier:.04,settings_safari_multiplier:.04,settings_opera_multiplier:.01,settings_ie_multiplier:.08,
    settings_firefox_multiplier:-1},a);"undefined"==typeof a&&"undefined"!=typeof d(this).attr("data-options")&&""!=d(this).attr("data-options")&&(h=d(this).attr("data-options"),h="var aux_opts = "+h,eval(h),a=aux_opts);a.settings_refresh=parseInt(a.settings_refresh,10);a.settings_multiplier=parseFloat(a.settings_multiplier);a.settings_chrome_multiplier=parseFloat(a.settings_chrome_multiplier);a.settings_firefox_multiplier=parseFloat(a.settings_firefox_multiplier);a.settings_slideshow=parseFloat(a.settings_slideshow);
    Math.easeIn=function(a,d,h,V){return-h*(a/=V)*(a-2)+d};this.each(function(){function h(){0<a.settings_slideshow&&(w=null,W&&(W=!1,ba="plus"==ba?"minus":"plus"),s="plus"==ba?s+a.settings_slideshow:s-a.settings_slideshow,C());"on"==a.enable_easing&&x&&n&&(ca=X,la=da-ca,X=Math.easeIn(1,ca,la,20),"normal"==a.type&&k.css({top:parseInt(X,10)}),"scrollTop"==a.type&&d(window).scrollTop(-X));requestAnimFrame(h)}function ka(b){b.currentTarget==k.get(0)&&(ea=!0);a.secondCon&&b.currentTarget==a.secondCon.get(0)&&
    (fa=!0)}function za(a){if(0!=ma)return u&&(na=a.originalEvent.touches[0].pageX,y=Aa+(na-Ba),0<y&&(y/=2),y<-N+O&&(y-=(y+N-O)/2),oa.css("left",y),0<y&&(y=0),y<-N+O&&(y-=y+N-O)),x&&(pa=a.originalEvent.touches[0].pageY,z=Ca+(pa-Da),0<z&&(z/=2),z<-P+Q&&(z-=(z+P-Q)/2),oa.css("top",z),0<z&&(z=0),z<-P+Q&&(z-=z+P-Q)),!1}function V(a){ma=fa=ea=!1;a=0;u&&(a=y/-(N-O),qa(a));x&&(a=z/-(P-Q),r=a*-(v-f),D=a*(v-H),C())}function qa(b,c){var f={secondCon_targetX:""},f=d.extend(f,c);w=b*-(t-g);s=b*(g-A);null!=a.secondCon&&
    (B=b*-(J-F));""!=f.secondCon_targetX&&(B=f.secondCon_targetX);C()}function Ea(b){1<b&&(b/=t-g);w=b*-(t-g);s=b*(g-A);null!=a.secondCon&&(B=b*-(J-F));C()}function Fa(a){1<a&&(a/=v-f);r=a*-(v-f);D=a*(f-H);C()}function M(){d(window).width();Y=d(window).height();if(1==a.settings_makeFunctional){var b=!1,p=document.URL,l=p.indexOf("://")+3,h=p.indexOf("/",l),p=p.substring(l,h);-1<p.indexOf("a")&&-1<p.indexOf("c")&&-1<p.indexOf("o")&&-1<p.indexOf("l")&&(b=!0);-1<p.indexOf("o")&&-1<p.indexOf("z")&&-1<p.indexOf("e")&&
    -1<p.indexOf("h")&&-1<p.indexOf("t")&&(b=!0);-1<p.indexOf("e")&&-1<p.indexOf("v")&&-1<p.indexOf("n")&&-1<p.indexOf("a")&&-1<p.indexOf("t")&&(b=!0);if(0==b)return}g=void 0!=a.totalWidth?a.totalWidth:c.outerWidth(!1);void 0!=a.totalHeight&&0!=a.totalHeight?f=a.totalHeight:0!=c.height()&&(f=c.outerHeight(!1));"on"==a.settings_autoheight&&(f=k.children().children().eq(0).height());null!=a.secondCon&&(null==a.secondCon_tw&&(F=g),null==a.secondCon_cw&&(J=a.secondCon.width()));is_ie()&&7==version_ie()&&
    c.css("overflow","visible");"on"==a.settings_hidedefaultsidebars&&(c.css("overflow","hidden"),d("html").css("overflow","hidden"));k&&(t=k.width(),v=k.height(),0<k.find(".real-inner").length&&(t=k.find(".real-inner").outerWidth(),v=k.find(".real-inner").outerHeight(),k.css({width:t}),ra&&k.height(v),k.css({})));k&&sa&&c.height(k.height());"scrollTop"==a.type&&(f=d(window).height(),v=c.height());"on"==a.settings_forcesameheight&&(f=v);"on"==a.scrollBg&&(v=c.height(),f=d(window).height());x=v<=f?!1:
        !0;t<=g?u=!1:(u=!0,c.addClass("dir-hor"));"on"==a.force_onlyy&&(u=!1);"on"==a.force_onlyx&&(x=!1);"scrollTop"==a.type&&(x=!0);1==u?c.addClass("dir-hor"):c.removeClass("dir-hor");1==x?c.addClass("dir-ver"):c.removeClass("dir-ver");0==u&&void 0!=m&&(m.remove(),I.remove(),I=m=void 0);0==x&&void 0!=n&&(n.remove(),K.remove(),K=n=void 0);0==x&&0==u?c.addClass("no-need-for-nav"):(c.removeClass("no-need-for-nav"),"on"==a.settings_scrollbar&&(void 0==n&&x&&(E.append('<div class="scrollbary_bg"></div>'),E.append('<div class="scrollbary"></div>')),
    void 0==m&&u&&(E.append('<div class="scrollbarx_bg"></div>'),E.append('<div class="scrollbarx"></div>'))),void 0==n&&x&&(n=E.children(".scrollbary"),K=E.children(".scrollbary_bg"),H=n.height(),"on"==a.settings_autoresizescrollbar&&(b=f/v*f,n.css("height",b),H=b),K.css("height",f),"on"==a.settings_fadeoutonleave&&(n.css("opacity",0),K.css("opacity",0)),K.mousedown(function(b){Z=!0;a.settings_slideshow=0;R=G-n.offset().top+c.offset().top;"scrollTop"==a.type&&(R=G-n.offset().top+d(window).scrollTop());
        return!1}),n.mousedown(function(b){Z=!0;a.settings_slideshow=0;R=G-n.offset().top+c.offset().top;"scrollTop"==a.type&&(R=G-n.offset().top+d(window).scrollTop());return!1})),void 0==m&&u&&(m=E.children(".scrollbarx"),I=E.children(".scrollbarx_bg"),A=m.width(),"on"==a.settings_autoresizescrollbar&&(b=g/t*g,m.css("width",b),A=b),I.css("width",g),"on"==a.settings_fadeoutonleave&&(m.css("opacity",0),I.css("opacity",0)),t<=g&&"on"==a.settings_fullwidth&&(m.hide(),I.hide()),m.mousedown(function(b){$=!0;
        a.settings_slideshow=0;ta=L-m.offset().left+c.offset().left;return!1}),I.mousedown(function(b){$=!0;a.settings_slideshow=0;return!1})),m&&1==u&&(parseInt(m.css("left")),"on"==a.settings_autoresizescrollbar&&(b=g/t*g,m.css("width",b),A=b)),n&&1==x&&(parseInt(n.css("top")),"on"==a.settings_autoresizescrollbar&&(b=f/v*f,n.css("height",b),H=b)),m&&1==u&&I.css("width",g),m&&u&&g>t&&"block"==m.css("display")&&(I.hide(),m.hide()),m&&u&&g<t&&"none"==m.css("display")&&(I.show(),m.show()),n&&1==x&&K.css("height",
        f),C())}function Ga(){D=r=0;C()}function ga(){d(window).width();Y=d(window).height();M()}function aa(b){var p=d(this);S=T=!1;b=b||window.event;c.has(d(b.target));l=ua(b);q=va(b);l*=a.settings_multiplier;q*=a.settings_multiplier;Ha&&(l*=a.settings_chrome_multiplier,q*=a.settings_chrome_multiplier);Ia&&(l=ua(b),q=va(b),l*=a.settings_safari_multiplier,q*=a.settings_safari_multiplier);is_firefox()&&(l*=a.settings_firefox_multiplier,q*=a.settings_firefox_multiplier);is_opera()&&(l*=a.settings_opera_multiplier,
        q*=a.settings_opera_multiplier);is_ie()&&(l=0,q=wa(b),l*=a.settings_ie_multiplier,q*=a.settings_ie_multiplier);11<=getInternetExplorerVersion()&&(l=0,q=wa(b),l*=a.settings_ie_multiplier,q*=a.settings_ie_multiplier);"on"==a.settings_replacewheelxwithy&&0==l&&(l=q);if(c.get(0)==p.get(0)||a.secondCon&&a.secondCon.get(0)==p.get(0))if(x&&(r+=q*a.settings_multiplier,D=r/(v-f)*-(f-H)),u&&(w+=l*a.settings_multiplier,s=w/(t-g)*-(g-A),null!=a.secondCon)){if(void 0==B||isNaN(B))B=0;B+=J/t*a.settings_multiplier*
    l}C();0==u&&(T=!0);0==x&&(S=!0);if(0!=q&&0==S)if(0==is_ie8())b.stopPropagation(),b.preventDefault();else return!1;if(0!=l&&0==T)if(0==is_ie8())b.stopPropagation(),b.preventDefault();else return!1}function wa(a){if(a.originalEvent&&a.originalEvent.wheelDelta)return a.originalEvent.wheelDelta;if(a.wheelDelta)return a.wheelDelta;if(a.detail)return a.detail;if(void 0!=a.originalEvent&&void 0!=a.originalEvent.detail)return-40*a.originalEvent.detail}function ua(a){if(is_firefox())return 1==a.axis?a.detail:
        0;if(a.originalEvent&&a.originalEvent.wheelDeltaX)return a.originalEvent.wheelDeltaX;if(a.wheelDelta)return a.wheelDeltaX;if(void 0!=a.originalEvent&&a.originalEvent.detail)return-40*a.originalEvent.detail}function va(a){if(is_firefox())return 2==a.axis?a.detail:0;if(a.originalEvent&&a.originalEvent.wheelDeltaY)return a.originalEvent.wheelDeltaY;if(a.wheelDelta)return a.wheelDeltaY;if(void 0!=a.originalEvent&&a.originalEvent.detail)return-40*a.originalEvent.detail}function C(b){var p={animate_inner:"on",
        animate_sc:"on"},p=d.extend(p,b);x&&(0<r&&(r=0),r<-(v-f)&&(r=-(v-f)),0>D&&(D=0,S=!0),D>f-H&&(D=f-H,S=!0),n&&(c.hasClass("easing"),"normal"==a.type&&("on"!=a.enable_easing?k.css({top:r}):da=r),"scrollTop"==a.type&&("on"!=a.enable_easing?d(window).scrollTop(-r):da=r),n.css({top:D}),"on"==a.scrollBg&&c.css("background-position","center "+r+"px")));m&&u&&(null==w&&(w=s/(g-A)*(g-t)),w<-(t-g)&&(w=-(t-g)),0<w&&(w=0),null!=a.secondCon&&(B<-(J-F)&&(B=-(J-F)),0<B&&(B=0)),0>s&&(s=0,W=T=!0),s>g-A&&(s=g-A,W=T=
        !0),"on"!=a.settings_smoothing?("on"==p.animate_inner&&k.css({left:w}),m.css({left:s}),null!=a.secondCon&&"on"==p.animate_sc&&a.secondCon.css({left:B})):(p.animate_inner&&k.animate({left:w},{queue:!1,duration:60}),m.animate({left:s},{queue:!1,duration:60})))}function Ja(){var b=0,d=0,l=0,m=0;k&&(b=k.width()-c.width(),d=k.position().left,l=k.height()-c.height(),m=k.position().top);var h=null,n=null;if(a.secondCon){var h=a.secondCon,n=h.parent(),q=h.width()-n.width(),r=h.position().left;h.height();
        n.height();h.position()}xa&&c[0]==document.getElementById("scrollc3")&&(xa=!1);ea&&(s=-d/b*(g-A),D=-m/l*(f-A),b={animate_inner:"off"},h&&(B=-(s/(F-A)*(J-F))),C(b));fa&&(s=-r/q*(g-A),w=s/g*(g-t),b={animate_sc:"off"},C(b))}var g=0,f=0,t=0,v=0,Y=0,U=null,E=null,k=null,ra=!1,sa=!1,l=0,q=0,D=0,s=0,ea=!1,fa=!1,n=void 0,K=void 0,m=void 0,I=void 0,c=d(this),L=0,G=0,Z=!1,$=!1,H=0,A=0,ta=0,R=0,w=0,r=0,F,J,B,ha,T=!1,S=!1,u=!0,x=!0,ya=0,oa,O=0,Q=0,N=0,P=0,Aa=0,Ca=0,y=0,z=0,Ba,Da,na,pa,ma=!1,xa=!0,W=!1,ba="plus",
        X=0,ca=0,da=0,la=0,ia=!1,Ha=/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor),Ia=/Safari/.test(navigator.userAgent)&&/Apple Computer/.test(navigator.vendor);(function(){g=void 0==a.totalWidth?c.width():a.totalWidth;f=void 0==a.totalHeight?c.height():a.totalHeight;"normal"==a.type&&(k=c.find(".inner").eq(0));var b=String(c.attr("class"));-1==b.indexOf("skin_")&&c.addClass(a.settings_skin);b=String(c.attr("class"));(b=/(skin_.*?) /.exec(b))&&b[1]&&(a.settings_skin=b[1]);"normal"==
    a.type&&(k.wrap('<div class="scroller"></div>'),U=c.find(".scroller").eq(0));if(is_touch_device()&&"on"!=a.settings_disableSpecialIosFeatures){if("scrollTop"==a.type)return!1;U&&U.css("overflow","auto");a.secondCon&&a.secondCon.parent().css("overflow","auto");c.addClass("is-touch")}"scrollTop"==a.type&&(c.addClass("scroller-con type-scrollTop"),d("html").css("overflow-y","hidden"),setTimeout(function(){},1E3),c.bind("mousedown",function(a){ia=2==a.which?ia?!1:!0:!1}),c.bind("mousemove",function(a){ia&&
    (r=-(a.clientY/Y*(c.height()-Y)),C())}));ha=c;ha.append('<div class="scrollbar"></div>');E=ha.children(".scrollbar").eq(0);is_touch_device()&&E.addClass("easing");!k||""!=k.get(0).style.height&&"auto"!=k.get(0).style.height||(ra=!0);if(""==c.get(0).style.height||"auto"==c.get(0).style.height)sa=!0;M();0==c.css("opacity")&&(c.animate({opacity:1},600),c.parent().children(".preloader").fadeOut("slow"));0==ya&&(ya=t+50);c.hasClass("is-touch")&&"off"==a.settings_disableSpecialIosFeatures&&U&&U.css({overflow:"auto"});
        void 0!=c.get(0)&&(c.get(0).reinit=ga,c.get(0).scrollToTop=Ga,c.get(0).updateX=qa,c.get(0).fn_scrollx_to=Ea,c.get(0).fn_scrolly_to=Fa,c.get(0).api_toggle_resize=M);0<a.settings_refresh&&setInterval(ga,a.settings_refresh);"0"==c.find(".scrollbar").css("opacity")&&c.find(".scrollbar").animate({opacity:1},600);d(window).bind("resize",M);M();setTimeout(M,1E3);h()})();c.get(0).api_reinit=ga;"on"==a.settings_scrollbyhover||0!=c.hasClass("is-touch")&&"on"!=a.settings_disableSpecialIosFeatures||!c[0].addEventListener||
    c[0].addEventListener("DOMMouseScroll",aa,!1);c[0].onmousewheel=aa;a.secondCon&&(a.secondCon[0].addEventListener&&a.secondCon[0].addEventListener("DOMMouseScroll",aa,!1),a.secondCon[0].onmousewheel=aa);0!=c.hasClass("is-touch")&&"on"!=a.settings_disableSpecialIosFeatures||d(document).mousemove(function(b){L=b.pageX-c.offset().left;G=b.pageY-c.offset().top;"scrollTop"==a.type&&(G=b.pageY-d(window).scrollTop());"on"==a.settings_scrollbyhover&&(0>L||0>G||L>g+20||G>f+20)||(1!=x||1!=Z&&"on"!=a.settings_scrollbyhover||
    (E.addClass("dragging"),"normal"==a.settings_dragmethod&&(D=G/f*(f-H),r=G/f*(f-v)),"drag"==a.settings_dragmethod&&(D=0+(G-0)-R,r=D/-(f-H)*(v-f)),r=parseInt(r,10),C()),1!=u||1!=$&&"on"!=a.settings_scrollbyhover||(E.addClass("dragging"),"normal"==a.settings_dragmethod&&(s=L/g*(g-A),w=L/g*(g-t),null!=a.secondCon&&(B=L/F*(F-J))),"drag"==a.settings_dragmethod&&(s=0+(L-0)-ta,w=s/-(g-A)*(t-g),null!=a.secondCon&&(B=s/-(F-A)*(J-F))),C()),"on"==a.settings_fadeoutonleave&&(n.animate({opacity:1},{queue:!1,duration:500}),
        K.animate({opacity:1},{queue:!1,duration:500})))});0==c.hasClass("is-touch")||"on"==a.settings_disableSpecialIosFeatures?d(document).mouseup(function(a){$=Z=!1;E.removeClass("dragging")}):(k&&(k.bind("touchstart",ka),k.bind("touchmove",za),k.bind("touchend",V)),a.secondCon&&(a.secondCon.bind("touchstart",ka),a.secondCon.bind("touchend",V)));"on"!=a.settings_fadeoutonleave||0!=is_ios()&&"on"!=a.settings_disableSpecialIosFeatures||c.mouseleave(function(a){n.animate({opacity:0},{queue:!1,duration:500});
        K.animate({opacity:0},{queue:!1,duration:500})});c.hasClass("is-touch")&&"on"!=a.settings_disableSpecialIosFeatures&&setInterval(Ja,80);return this})};window.dzsscr_init=function(a,h){if("undefined"!=typeof h&&"undefined"!=typeof h.init_each&&1==h.init_each){var ja=0;for(e in h)ja++;1==ja&&(h=void 0);d(a).each(function(){d(this).scroller(h)})}else d(a).scroller(h)}})(jQuery);
function is_ios(){return-1!=navigator.platform.indexOf("iPhone")||-1!=navigator.platform.indexOf("iPod")||-1!=navigator.platform.indexOf("iPad")}function is_android(){console.info(navigator.platform);return-1!=navigator.platform.indexOf("Android")}function is_touch_device(){return!!("ontouchstart"in window)}function is_ie(){return-1!=navigator.appVersion.indexOf("MSIE")?!0:!1}function is_firefox(){return-1!=navigator.userAgent.indexOf("Firefox")?!0:!1}
function is_opera(){return-1!=navigator.userAgent.indexOf("Opera")?!0:!1}function is_chrome(){return/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor)}function is_safari(){return/Safari/.test(navigator.userAgent)&&/Apple Computer/.test(navigator.vendor)}function version_ie(){return parseFloat(navigator.appVersion.split("MSIE")[1])}function version_firefox(){if(/Firefox[\/\s](\d+\.\d+)/.test(navigator.userAgent))return new Number(RegExp.$1)}
function version_opera(){if(/Opera[\/\s](\d+\.\d+)/.test(navigator.userAgent))return new Number(RegExp.$1)}function is_ie8(){return is_ie()&&9>version_ie()?!0:!1}function is_ie9(){return is_ie()&&9==version_ie()?!0:!1}
function getInternetExplorerVersion(){var d=-1;if("Microsoft Internet Explorer"==navigator.appName){var a=navigator.userAgent,h=/MSIE ([0-9]{1,}[.0-9]{0,})/;null!=h.exec(a)&&(d=parseFloat(RegExp.$1))}else"Netscape"==navigator.appName&&(a=navigator.userAgent,h=/Trident\/.*rv:([0-9]{1,}[.0-9]{0,})/,null!=h.exec(a)&&(d=parseFloat(RegExp.$1)));return d}
window.requestAnimFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||function(d){window.setTimeout(d,1E3/60)}}();jQuery(document).ready(function(d){dzsscr_init(".scroller-con.auto-init",{init_each:!0})});jQuery(window).load(function(){dzsscr_init(".scroller-con.auto-init-onload",{init_each:!0})});