<?php echo Wo_LoadPage('welcome/welcome-header');?>
<div class="wrapper">
	<div class="container">
		<div class="row login forgot_pass">
			<div class="col-md-4"></div>
			<div class="col-md-4">
				<div class="sun_welcome_heading">
					<h1><?php echo $wo['lang']['reset_new_password_label']; ?></h1>
				</div>
				<form id="reset-form" class="small-padd" method="post">
					<div class="errors"></div>
					<div class="loading_cont">
						<div class="loading hidden"></div>
					</div>
					<div class="sun_input_holder">
						<div class="sun_input">
							<input name="password" type="password" id="new_password" placeholder="<?php echo $wo['lang']['new_password'];?>" autofocus/>
							<label for="new_password"><?php echo $wo['lang']['new_password']?></label>
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect><path d="M7 11V7a5 5 0 0 1 10 0v4"></path></svg>
						</div>
					</div>
					<input type="hidden" name="id" value="<?php echo $_GET['code'];?>">
					<div class="login_signup_combo">
						<div class="login__">
							<button type="submit" class="btn btn-main"><?php echo $wo['lang']['reset_password']?></button>
						</div>
						<div class="signup__">
						</div>
					</div>
				</form>
			</div>
			<div class="col-md-4"></div>
		</div>
	</div>
</div>

<div class="container"><?php echo Wo_LoadPage('footer/welcome');?></div>

<script>
var working = false;
var $this = $('#reset-form');
var $state = $this.find('.errors');
$(function() {
  $this.ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=reset_password',
    beforeSend: function() {
		working = true;
		$this.find('button').attr("disabled", true);
		$this.find('.loading').removeClass('hidden');
    },
    success: function(data) {
      if (data.status == 200 || data.status == 600) {
        $state.addClass('success');
        $state.html('<?php echo $wo['lang']['welcome_'] ?>');
		$this.find('.loading').addClass('hidden');
        setTimeout(function () {
         window.location.href = data.location;
        }, 1000);
      } else {
        $this.find('button').attr("disabled", false);
		$this.find('.loading').addClass('hidden');
        $state.html(data.errors);
      } 
      working = false;
    }
  });
});
</script>