<?php echo Wo_LoadPage('forum/headers/header'); ?>
<div role="tabpanel" class="tab-pane active list-group" id="threadreply">
		<div class="">
			<div class="blocksubhead"><i class="fa fa-thumb-tack fa-fw" aria-hidden="true"></i> 
			<i class="fa fa-angle-right" aria-hidden="true"></i> <?php echo $wo['lang']['reply']; ?>
			<i class="fa fa-angle-right" aria-hidden="true"></i> <?php echo $wo['reply']['post_subject']; ?>
			</div>
		</div>
		<div class="col-md-12" id="quotereply-alert"></div>
		<div class="col-md-12">
			<form  class="form" id="quotereply" method="post">
				<div class="form-group">
					<label for="subject" class="col-md-2"><?php echo $wo['lang']['subject']; ?>:</label>
					<div class="col-md-10">
						<div class="form-group">
							<input type="text" name="subject" class="form-control" value="<?php echo($wo['reply']['post_subject']); ?>">
							
						    <div class="clear"></div>
						</div>
					</div>
					<div class="clear"></div>
				</div>

				<div class="form-group">
					<label for="replythread" class="col-md-2"><?php echo $wo['lang']['edit']; ?>:</label>
					<div class="col-md-10">
						<textarea id="newquotereply" name="content"><?php echo(br2nlf($wo['reply']['post_text'])); ?></textarea>
					</div>
					<div class="clear"></div>
				</div>
		        <div class="form-group">
		          <label class="col-md-2"></label>
		          <div class="col-sm-10">
		             <button type="submit" class="btn btn-main">
		             
						<i class="fa fa-floppy-o" aria-hidden="true"></i> <?php echo $wo['lang']['save']; ?>
		             </button>
		          </div>
		          <div class="clear"></div>
		       </div>
              <div class="clear"></div>
			</form>
		</div>
		<div class="clear"></div>
	</div>
<?php if (isset($wo['bbcodeditor']) && $wo['bbcodeditor']): ?>
<script>
	jQuery(document).ready(function($) {


		$('#quotereply').ajaxForm({

	      url: Wo_Ajax_Requests_File()  +  '?f=editreply&rid=<?php echo $wo['reply']['id']; ?>&tid=<?php echo $wo['reply']['thread_id']; ?>&hash=' + $('.main_session').val(),
	      beforeSend: function() {
	        Wo_progressIconLoader($('#quotereply').find('button'));
	      },
	      success: function(data) {
	        scrollToTop();
	        if (data['status'] == 200) {
	        	
	         	$("#quotereply-alert").html('<div class="alert alert-success">'+ data['message'] +'</div>');
	         	window.location = data.url;
	          
	        } else {
	        	
	         	$("#quotereply-alert").html('<div class="alert alert-danger">' + data['message'] + '</div>');
	        } 
	        Wo_progressIconLoader($('#quotereply').find('button'));
	      }
		});
		$('#newquotereply').bbcode();
		$("#newquotereply").autogrow({vertical: true, horizontal: false});

	});

</script>
	
<?php endif ?>

<?php echo Wo_LoadPage('forum/headers/footer'); ?>