<?php echo Wo_LoadPage('ads/includes/header'); ?>

<div class="ads-cont-wrapper">
	<table class="table table-striped">
		<thead>
		  <tr>
		    <th>
		    	<?php echo $wo['lang']['id']; ?>
		    </th>
		    <th><?php echo $wo['lang']['company']; ?></th>
		    <th><?php echo $wo['lang']['bidding']; ?></th>
		    <th><?php echo $wo['lang']['clicks']; ?></th>
		    <th>
		    	<?php echo $wo['lang']['views']; ?>
		    </th>
		    <th><?php echo $wo['lang']['status']; ?></th>
		    <th><?php echo $wo['lang']['action']; ?></th>
		  </tr>
		</thead>
		<tbody id="user-ads">
		<?php if (count($wo['ads']) > 0): ?>
		  <?php foreach ($wo['ads'] as $wo['ad']): ?>
		  	<?php echo Wo_LoadPage('ads/includes/ads-list');?>
		  <?php endforeach; ?>
		<?php else: ?>
			<tr>
				<td colspan="7" class="text-center" style="height: 200px;">
					<?php echo $wo['lang']['no_ads_found']; ?>
				</td>
			</tr>
		<?php endif; ?>
		</tbody>
	</table>
</div>

<div class="col-md-12 col-lg-12 col-sm-12 col-sx-12">
 	<div class="posts_load">
	    <?php if (count($wo['ads']) > 0): ?>
		<div class="load-more">
            <button class="btn btn-default text-center pointer load-more-ads">
            <svg xmlns="http://www.w3.org/2000/svg" width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather"><polyline points="6 9 12 15 18 9"></polyline></svg>
            <?php echo $wo['lang']['load_more'] ?>
            </button>
        </div>
        <?php endif ?>
	</div>
</div>

<div class="modal fade" id="delete-ad" >
   <div class="modal-dialog modal-sm">
      <div class="modal-content">
         <div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
            <h4 class="modal-title"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg> <?php echo $wo['lang']['delete_ad']; ?></h4>
         </div>
         <div class="modal-body">
            <p><?php echo $wo['lang']['confirm_delete_ad']; ?></p>
         </div>
         <div class="modal-footer">
            <button  type="button" onclick="Wo_DeleteAd($('#delete-ad').attr('data-userad-id'))" class="btn  btn-main"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path></svg> <?php echo $wo['lang']['delete']; ?></button>
         </div>
      </div>
   </div>
</div>

<script>
	
	jQuery(document).ready(function($) {
		$(document).on('click', '.delete-ad', function(event) {
			var self = $(this);	
			$("#delete-ad").attr('data-userad-id',self.attr('id')).modal("show");

		});

		$(document).on('click', '.toggle-user-ad-status', function(event) {
			var self      = $(this);
			var ad_id     = self.attr('id');
			var ad_status = self.attr('data-status');
			$.ajax({
				url: Wo_Ajax_Requests_File(),
				type: 'GET',
				dataType: 'json',
				data: {f: 'ads',s:'ts',ad_id:ad_id,status:ad_status},
			})
			.done(function(data) {
				if (data.status == 200) {
					$("[data-ad-status='"+ad_id+"']").find('span').text(data.ad);
					if (ad_status == 0) {
						self.html('<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-check-circle"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path><polyline points="22 4 12 14.01 9 11.01"></polyline></svg>');
						self.attr('data-status',1);
					}
					else{
						self.html('<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-circle"><circle cx="12" cy="12" r="10"></circle></svg>');
						self.attr('data-status',0);
					}
				}
			})
			.fail(function() {
				console.log("error");
			})
		
		});

		$(".load-more-ads").click(function(event) {
			var last_ad = ($("tr[data-ad-id]").length > 0) ? $("tr[data-ad-id]").last().attr('data-ad-id') : 0;
			var self    = $(this);
			$.ajax({
				url: Wo_Ajax_Requests_File(),
				type: 'GET',
				dataType: 'json',
				data: {f: 'ads',s:'lm',ad_id:last_ad},
			})
			.done(function(data) {
				if (data.status == 200) {
					$("#user-ads").append(data.html);
				}
				else if(data.status == 404){
					self.removeClass('load-more-ads').html(data.html);
				}
				else{
					self.remove();
				}
			})
			.fail(function() {
				console.log("error");
			})
			
		});
	});

	function Wo_DeleteAd(id){
		if (id && id > 0) {
			$.ajax({
				url: Wo_Ajax_Requests_File(),
				type: 'GET',
				dataType: 'json',
				data: {f: 'wallet',s:'remove',id:id},
			})
			.done(function(data) {
				if (data.status == 200) {
					$("tr[data-ad-id="+id+"]").slideUp(function(){
						$(this).remove();
					})
					$("#delete-ad").modal("hide");
				}
			})
			.fail(function() {
				console.log("error");
			})
		}
	}
</script>