<section class="bg-purple">
	<div class="stars">
		<div class="central-body-prnt">
			<div class="central-body">
                <img class="image-404" src="<?php echo $wo['config']['theme_url'];?>/img/404/404.svg" width="300px">
				<p><?php echo $wo['lang']['page_not_found']; ?></p>
				<div>
					<a href="<?php echo $wo['config']['site_url']; ?>" class="btn btn-lg btn-main btn-go-home"><?php echo $wo['lang']['home']; ?></a>
				</div>
			</div>
		</div>
		<div class="objects">
			<img class="object_rocket" src="<?php echo $wo['config']['theme_url'];?>/img/404/rocket.svg" width="40px">
			<div class="earth-moon">
				<img class="object_earth" src="<?php echo $wo['config']['theme_url'];?>/img/404/earth.svg" width="100px">
				<img class="object_moon" src="<?php echo $wo['config']['theme_url'];?>/img/404/moon.svg" width="80px">
			</div>
			<div class="box_astronaut">
				<img class="object_astronaut" src="<?php echo $wo['config']['theme_url'];?>/img/404/astronaut.svg" width="140px">
			</div>
		</div>
		<div class="glowing_stars">
			<div class="star"></div><div class="star"></div><div class="star"></div><div class="star"></div><div class="star"></div>
		</div>
	</div>
</section>

<style>
@-webkit-keyframes rocket-movement {100% {-webkit-transform: translate(1200px,-600px); } }
@keyframes rocket-movement { 100% {transform: translate(1200px,-600px);} }
@-webkit-keyframes spin-earth { 100% { -webkit-transform: rotate(-360deg); transition: transform 20s;  } }
@keyframes spin-earth{ 100% { -webkit-transform: rotate(-360deg); transform:rotate(-360deg); transition: transform 20s; } }

@-webkit-keyframes move-astronaut {100% { -webkit-transform: translate(-160px, -160px);}}
@keyframes move-astronaut{100% { -webkit-transform: translate(-160px, -160px); transform:translate(-160px, -160px); }}
@-webkit-keyframes rotate-astronaut {100% { -webkit-transform: rotate(-720deg);}}
@keyframes rotate-astronaut{100% { -webkit-transform: rotate(-720deg); transform:rotate(-720deg); }}

@-moz-keyframes glow-star {40% { -moz-opacity: 0.3;}90%,100% { -moz-opacity: 1; -moz-transform: scale(1.2);}}
@-webkit-keyframes glow-star {40% { -webkit-opacity: 0.3;}90%,100% { -webkit-opacity: 1; -webkit-transform: scale(1.2);}}
@keyframes glow-star{40% { -webkit-opacity: 0.3; opacity: 0.3;  }90%,100% { -webkit-opacity: 1; opacity: 1; -webkit-transform: scale(1.2); transform: scale(1.2); border-radius: 999999px;}}
.bg-purple{min-height: calc(100vh - 45px);overflow: hidden;background: radial-gradient(at bottom center, #583469, #3f3162);}
.btn-go-home {z-index: 200;margin: 25px auto 0;min-width: 110px;border-radius: 2em;font-weight: 600;letter-spacing: 1px;font-size: 14px;}
.central-body-prnt {display: -webkit-box;display: -moz-box;display: -ms-flexbox;display: -webkit-flex;display: flex;-webkit-flex-direction: column;flex-direction: column;min-height: calc(100vh - 45px);position: relative;}
.central-body-prnt:after, .central-body-prnt:before {-webkit-box-flex: 1;box-flex: 1;-webkit-flex-grow: 1;flex-grow: 1;content: '';display: block;height: 24px;}
.central-body {width: 100%;max-width: 350px;text-align: center;margin: auto;font-family: "Lato", sans-serif;}
.central-body p {color: #fff;margin-top: -50px;font-size: 16px;}
.objects img{z-index: 90;pointer-events: none;}
.object_rocket{z-index: 95;position: absolute;transform: translateX(-50px);top: 75%;pointer-events: none;animation: rocket-movement 200s linear infinite both running;}
.object_earth{position: absolute;top: 20%;left: 15%;z-index: 90;animation: spin-earth 100s infinite linear both;}
.object_moon{position: absolute;top: 12%;left: 25%;}
.object_astronaut{animation: rotate-astronaut 200s infinite linear both alternate;}
.box_astronaut{z-index: 110 !important;position: absolute;top: 60%;right: 20%;will-change: transform;animation: move-astronaut 50s infinite linear both alternate;}
.image-404{position: relative;z-index: 100;pointer-events: none;}
.stars{background: url(<?php echo $wo['config']['theme_url'];?>/img/404/overlay_stars.svg);background-repeat: repeat;background-size: contain;background-position: left top;height: 100%;}
.glowing_stars .star {position: absolute;border-radius: 100%;background-color: #fff;width: 3px;height: 3px;opacity: 0.3;will-change: opacity;}
.glowing_stars .star:nth-child(1) {top: 80%;left: 25%;animation: glow-star 2s infinite ease-in-out alternate 1s;}
.glowing_stars .star:nth-child(2) {top: 20%;left: 40%;animation: glow-star 2s infinite ease-in-out alternate 3s;}
.glowing_stars .star:nth-child(3) {top: 25%;left: 25%;animation: glow-star 2s infinite ease-in-out alternate 5s;}
.glowing_stars .star:nth-child(4) {top: 75%;left: 80%;animation: glow-star 2s infinite ease-in-out alternate 7s;}
.glowing_stars .star:nth-child(5) {top: 90%;left: 50%;animation: glow-star 2s infinite ease-in-out alternate 9s;}

@media only screen and (max-width: 600px){
.box_astronaut{top: 70%;}
}
</style>