<?php echo Wo_LoadPage('forum/headers/header'); ?>
<div class="row">
	<label class="col-md-2"></label>
	<div class="col-md-8">
		<div class="red-list">
			<div class="wo_settings_page">
				<h3><?php echo $wo['lang']['reply']; ?></h3>
				<form action="#" class="form" id="newtopicreply" method="post">
					<div class="setting-panel row">
						<div class="sun_input">
							<textarea id="replythread" name="content" placeholder="<?php echo $wo['lang']['your_reply']?>"></textarea>
							<label for="replythread"><?php echo $wo['lang']['your_reply']?></label>
						</div>
						<!-- Text input-->
						<div class="sun_input">
							<input type="text" class="form-control" name="subject" id="subject" placeholder="<?php echo $wo['lang']['subject']?>" value="<?php echo $wo['thread']['headline']; ?>">
							<label for="subject"><?php echo $wo['lang']['subject']?></label>
						</div>
					</div>
					<div id="newtopicreply-alert"></div>
					<div class="form-group last-sett-btn modal-footer">
						<div class="ball-pulse"><div></div><div></div><div></div></div>
						<button type="submit" class="btn btn-main setting-panel-mdbtn"><?php echo $wo['lang']['reply'];?></button>
					</div>
				</form>
			</div>
		</div>
	</div>
	<!-- .col-md-8 -->
	<label class="col-md-2"></label>
</div>
<?php if (isset($wo['bbcodeditor']) && $wo['bbcodeditor']): ?>

<script>
	jQuery(document).ready(function($) {
		$('#newtopicreply').ajaxForm({
	      url: Wo_Ajax_Requests_File()  +  '?f=threadreply&tid=<?php echo $wo['thread']['id']; ?>&fid=<?php echo $wo['thread']['forum']; ?>&q=0&hash=' + $('.main_session').val(),
	      dataType:'json',
	      beforeSend: function() {
	        Wo_progressIconLoader($('#newtopicreply').find('button'));
	      },
	      success: function(data) {
	        scrollToTop();
	        if (data['status'] == 200) {
	         	$("#newtopicreply-alert").html('<div class="alert alert-success">'+ data['message'] +'</div>');
	         	window.location = data.url;
	          
	        } else {
	         	$("#newtopicreply-alert").html('<div class="alert alert-danger">' + data['message'] + '</div>');
	        } 
	        Wo_progressIconLoader($('#newtopicreply').find('button'));
	      }
		});
		$('#replythread').bbcode();
		$("#replythread").autogrow({vertical: true, horizontal: false});
	});
</script>
	
<?php endif ?>

<?php echo Wo_LoadPage('forum/headers/footer'); ?>