<div class="blog-comment-item" data-blog-comment="<?php echo $wo['comment']['id']; ?>">
	<div>
		<div class="col-md-1 col-sm-1 col-xs-1 <?php echo Wo_RightToLeft('pull-left');?> blog-comment-item-img">
			<img src="<?php echo $wo['comment']['user_data']['avatar']; ?>" alt="" class="responsive-img img-circle">
		</div>
		<div class="col-md-11 <?php echo Wo_RightToLeft('pull-right');?> col-sm-10 col-xs-10 blog-comment-item-body">
			<h5>
				<a class="pointer bold" data-ajax="?link1=timeline&u=<?php echo $wo['comment']['user_data']['username']; ?>" href="<?php echo $wo['comment']['user_data']['url']; ?>">
					<?php echo $wo['comment']['user_data']['name']; ?>
				</a>
				<span class="time">
					<span class="ajax-time" title="<?php echo date('c',$wo['comment']['posted']); ?>">
						<?php echo Wo_Time_Elapsed_String($wo['comment']['posted']); ?>
					</span>
				</span>
				<?php if ($wo['comment']['is_owner']): ?>
					<span class="pointer <?php echo Wo_RightToLeft('pull-right');?> del-blog-comment" id="<?php echo $wo['comment']['id']; ?>">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg>
					</span>
				<?php endif ?>
			</h5>
			<p><?php echo $wo['comment']['text']; ?></p>
			<div>
				<span class="comment-icons">
					<span class="pointer reply-toblog-comm"  id="<?php echo $wo['comment']['id']; ?>">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-message-circle"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"></path></svg>
					</span>
					&nbsp;
					<span class="pointer add-blog-commlikes-<?php echo $wo['comment']['id']; ?>" onclick="Wo_AddBlogCommentLike(<?php echo $wo['comment']['id']; ?>)">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-thumbs-up"><path d="M14 9V5a3 3 0 0 0-3-3l-4 9v11h11.28a2 2 0 0 0 2-1.7l1.38-9a2 2 0 0 0-2-2.3zM7 22H4a2 2 0 0 1-2-2v-7a2 2 0 0 1 2-2h3"></path></svg>
					</span> 
					<span id="blog-comment-likes" data-blog-comlikes="<?php echo $wo['comment']['id']; ?>">
						<?php if ($wo['comment']['likes'] > 0): ?>
							<?php echo $wo['comment']['likes']; ?>
						<?php endif; ?>
					</span>
					<?php if ($wo['config']['second_post_button'] != 'disabled') { ?>
					&nbsp;
					<span class="pointer add-blog-commdislikes-<?php echo $wo['comment']['id']; ?>" onclick="Wo_AddBlogCommentDisLike(<?php echo $wo['comment']['id']; ?>)">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-thumbs-down"><path d="M10 15v4a3 3 0 0 0 3 3l4-9V2H5.72a2 2 0 0 0-2 1.7l-1.38 9a2 2 0 0 0 2 2.3zm7-13h2.67A2.31 2.31 0 0 1 22 4v7a2.31 2.31 0 0 1-2.33 2H17"></path></svg>
					</span>
					<span id="blog-comment-likes" data-blog-comdislikes="<?php echo $wo['comment']['id']; ?>">
						<?php if ($wo['comment']['dislikes'] > 0): ?>
							<?php echo $wo['comment']['dislikes']; ?>
						<?php endif; ?>
					</span>
					<?php } ?>
				</span>
				&nbsp;
				<?php if (count($wo['comment']['replies']) > 5): ?>
					<span class="pointer"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevrons-down" style="margin-top: 0px;width: 18px;height: 18px;"><polyline points="7 13 12 18 17 13"></polyline><polyline points="7 6 12 11 17 6"></polyline></svg></span>
				<?php endif; ?>
			</div>
		</div>
		<div class="clear"></div>
	</div>
	<div class="blog-comment-reply-cont">
		<?php 
  		foreach ($wo['comment']['replies'] as $wo['comm-reply']) {
  			echo Wo_LoadPage('blog/commreplies-list');
  		}
		?>
	</div>
	<div class="blog-comment-reply-box col-md-11 col-sm-11 col-xs-11 <?php echo Wo_RightToLeft('pull-right');?> hidden">
		<form class="form">
			<div class="form-group">
				<textarea  class="form-control blog-comment-reply" onkeydown="Wo_RegisterBlogCommReply(<?php echo $wo['comment']['id']; ?>,event,this)"  placeholder="<?php echo $wo['lang']['write_comment'];?>" type="text"></textarea>
			</div>
		</form>
	</div>
</div>