<div class="wo_about_wrapper_parent">
	<div class="wo_about_wrapper"> 
		<div class="hero hero-overlay"> 
			<div class="container">
				<h1 class="text-center"> 
					<?php echo $wo['lang']['about'];?> <?php echo $wo['config']['siteName'];?> <br> 
					<small class="site_desc text-center"><?php echo $wo['description'];?></small> 
				</h1>
			</div> 
		</div> 
		<div class="full-width-picture" style="background-image: url(<?php echo $wo['config']['theme_url'];?>/img/about-us.jpg);"></div> 
	</div>
</div>

<div class="page-margin wo_about_page_margin">
   <div class="sun_about_page">
      <div class="list-group-item hidden">About Us</div>
      <div class="setting-well">
        <?php echo $wo['terms']['about'];?>
      </div>
   </div>
</div>