<div class="wo_settings_page">
	<h3>
		<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-mail"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg>
		<?php echo $wo['lang']['email_notification']; ?> 
	</h3>

	<form class="setting-general-form form-horizontal" method="post">
		<div class="setting-general-alert setting-update-alert"></div>
		
		<div class="setting-panel row">
			<!-- Multiple Radios (inline) -->
         	<div class="col-md-3"><h5 class="bold"><?php echo $wo['lang']['email_me_when']; ?></h5></div>
         	<div class="col-lg-9">
				<!-- Multiple Radios (inline) -->
				<div class="form-group">
					<?php 
						$selected_e_liked   = ($wo['setting']['e_liked'] == 1)   ? ' checked' : '';
					?>
					<div class="col-md-12 round-check">
						<input type="checkbox" name="e_liked" id="e_liked" value="1" <?php echo $selected_e_liked; ?>>
						<label for="e_liked"><?php echo $wo['lang']['e_likes_my_posts']; ?></label>
					</div>
				</div>
				<!-- Multiple Radios (inline) -->
				<?php if ($wo['config']['second_post_button'] != 'disabled') { ?>
				<div class="form-group">
					<?php 
						$selected_e_wondered   = ($wo['setting']['e_wondered'] == 1)   ? ' checked' : '';
					?>
					<div class="col-md-12 round-check">
						<input type="checkbox" name="e_wondered" id="e_wondered" value="1" <?php echo $selected_e_wondered; ?>>
						<label for="e_wondered"><?php echo ($wo['config']['second_post_button'] == 'wonder') ? $wo['lang']['e_wondered_my_posts'] : $wo['lang']['e_disliked_my_posts']; ?></label>
					</div>
				</div>
				<?php } ?>
				<!-- Multiple Radios (inline) -->
				<div class="form-group">
					<?php 
						$selected_e_commented   = ($wo['setting']['e_commented'] == 1)   ? ' checked' : '';
					?>
					<div class="col-md-12 round-check">
						<input type="checkbox" name="e_commented" id="e_commented" value="1" <?php echo $selected_e_commented; ?>> 
						<label for="e_commented"><?php echo $wo['lang']['e_commented_my_posts']; ?></label>
					</div>
				</div>
				<!-- Multiple Radios (inline) -->
				<div class="form-group">
					<?php 
						$selected_e_shared = ($wo['setting']['e_shared'] == 1)   ? ' checked' : '';
					?>
					<div class="col-md-12 round-check">
						<input type="checkbox" name="e_shared" id="e_shared" value="1" <?php echo $selected_e_shared; ?>> 
						<label for="e_shared"><?php echo $wo['lang']['e_shared_my_posts']; ?></label>
					</div>
				</div>
				<!-- Multiple Radios (inline) -->
				<div class="form-group">
					<?php 
						$selected_e_followed = ($wo['setting']['e_followed'] == 1)   ? ' checked' : '';
					?>
					<div class="col-md-12 round-check">
						<input type="checkbox" name="e_followed" id="e_followed" value="1" <?php echo $selected_e_followed; ?>>  
						<label for="e_followed"><?php echo $wo['lang']['e_followed_me']; ?></label>
					</div>
				</div>
				<!-- Multiple Radios (inline) -->
				<div class="form-group">
					<?php 
						$selected_e_liked_page = ($wo['setting']['e_liked_page'] == 1)   ? ' checked' : '';
					?>
					<div class="col-md-12 round-check">
						<input type="checkbox" name="e_liked_page" id="e_liked_page" value="1" <?php echo $selected_e_liked_page; ?>>  
						<label for="e_liked_page"><?php echo $wo['lang']['e_liked_page']; ?></label>
					</div>
				</div>
				<!-- Multiple Radios (inline) -->
				<div class="form-group">
					<?php 
						$selected_e_visited = ($wo['setting']['e_visited'] == 1)   ? ' checked' : '';
					?>
					<div class="col-md-12 round-check">
						<input type="checkbox" name="e_visited" id="e_visited" value="1" <?php echo $selected_e_visited; ?>>  
						<label for="e_visited"><?php echo $wo['lang']['e_visited_my_profile']; ?></label>
					</div>
				</div>
				<!-- Multiple Radios (inline) -->
				<div class="form-group">
					<?php 
						$selected_e_mentioned = ($wo['setting']['e_mentioned'] == 1)   ? ' checked' : '';
					?>
					<div class="col-md-12 round-check">
						<input type="checkbox" name="e_mentioned" id="e_mentioned" value="1" <?php echo $selected_e_mentioned; ?>>  
						<label for="e_mentioned"><?php echo $wo['lang']['e_mentioned_me']; ?></label>
					</div>
				</div>
				<!-- Multiple Radios (inline) -->
				<div class="form-group">
					<?php 
						$selected_e_joined_group = ($wo['setting']['e_joined_group'] == 1)   ? ' checked' : '';
					?>
					<div class="col-md-12 round-check">
						<input type="checkbox" name="e_joined_group" id="e_joined_group" value="1" <?php echo $selected_e_joined_group; ?>>  
						<label for="e_joined_group"><?php echo $wo['lang']['e_joined_group']; ?></label>
					</div>
				</div>
				<!-- Multiple Radios (inline) -->
				<div class="form-group">
					<?php 
						$selected_e_accepted = ($wo['setting']['e_accepted'] == 1)   ? ' checked' : '';
					?>
					<div class="col-md-12 round-check">
						<input type="checkbox" name="e_accepted" id="e_accepted" value="1" <?php echo $selected_e_accepted; ?>> 
						<label for="e_accepted"><?php echo $wo['lang']['e_accepted']; ?></label>
					</div>
				</div>
				<!-- Multiple Radios (inline) -->
				<div class="form-group">
					<?php 
						$selected_e_profile_wall_post = ($wo['setting']['e_profile_wall_post'] == 1)   ? ' checked' : '';
					?>
					<div class="col-md-12 round-check">
						<input type="checkbox" name="e_profile_wall_post" id="e_profile_wall_post" value="1" <?php echo $selected_e_profile_wall_post; ?>> 
						<label for="e_profile_wall_post"><?php echo $wo['lang']['e_profile_wall_post']; ?></label>
					</div>
				</div>
				<!-- Multiple Radios (inline) -->
				<div class="form-group">
					<?php 
						$selected_e_sentme_msg = ($wo['setting']['e_sentme_msg'] == 1)   ? ' checked' : '';
					?>
					<div class="col-md-12 round-check">
						<input type="checkbox" name="e_sentme_msg" id="e_sentme_msg" value="1" <?php echo $selected_e_sentme_msg; ?>>
						<label for="e_sentme_msg"><?php echo $wo['lang']['e_sent_msg']; ?></label>
					</div>
				</div>
			</div>
         </div>
		 <div class="form-group last-sett-btn modal-footer">
			<div class="ball-pulse"><div></div><div></div><div></div></div>
			<button type="submit" class="btn btn-main setting-panel-mdbtn">
               <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-check-circle"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path><polyline points="22 4 12 14.01 9 11.01"></polyline></svg> 
			   <?php echo $wo['lang']['save']; ?>
			</button>
         </div>
         <input type="hidden" name="user_id" value="<?php echo $wo['setting']['user_id'];?>">
         <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
   </form>
</div>
<script type="text/javascript">
$(function() {
  $('form.setting-general-form').ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=update_email_settings',
    beforeSend: function() {
      $('.wo_settings_page').find('.last-sett-btn .ball-pulse').fadeIn(100);
    },
    success: function(data) {
      scrollToTop();
      if (data.status == 200) {
        $('.setting-general-alert').html('<div class="alert alert-success">' + data.message + '</div>');
        $('.alert-success').fadeIn('fast', function() {
           $(this).delay(2500).slideUp(500, function() {
              $(this).remove();
            });
        });
      } 
      $('.wo_settings_page').find('.last-sett-btn .ball-pulse').fadeOut(100);
    }
  });
});
</script>