<div class="wo_settings_page">
	<h3><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg> <?php echo $wo['lang']['manage_sessions'] ?></h3>
	<br>
	<div class="active_sessions">
		<div class="table-responsive">
					<?php
						$get_sessions = Wo_GetAllSessionsFromUserID($wo['setting']['user_id']);
						if (count($get_sessions) > 0) {
							foreach ($get_sessions as $wo['key'] => $wo['session']) {
							     echo Wo_LoadPage('setting/includes/sessions');
							}
						}
					?>
		</div>
	</div>
</div>
<script type="text/javascript">
function logOutSession(id) {
	if (!confirm('Are you sure you want to log out from this device?')) {
		return false;
	}
	$('#session_' + id).remove();
	$.post(Wo_Ajax_Requests_File() + '?f=delete_s', {id: id}, function () {
		Wo_IsLogged();
	});
}
</script>