<?php 
$wo['trans'] = Wo_GetMytransactions();
?>
<div class="wo_settings_page">
	<h3>
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-activity"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"></polyline></svg>
		<?php echo $wo['lang']['transaction_log']; ?>
	</h3>
        <div class="row">
            <div class="tabbable">
                <?php echo Wo_LoadPage('setting/includes/latest_activities');?>
            </div>
        </div>
</div>