<div class="modal fade matdialog" id="calling-modal" role="dialog" data-backdrop="static" data-keyboard="false">
   <div class="modal-dialog modal-sm">
      <div class="modal-content">
         <div class="modal-header">
            <h4 class="modal-title"><i class="zmdi zmdi-phone"></i> <?php echo $wo['lang']['calling'];?> <?php echo $wo['calling_user']['name'];?> ..</h4>
         </div>
         <div class="modal-body">
            <p><?php echo $wo['lang']['calling_desc'];?></p>
         </div>
         <div class="modal-footer">
            <button type="button" class="matbtn wabe btn btn-default cancel-call" onclick="Wo_CancelCall();"><i class="fa fa-times progress-icon" data-icon="times"></i> <?php echo $wo['lang']['cancel'];?></button>
         </div>
      </div>
   </div>
</div>