<div class="modal fade" id="create-password" role="dialog">
   <div class="modal-dialog" id="modal-dialog-update-info">
      <div class="modal-content">
         <form action="#" method="post" class="create-password">
            <div class="modal-header">
               <h4 class="modal-title"><i class="fa fa-cog"></i> <?php echo $wo['lang']['update_your_info'];?></h4>
            </div>
            <div class="modal-body">
               <div class="error-container">
               </div>
               <div class="form-group">
                  <label for="username"><?php echo $wo['lang']['choose_your_username'];?></label>
                  <input id="username" name="username" type="text" placeholder="<?php echo $wo['lang']['username'];?>" class="form-control input-md" onkeyup="Wo_CheckUsername(this.value);" autocomplete="off">
                  <span class="help-block checking"></span> 
               </div>
               <!-- Password input-->
               <div class="form-group">
                  <label for="new_password"><?php echo $wo['lang']['create_your_new_password'];?></label>
                  <input id="new_password" name="new_password" type="password" placeholder="<?php echo $wo['lang']['password'];?>" class="form-control input-md">
               </div>
               <!-- Password input-->
               <div class="form-group">
                  <input id="repeat_new_password" name="repeat_new_password" type="password" placeholder="<?php echo $wo['lang']['confirm_password'];?>" class="form-control input-md">
               </div>
               <input type="hidden" name="user_id" value="<?php echo $wo['user']['user_id']?>">
               <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
            </div>
            <div class="modal-footer">
               <button id="create-password-button" type="submit" class="btn  btn-main"><i class="fa fa-pencil progress-icon" data-icon="pencil"></i> <?php echo $wo['lang']['update'];?></button>
            </div>
         </form>
      </div>
   </div>
</div>