<div class="modal fade" id="keyboard_shortcuts_box" role="dialog">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></button>
				<h4 class="modal-title"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-command"><path d="M18 3a3 3 0 0 0-3 3v12a3 3 0 0 0 3 3 3 3 0 0 0 3-3 3 3 0 0 0-3-3H6a3 3 0 0 0-3 3 3 3 0 0 0 3 3 3 3 0 0 0 3-3V6a3 3 0 0 0-3-3 3 3 0 0 0-3 3 3 3 0 0 0 3 3h12a3 3 0 0 0 3-3 3 3 0 0 0-3-3z"></path></svg> <?php echo $wo['lang']['keyboard_shortcuts'];?></h4>
			</div>
			<div class="modal-body">
				<table class="key_shortcts">
					<tbody>
						<tr>
							<th><span>J</span></th>
							<td><?php echo $wo['lang']['keyboard_shortcut_j']; ?></td>
						</tr>
						<tr>
							<th><span>K</span></th>
							<td><?php echo $wo['lang']['keyboard_shortcut_k']; ?></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>