<div class="page-margin">
	<div class="row">
		<div class="col-lg-12" style="padding: 0;">
			<iframe src="https://www.miniclip.com/games/<?php echo $wo['game']['game_link'];?>/en/webgame.php" frameborder="0" style="border:none;" width="100%" height="560"></iframe>
			
		</div>
	</div>
</div>
<style>
  body {
    padding-left: 0px;
}
.navbar-default {
    padding-right: 0px;
}
@media (min-width: 1200px){
body {
    padding-left: 0px;
    padding-right: 205px;
}
.navbar-default {
    padding-right: 205px;
}
}
@media (max-width: 990px) {
body {
    padding-left: 0px;
    overflow-x: auto;
}
}
</style>