<div class="container-fluid">
    <div class="block-header">
        <h2>Tools > Auto Delete Data</h2>
    </div>
    <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="header">
                    <h2>Auto Delete Data</h2> 
                    <br>
                    <small>It's recommended to create a backup before applying any actions.</small>
                </div>
                <div class="body">
                   <label for="delete">Select what you want to delete</label>
                        <select class="form-control show-tick" id="delete" name="delete">
                           <option value="1">Delete all inactive users</option>
                           <option value="2">Delete users that are not logged in more than 1 week</option>
                           <option value="3">Delete users that are not logged in more than 1 month</option>
                           <option value="4">Delete users that are not logged in more than 1 year</option>
                           <option value="5">Delete posts that are longer than 1 week</option>
                           <option value="6">Delete posts that are longer than 1 month</option>
                           <option value="7">Delete posts that are longer than 1 year</option>
                        </select>
                        <div class="clearfix"></div><br>
                        <small>This process might take some time, you can check for your site changes after few minutes.</small><br>
                  <button type="submit" class="btn btn-danger waves-effect waves-light m-t-20" id="delete-btn">Delete Data</button>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    </div>
<script>
$(document).on('click', '#delete-btn', function(event) {
	event.preventDefault();
	if (!confirm('Are you sure you want to delete? this action can\'t be undo')) {
		return false;
	}
	$(this).text('Please wait..');
	$.get(Wo_Ajax_Requests_File(), {f:'admin_setting', s: 'auto_delete', delete: $('#delete').val()}, function(data, textStatus, xhr) {
		$('#delete-btn').text('Data is being deleted, check your site after few mins.');
		setTimeout(function () {
			$('#delete-btn').text('Delete Data');
		}, 4000);
	});
});
</script>