<?php 
$not_found = '<h5 class="search-filter-center-text empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-info"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="16" x2="12" y2="12"></line><line x1="12" y1="8" x2="12" y2="8"></line></svg> ' . $wo["lang"]["no_result"] . '</h5>';
$type_to_find = '<h5 class="search-filter-center-text empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg> ' . $wo["lang"]["what_are_looking_for"] . '</h5>';
?>
<div class="page-margin">
   <div class="row">
      <div class="col-md-8">
         <div class="wo_search_page">
            <div class="setting-well">
               <ul class="nav nav-tabs searchtoptabs">
                  <li class="active"><a data-toggle="tab" data-target="#users" href="#"><i class="zmdi zmdi-accounts-alt zmdi-hc-fw" style="font-size: 18px;margin-top: -2px;"></i> <span class="button-text"><?php echo $wo['lang']['users'];?></span></a></li>
                  <?php if ($wo['config']['pages'] == 1) { ?><li><a data-toggle="tab" data-target="#pages" href="#"><i class="zmdi zmdi-flag zmdi-hc-fw" style="font-size: 18px;margin-top: -2px;"></i> <span class="button-text"><?php echo $wo['lang']['pages'];?></span></a></li><?php } ?>
                  <?php if ($wo['config']['groups'] == 1) { ?><li><a data-toggle="tab" data-target="#groups" href="#"><i class="zmdi zmdi-group-work zmdi-hc-fw" style="font-size: 18px;margin-top: -2px;"></i> <span class="button-text"><?php echo $wo['lang']['groups'];?></span></a></li><?php } ?>
                  <?php if ($wo['config']['games'] == 1) { ?><li><a data-toggle="tab" data-target="#games" href="#"><i class="zmdi zmdi-gamepad zmdi-hc-fw" style="font-size: 18px;margin-top: -2px;"></i> <span class="button-text"><?php echo $wo['lang']['games'];?></span></a></li><?php } ?>
               </ul>
               <div class="tab-content">
                  <div id="users" class="tab-pane fade in active">
                  <div id="users-cont">

                     <?php
                     if (!isset($_GET['query'])) {
                        echo $type_to_find;
                     }
                     if (isset($_GET['query'])) {
                        $search_query = Wo_GetSearchFilter($_GET, 30);
                          if (count($search_query) != 0) {
                              foreach ($search_query as $wo['result']) {
                                  echo Wo_LoadPage('search/result');
                              }
                          } else {
                              echo $not_found;
                          }
                      }
                     ?>
                    </div>
                    <div class="clear"></div>
                    <br>
                    <div class="load-more">
                        <button class="mdbtn wabe btn btn-default text-center pointer load-more-users">
                          <i class="fa fa-arrow-down progress-icon" data-icon="arrow-down"></i> 
                          <?php echo $wo['lang']['load_more_users'] ?>
                        </button>
                    </div>
                  </div>
                  <?php if ($wo['config']['pages'] == 1) { ?>
                  <div id="pages" class="tab-pane fade">
                    <div id="pages-cont">
                     <?php
                     if (!isset($_GET['query'])) {
                        echo $type_to_find;
                     }
                     if (isset($_GET['query'])) {
                        $search_query = Wo_GetSearchAdv($_GET['query'], 'pages');
                          if (count($search_query) != 0) {
                              foreach ($search_query as $wo['result']) {
                                  echo Wo_LoadPage('search/result');
                              }
                          } else {
                              echo $not_found;
                          }
                      }
                     ?>
                    </div>
                    <div class="clear"></div>
                    <br>
                    <div class="load-more">
                        <button class="mdbtn wabe btn btn-default text-center pointer load-more-pages">
                          <i class="fa fa-arrow-down progress-icon" data-icon="arrow-down"></i> 
                          <?php echo $wo['lang']['load_more_pages'] ?>
                        </button>
                    </div>
                  </div>
                  <?php } ?>
                  <?php if ($wo['config']['groups'] == 1) { ?>
                  <div id="groups" class="tab-pane fade">
                    <div id="groups-cont">
                     <?php
                     if (!isset($_GET['query'])) {
                        echo $type_to_find;
                     }
                     if (isset($_GET['query'])) {
                        $search_query = Wo_GetSearchAdv($_GET['query'], 'groups');
                          if (count($search_query) != 0) {
                              foreach ($search_query as $wo['result']) {
                                  echo Wo_LoadPage('search/result');
                              }
                          } else {
                              echo $not_found;
                          }
                      }
                     ?>
                    </div>
                    <div class="clear"></div>
                    <br> 
                    <div class="load-more">
                        <button class="mdbtn wabe btn btn-default text-center pointer load-more-groups">
                          <i class="fa fa-arrow-down progress-icon" data-icon="arrow-down"></i> 
                          <?php echo $wo['lang']['load_more_groups'] ?>
                        </button>
                    </div>
                  </div>
                  <?php } ?>
                  <?php if ($wo['config']['groups'] == 1) { ?>
                  <div id="games" class="tab-pane fade">
                     <?php
                     if (!isset($_GET['query'])) {
                        echo $type_to_find;
                     }
                     if (isset($_GET['query'])) {
                        $search_query = Wo_GetSearchAdv($_GET['query'], 'games');
                          if (count($search_query) != 0) {
                              foreach ($search_query as $wo['game']) {
                                  echo Wo_LoadPage('games/game-list');
                              }
                          } else {
                              echo $not_found;
                          }
                      }
                     ?>

                  </div>
                  <?php } ?>
               </div>
            </div>
            <div class="clear"></div>
         </div>
      </div>
      <div class="col-md-4 cussidefix">
        <div class="wo_settings_page">
            <h3><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-filter"><polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3"></polygon></svg> <?php echo $wo['lang']['search_filter'];?></h3>
         <form action="<?php echo Wo_SeoLink('index.php?link1=search') ?>" method="get" class="search-filter-form">
		 <div class="setting-panel row">
            <div class="col-lg-12 pp_mat_input">
               <input type="text" name="query" id="query" class="form-control" placeholder="<?php echo $wo['lang']['keyword'];?>" value="<?php echo (isset($_GET['query'])) ? Wo_Secure($_GET['query']): '';?>" autocomplete="off">
			   <label><?php echo $wo['lang']['keyword'];?></label>
			   <span class="bar"></span>
            </div>
            
            <div class="col-lg-12 pp_mat_input">
               <select name="country" id="country" class="form-control">
                  <option value="all" selected><?php echo $wo['lang']['all'];?></option>
                  <?php 
                  foreach ($wo['countries_name'] as $country_ids => $country) { 
                  $selected_c = (!empty($_GET['country']) && $_GET['country'] == $country_ids) ? ' selected': '';
                  ?>
                  <option value="<?php echo $country_ids;?>" <?php echo $selected_c?>><?php echo $country;?></option>
                  <?php } ?>
               </select>
			   <label><?php echo $wo['lang']['country'];?></label>
            </div>



            <?php
						$fields = Wo_GetUserCustomFields('profile');
						if (count($fields) > 0) {
							foreach ($fields as $key => $wo['field']) {
								$wo['field']['issearch'] = true;
								echo Wo_LoadPage('setting/profile-fields');
							}
						}
						?>


						<script>
						<?php
							$age_from = 18;
							if (!empty($_GET['age_from'])) {
								$age_from = Wo_Secure( $_GET['age_from'] );
							}
							$age_to = 50;
							if (!empty($_GET['age_to'])) {
								$age_to = Wo_Secure( $_GET['age_to'] );
							}
						?>
						$( function() {
							$( "#slider-range" ).slider({
							range: true,
							min: 10,
							max: 70,
							values: [ <?php echo $age_from;?>, <?php echo $age_to;?> ],
							slide: function( event, ui ) {
								$( "#amount" ).val( ui.values[ 0 ] + " - " + ui.values[ 1 ] );
								$( "#age_from" ).val( ui.values[ 0 ] );
								$( "#age_to" ).val( ui.values[ 1 ] );
							}
							});
							$( "#amount" ).val( $( "#slider-range" ).slider( "values", 0 ) + " - " + $( "#slider-range" ).slider( "values", 1 ) );
						});
						</script>

            <div class="clear"></div><div class="clear"></div>
						<div class="cusradiobox">
						<?php 
							$selected_filterbyage_on = '';
							$selected_filterbyage_off = 'checked';

							$agefilter_style = "display: none;";
							if (!empty($_GET['filterbyage'])) {
								if ($_GET['filterbyage'] == 'yes') {
									$selected_filterbyage_on = 'checked';
									$selected_filterbyage_off = '';
									$agefilter_style = "display: block;";
								} else if ($_GET['filterbyage'] == 'no') {
									$selected_filterbyage_on = '';
									$selected_filterbyage_off = 'checked';
								} 
							}
						?>
              <h5><?php echo $wo['lang']['age'];?></h5>
              <div>
                <span><?php echo $wo['lang']['yes']; ?></span>
                <input type="radio" name="filterbyage" id="filterbyage-1" class="tgl tgl-ios" value="yes" <?php echo $selected_filterbyage_on;?> onclick="$('#agefilter').css({'display':'block'});">
                <label class="tgl-btn" for="filterbyage-1"></label>
              </div>
              <div>
                <span><?php echo $wo['lang']['no']; ?></span>
                <input type="radio" name="filterbyage" id="filterbyage-2" class="tgl tgl-ios" value="no"<?php echo $selected_filterbyage_off;?>  onclick="$('#agefilter').css({'display':'none'});">
                <label class="tgl-btn" for="filterbyage-2"></label>
              </div>
              <div class="clear"></div>
            </div>


						<div class="col-lg-12 pp_mat_input" id="agefilter" style="<?php echo $agefilter_style;?> margin: -2em 0 2.5em;padding: 0 !important;">
							<label class="col-md-12" for="query"> <input type="text" id="amount" readonly style="border:0; color:#000000; font-weight:bold;"></label>
							<div class="form-group">
								<div id="slider-range" style="margin-top: 46px;"></div>
								<input type="hidden" name="age_from" id="age_from" value="<?php echo $age_from;?>">
								<input type="hidden" name="age_to" id="age_to" value="<?php echo $age_to;?>">
							</div>
						</div>

<div class="clear"></div><div class="clear"></div>
						<div class="cusradiobox">
							<?php 
								$selected_verified_all = 'checked';
								$selected_verified_on = '';
								$selected_verified_off = '';
								if (!empty($_GET['verified'])) {
									if ($_GET['verified'] == 'on') {
										$selected_verified_on = 'checked';
										$selected_verified_all = '';
									} else if ($_GET['verified'] == 'off') {
										$selected_verified_off = 'checked';
										$selected_verified_all = '';
									} 
								}
							?>
              <h5><?php echo $wo['lang']['verified'];?></h5>
              <div>
                <span><?php echo $wo['lang']['all']; ?></span>
                <input type="radio" name="verified" id="verified-0" class="tgl tgl-ios" value="all" <?php echo $selected_verified_all;?>>
                <label class="tgl-btn" for="verified-0"></label>
              </div>
              <div>
                <span><?php echo $wo['lang']['verified']; ?></span>
                <input type="radio" name="verified" id="verified-1" class="tgl tgl-ios" value="on" <?php echo $selected_verified_on;?>>
                <label class="tgl-btn" for="verified-1"></label>
              </div>
              <div>
                <span><?php echo $wo['lang']['unverified']; ?></span>
                <input type="radio" name="verified" id="verified-2" class="tgl tgl-ios" value="off"<?php echo $selected_verified_off;?>>
                <label class="tgl-btn" for="verified-2"></label>
              </div>
              <div class="clear"></div>
            </div>


          <div class="cusradiobox">
             <?php 
             $selected_status_all = 'checked';
             $selected_status_on = '';
             $selected_status_off = '';
             if (!empty($_GET['status'])) {
                if ($_GET['status'] == 'on') {
                  $selected_status_on = 'checked';
                  $selected_status_all = '';
                } else if ($_GET['status'] == 'off') {
                  $selected_status_off = 'checked';
                  $selected_status_all = '';
                } 
             }
             ?>
            <h5><?php echo $wo['lang']['status'];?></h5>
				<div>
					<span><?php echo $wo['lang']['all']; ?></span>
					<input type="radio" name="status" id="status-0" class="tgl tgl-ios" value="all" <?php echo $selected_status_all;?>>
					<label class="tgl-btn" for="status-0"></label>
				</div>
				<div>
					<span><?php echo $wo['lang']['online']; ?></span>
					<input type="radio" name="status" id="status-1" class="tgl tgl-ios" value="on" <?php echo $selected_status_on;?>>
					<label class="tgl-btn" for="status-1"></label>
				</div>
				<div>
					<span><?php echo $wo['lang']['offline']; ?></span>
					<input type="radio" name="status" id="status-2" class="tgl tgl-ios" value="off"<?php echo $selected_status_off;?>>
					<label class="tgl-btn" for="status-2"></label>
				</div>
            <div class="clear"></div>
         </div>
			<br>
          <div class="cusradiobox">
             <?php 
             $selected_status_all_sex = 'checked';
             $selected_status_male = '';
             $selected_status_female = '';
             if (!empty($_GET['gender'])) {
                if ($_GET['gender'] == 'male') {
                  $selected_status_male = 'checked';
                  $selected_status_all = '';
                } else if ($_GET['gender'] == 'female') {
                  $selected_status_female = 'checked';
                  $selected_status_all = '';
                } 
             }
             ?>
            <h5><?php echo $wo['lang']['gender'];?></h5>
				<div>
					<span><?php echo $wo['lang']['all']; ?></span>
					<input type="radio" name="gender" id="gender-0" class="tgl tgl-ios" value="all" <?php echo $selected_status_all_sex;?>>
					<label class="tgl-btn" for="gender-0"></label>
				</div>
				<div>
					<span><?php echo $wo['lang']['male']; ?></span>
					<input type="radio" name="gender" id="gender-1" class="tgl tgl-ios" value="male" <?php echo $selected_status_male;?>>
					<label class="tgl-btn" for="gender-1"></label>
				</div>
				<div>
					<span><?php echo $wo['lang']['female']; ?></span>
					<input type="radio" name="gender" id="gender-2" class="tgl tgl-ios" value="female" <?php echo $selected_status_female;?>>
					<label class="tgl-btn" for="gender-2"></label>
				</div>
            <div class="clear"></div>
         </div>
		 <br>
         <div class="cusradiobox">
             <?php 
             $selected_status_image_all = 'checked';
             $selected_status_image_y = '';
             $selected_status_image_n = '';
             if (!empty($_GET['image'])) {
                if ($_GET['image'] == 'yes') {
                  $selected_status_image_y = 'checked';
                  $selected_status_image_all = '';
                } else if ($_GET['image'] == 'no') {
                  $selected_status_image_n = 'checked';
                  $selected_status_image_all = '';
                } 
             }
             ?>
            <h5><?php echo $wo['lang']['profile_picture'];?></h5>
				<div>
					<span><?php echo $wo['lang']['all']; ?></span>
					<input type="radio" name="image" id="image-0" class="tgl tgl-ios" value="all" <?php echo $selected_status_image_all;?>>
					<label class="tgl-btn" for="image-0"></label>
				</div>
				<div>
					<span><?php echo $wo['lang']['yes']; ?></span>
					<input type="radio" name="image" id="image-1" class="tgl tgl-ios" value="yes" <?php echo $selected_status_image_y;?>>
					<label class="tgl-btn" for="image-1"></label>
				</div>
				<div>
					<span><?php echo $wo['lang']['no']; ?></span>
					<input type="radio" name="image" id="image-2" class="tgl tgl-ios" value="no" <?php echo $selected_status_image_n;?>>
					<label class="tgl-btn" for="image-2"></label>
				</div>
            <div class="clear"></div>
         </div>
		 </div>
            <div class="form-group last-sett-btn modal-footer" style="margin-left: -15px;">
						<button type="submit" class="btn btn-main setting-panel-mdbtn">
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg> 
							<?php echo $wo['lang']['search'];?>
						</button>
					</div>
					
         </form>
         </div>
      </div>
   </div>
</div>
<style>
body {padding-left: 0px;}
.navbar-default {padding-right: 0px;}

@media (min-width: 1200px){
body {padding-left: 0px;padding-right: 205px;}
.navbar-default {padding-right: 205px;}
}

@media (min-width: 1500px){
body {padding-left: 0px;padding-right: 260px;}
.navbar-default {padding-right: 260px;}
}

@media (max-width: 990px) {
body {padding-left: 0px;overflow-x: auto;}
}
</style>
<?php if($wo['loggedin'] == false) {  ?>
<style>
body {padding-left: 0px;}
.navbar-default {padding-right: 0px;}
@media (min-width: 1200px){
body {padding-left: 0px;padding-right: 0px;}
.navbar-default {padding-right: 0px;}
}
@media (max-width: 990px) {
body {padding-left: 0px;overflow-x: auto;}
.hideinmenu {display: none;}
}
</style>
<?php } ?>
<script>
  jQuery(document).ready(function($) {
    //Load more users
    $(".load-more-users").click(function(event) {

      var u_offset = ($("[data-search-type=user]").length > 0) ? $("[data-search-type=user]").last().attr('data-id') : 0;
      $.ajax({
        url: Wo_Ajax_Requests_File(),
        type: 'GET',
        dataType: 'json',
        data: {f: 'load-more-users',offset:u_offset,query:$("#query").val()},
        success:function(data){
          if (data['status'] == 200) {
            $("#users-cont").append(data['html'])
          }else{$(".load-more-users").remove()}
        }
      })    
    });
    //Load more groups
    $(".load-more-groups").click(function(event) {
      var g_offset = ($("[data-search-type=group]").length > 0) ? $("[data-search-type=group]").last().attr('data-id') : 0;
      $.ajax({
        url: Wo_Ajax_Requests_File(),
        type: 'GET',
        dataType: 'json',
        data: {f: 'load-more-groups',offset:g_offset,query:$("#query").val()},
        success:function(data){
          if (data['status'] == 200) {
            $("#groups-cont").append(data['html'])
          }else{$(".load-more-groups").remove()}
        }
      })   
    });
    //Load more pages
    $(".load-more-pages").click(function(event) {
      var p_offset = ($("[data-search-type=page]").length > 0) ? $("[data-search-type=page]").last().attr('data-id') : 0;
      $.ajax({
        url: Wo_Ajax_Requests_File(),
        type: 'GET',
        dataType: 'json',
        data: {f: 'load-more-pages',offset:p_offset,query:$("#query").val()},
        success:function(data){
          if (data['status'] == 200) {
            $("#pages-cont").append(data['html'])
          }else{$(".load-more-pages").remove()}
        }
      })   
    });

    
    $("#input").hover(function(event) {
      $("#input").focus()
    });

  });
</script>