<meta property="og:title" content="<?php echo $wo['title'];?>" />
      <meta property="og:type" content="article" />
      <meta property="og:image" content="<?php echo Wo_GetMedia($wo['story']['postFile'])?>" />
      <meta property="og:description" content="<?php echo $wo['description'];?>" />    
      <meta name="twitter:title" content="<?php echo $wo['title'];?>" />
      <meta name="twitter:description" content="<?php echo $wo['description'];?>" />
      <meta name="twitter:image" content="<?php echo Wo_GetMedia($wo['story']['postFile'])?>" />
