<tr class="setting-giftlist" id="GiftID_<?php echo $wo['giftlist']['id']?>" data-gift-id="<?php echo $wo['giftlist']['id']?>">
   <td><?php echo $wo['giftlist']['id']?></td>
   <td>
        <?php echo $wo['giftlist']['name'];?>
   </td>
   <td>
        <a href="<?php echo Wo_GetMedia( $wo['giftlist']['media_file'] ); ?>" target="_blank">
            <img src="<?php echo Wo_GetMedia( $wo['giftlist']['media_file'] ); ?>" class="setting-avatar" alt="<?php echo $wo['giftlist']['name']?> Gift Picture">
        </a>
   </td>
   <td>
     <div class="ajax-time" title="<?php echo date('c',$wo['giftlist']['time']); ?>">
         <?php echo Wo_Time_Elapsed_String($wo['giftlist']['time']);?>
     </div>
   </td>
   <td>
    <button class="btn btn-danger waves-effect waves-light" onclick="Wo_DeleteGift(<?php echo $wo['giftlist']['id']?>);">DELETE</button>
   </td>
</tr>