<div class="modal fade in" id="comment_report_box" role="dialog">
    <div class="modal-dialog">
    
      <div class="modal-content">
        <p style="text-align: center;padding: 30px 20px;font-family: Hind,Arial;font-size: 16px;">
          <i class="fa fa-check" aria-hidden="true" style="color: green;"></i>      
          <span class="msg"><?php echo $wo['lang']['comment_reported']; ?></span>
        </p>
      </div>
      
    </div>
</div>

<div class="modal fade in" id="post-shared" role="dialog">
    <div class="modal-dialog">
    
      <div class="modal-content">
        <p style="text-align: center;padding: 30px 20px;font-family: Hind,Arial;font-size: 16px;">
          <i class="fa fa-check" aria-hidden="true" style="color: green;"></i>      
          <?php echo $wo['lang']['post_shared']; ?>
        </p>
      </div>
      
    </div>
</div>
<div class="modal fade in" id="modal-alert" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <p style="text-align: center;padding: 30px 20px;font-family: Hind,Arial;font-size: 16px;">
          <i class="fa fa-info-circle" aria-hidden="true" style="color: #31708f;"></i>      
          <span id="modal-alert-msg">
            <?php 
              $limit = $wo['config']['connectivitySystemLimit'];
              $text  = preg_replace("/\{\{CNTC_LIMIT\}\}/", $limit, $wo['lang']['cntc_limit_reached']);
              echo $text;
            ?>
          </span>
        </p>
      </div>
    </div>
</div>
<div class="modal fade in" id="invalid_file" role="dialog">
    <div class="modal-dialog">
    
      <div class="modal-content">
        <p style="text-align: center;padding: 30px 20px;font-family: Hind,Arial;font-size: 14px;">
          <i class="fa fa-info-circle main" aria-hidden="true" style="color:#f2dede;"></i>      
          <?php echo str_replace('{file_size}', Wo_SizeUnits($wo['config']['maxUpload']), $wo['lang']['file_too_big']); ?>
        </p>
      </div>
      
    </div>
</div>
<div class="modal fade in" id="file_not_supported" role="dialog">
    <div class="modal-dialog">
    
      <div class="modal-content">
        <p style="text-align: center;padding: 30px 20px;font-family: Hind,Arial;font-size: 14px;">
          <i class="fa fa-info-circle main" aria-hidden="true" style="color:#f2dede;"></i>      
          <?php echo $wo['lang']['file_not_supported']; ?>
        </p>
      </div>
      
    </div>
</div>
<div class="modal fade" id="modal_light_box" role="dialog">
	<button type="button" class="close comm_mod_img_close" data-dismiss="modal" aria-label="Close"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></button>
  <div class="modal-dialog" >
    <div class="modal-content">              
      <div class="modal-body" style="padding: 0;">
        <img  class="image" style="width: 100%;" >
      </div>
    </div>
  </div>
</div>