<div class="sidebar-user-data">
   <div class="sidebar-listed-user-avatar">
         <a href="<?php echo $wo['UsersList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['UsersList']['username']?>">
            <img src="<?php echo $wo['UsersList']['avatar']?>">
            <div class="sidebar-listed-user-name"><?php echo $wo['UsersList']['user_name'];?></div>
         </a>
   </div>
</div>