<div class="wo_settings_page">
	<h3><?php echo $wo['lang']['change_password']; ?></h3>

	<form class="form-horizontal setting-change-password-form" method="post">
		<div class="setting-password-alert setting-update-alert"></div>
         
		 <!-- Form Name -->
		 <div class="setting-panel row">
			<?php if ($wo['setting']['user_id'] == $wo['user']['user_id']) { ?>
			<!-- Password input-->
			<div class="form-group col-lg-12">
				<label class="col-md-12" for="current_password"><?php echo $wo['lang']['current_password']; ?></label>
				<div class="col-md-12">
					<input id="current_password" name="current_password" type="password" class="form-control input-md">
				</div>
			</div>
			<?php } ?>
			<!-- Password input-->
			<div class="form-group col-lg-6">
				<label class="col-md-12" for="new_password"><?php echo $wo['lang']['new_password']; ?></label>
				<div class="col-md-12">
					<input id="new_password" name="new_password" type="password" class="form-control input-md">
				</div>
			</div>
			<!-- Password input-->
			<div class="form-group col-lg-6">
				<label class="col-md-12" for="repeat_new_password"><?php echo $wo['lang']['repeat_password']; ?></label>
				<div class="col-md-12">
					<input id="repeat_new_password" name="repeat_new_password" type="password" class="form-control input-md">
				</div>
			</div>
			<div class="form-group col-lg-12">
				<label class="col-md-12" for="two_factor"><?php echo $wo['lang']['two_factor']; ?></label>
				<div class="col-md-12">
					<select id="country" name="two_factor" class="form-control">
						<option value="1" <?php echo ($wo['setting']['two_factor'] == '1')   ? 'selected' : '';?> ><?php echo $wo['lang']['enable']; ?></option>
						<option value="0" <?php echo ($wo['setting']['two_factor'] == '0')   ? 'selected' : '';?> ><?php echo $wo['lang']['disable']; ?></option>
					</select>
				</div>
			</div>
		</div>
		
		<div class="form-group last-sett-btn modal-footer">
			<div class="ball-pulse"><div></div><div></div><div></div></div>
			<button type="submit" class="btn btn-main setting-panel-mdbtn">
               <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-check-circle"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path><polyline points="22 4 12 14.01 9 11.01"></polyline></svg> 
			   <?php echo $wo['lang']['save'];?>
			</button>
            <input type="hidden" name="user_id" value="<?php echo $wo['setting']['user_id'];?>">
            <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
         </div>
   </form>
</div>
<script type="text/javascript">
$(function() {
  $('form.setting-change-password-form').ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=update_user_password',
    beforeSend: function() {
      $('.wo_settings_page').find('.last-sett-btn .ball-pulse').fadeIn(100);
    },
    success: function(data) {
      if (data.status == 200) {
        $('.setting-password-alert').html('<div class="alert alert-success">' + data.message + '</div>');
        $('.alert-success').fadeIn('fast', function() {
          $(this).delay(2500).slideUp(500, function() {
              $(this).remove();
          });
        });
        $('form.setting-change-password-form').clearForm();
      } else if (data.errors) {
        var errors = data.errors.join("<br>");
        $('.setting-password-alert').html('<div class="alert alert-danger">' + errors + '</div>');
        $('.alert-danger').fadeIn(300);
      }
      $('.wo_settings_page').find('.last-sett-btn .ball-pulse').fadeOut(100);
    }
  });
});
</script>