<?php 
//$wo['trans'] = Wo_GetMytransactions();
?>
<div class="wo_settings_page">
	<h3><?php echo $wo['lang']['my_points']; ?></h3>
	<div class="earn_points">
		<div class="ep_illus">
			<?php if ($wo['config']['second_post_button'] == "dislike") {?>
				<div class="ep_how_many like_post">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M23,10C23,8.89 22.1,8 21,8H14.68L15.64,3.43C15.66,3.33 15.67,3.22 15.67,3.11C15.67,2.7 15.5,2.32 15.23,2.05L14.17,1L7.59,7.58C7.22,7.95 7,8.45 7,9V19A2,2 0 0,0 9,21H18C18.83,21 19.54,20.5 19.84,19.78L22.86,12.73C22.95,12.5 23,12.26 23,12V10M1,21H5V9H1V21Z" /></svg>
					<b><?php echo str_replace('%d', $wo['config']['likes_point'], $wo['lang']['earn_text_like']);?></b>
				</div>
				<div class="ep_how_many wonder_post">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M19,15H23V3H19M15,3H6C5.17,3 4.46,3.5 4.16,4.22L1.14,11.27C1.05,11.5 1,11.74 1,12V14A2,2 0 0,0 3,16H9.31L8.36,20.57C8.34,20.67 8.33,20.77 8.33,20.88C8.33,21.3 8.5,21.67 8.77,21.94L9.83,23L16.41,16.41C16.78,16.05 17,15.55 17,15V5C17,3.89 16.1,3 15,3Z" /></svg>
					<b><?php echo str_replace('%d', $wo['config']['dislikes_point'], $wo['lang']['earn_text_dislike']);?></b>
				</div>
			<?php } ?>
			<div class="ep_how_many comment_post">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M9,22A1,1 0 0,1 8,21V18H4A2,2 0 0,1 2,16V4C2,2.89 2.9,2 4,2H20A2,2 0 0,1 22,4V16A2,2 0 0,1 20,18H13.9L10.2,21.71C10,21.9 9.75,22 9.5,22V22H9Z" /></svg>
				<b><?php echo str_replace('%d', $wo['config']['comments_point'], $wo['lang']['earn_text_comment']);?></b>
			</div>
			<?php if ($wo['config']['second_post_button'] == "wonder") {?>
				<div class="ep_how_many wonder_post">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M11,9H13V7H11M12,20C7.59,20 4,16.41 4,12C4,7.59 7.59,4 12,4C16.41,4 20,7.59 20,12C20,16.41 16.41,20 12,20M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M11,17H13V11H11V17Z" /></svg>
					<b><?php echo str_replace('%d', $wo['config']['wonders_point'], $wo['lang']['earn_text_wonder']);?></b>
				</div>
			<?php } ?>
			<div class="ep_how_many create_post">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M17,7H22V17H17V19A1,1 0 0,0 18,20H20V22H17.5C16.95,22 16,21.55 16,21C16,21.55 15.05,22 14.5,22H12V20H14A1,1 0 0,0 15,19V5A1,1 0 0,0 14,4H12V2H14.5C15.05,2 16,2.45 16,3C16,2.45 16.95,2 17.5,2H20V4H18A1,1 0 0,0 17,5V7M2,7H13V9H4V15H13V17H2V7M20,15V9H17V15H20Z" /></svg>
				<b><?php echo str_replace('%d', $wo['config']['createpost_point'], $wo['lang']['earn_text_create_post']);?></b>
			</div>
			<?php if ($wo['config']['second_post_button'] == "reaction") {?>
				<div class="ep_how_many reaction_bg">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M12,17.5C14.33,17.5 16.3,16.04 17.11,14H6.89C7.69,16.04 9.67,17.5 12,17.5M8.5,11A1.5,1.5 0 0,0 10,9.5A1.5,1.5 0 0,0 8.5,8A1.5,1.5 0 0,0 7,9.5A1.5,1.5 0 0,0 8.5,11M15.5,11A1.5,1.5 0 0,0 17,9.5A1.5,1.5 0 0,0 15.5,8A1.5,1.5 0 0,0 14,9.5A1.5,1.5 0 0,0 15.5,11M12,20A8,8 0 0,1 4,12A8,8 0 0,1 12,4A8,8 0 0,1 20,12A8,8 0 0,1 12,20M12,2C6.47,2 2,6.5 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z" /></svg>
					<b><?php echo str_replace('%d', $wo['config']['reaction_point'], $wo['lang']['earn_text_reaction']);?></b>
				</div>
			<?php } ?>
		</div>
		
		<div class="row">
			<div class="col-md-6">
				<div class="counter">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-circle"><circle cx="12" cy="12" r="10"></circle></svg>
					<h2 class="timer count-title count-number" data-to="<?php echo $wo['setting']['points'];?>" data-speed="1500"><?php echo $wo['setting']['points'];?></h2>
					<p class="point-text"><?php echo $wo['lang']['points']; ?></p>
					<?php if ($wo['config']['point_allow_withdrawal'] == 1) {?>
						<p class="count-text">( <?php echo $wo['config']['dollar_to_point_cost'] . " " . $wo['lang']['points'] . " = $1.00"; ?> )</p>
					<?php } ?>
				</div>
			</div>
			<div class="col-md-6">
				<div class="points_tip">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M13,9H11V7H13M13,17H11V11H13M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z" /></svg>
					<?php if ($wo['config']['point_allow_withdrawal'] == 1) { ?>
					<p><?php echo $wo['lang']['earned_points_goto'];?> <a href="<?php echo Wo_SeoLink('index.php?link1=setting&' . $wo['user_setting'] . 'page=payments');?>" data-ajax="?link1=setting&<?php echo $wo['user_setting'];?>page=payments"><?php echo $wo['lang']['my_earnings'];?></a></p>
					<?php } else { ?>
						<p><?php echo $wo['lang']['earned_points_goto'];?> <a href="<?php echo Wo_SeoLink('index.php?link1=wallet'); ?>"><?php echo $wo['lang']['wallet'];?></a></p>
					<?php } ?>
				</div>
			</div>
		</div>
    </div>
</div>