<span id="interested-<?php echo $wo['interested']['id']?>">
	<button type="button" onclick="Wo_RegisterEventInterested(<?php echo $wo['interested']['id'];?>)" class="btn btn-default btn-sm btn-active" title="<?php echo $wo['lang']['interested'];?>">
		<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M10,17L5,12L6.41,10.58L10,14.17L17.59,6.58L19,8M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z" /></svg>
		<span class="button-text"> <?php echo $wo['lang']['interested'];?></span>
    </button>
</span>