<div class="profile-style <?php echo Wo_RightToLeft('pull-left');?>">
	<span class="user-popover" data-id="<?php echo $wo['WondredLikedusers']['id']; ?>" data-type="<?php echo $wo['WondredLikedusers']['type']; ?>">
		<a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' .  $wo['WondredLikedusers']['username'] . '');?>" data-ajax="?link1=timeline&u=<?php echo $wo['WondredLikedusers']['username'];?>">
			<div class="avatar <?php echo Wo_RightToLeft('pull-left');?>" id="inline_emo_react">
				<img src="<?php echo $wo['WondredLikedusers']['avatar'];?>" alt="<?php echo $wo['WondredLikedusers']['name']; ?> Profile Picture" />
				<?php if( isset( $wo['WondredLikedusers']['reaction'] ) ){?>
					<span class="like-emo wo_who_react_this">
						<?php
							switch (strtolower($wo['WondredLikedusers']['reaction'])) {
								case 'like':
									echo '<div class="inline_post_emoji inline_act_emoji"><img src="' . $wo['config']['theme_url'] . '/reaction/like-sm.png"></div>';
								break;
								case 'love':
									echo '<div class="inline_post_emoji inline_act_emoji"><img src="' . $wo['config']['theme_url'] . '/reaction/love-sm.png"></div>';
								break;
								case 'haha':
									echo '<div class="inline_post_emoji inline_act_emoji"><img src="' . $wo['config']['theme_url'] . '/reaction/haha-sm.png"></div>';
								break;
								case 'wow':
									echo '<div class="inline_post_emoji inline_act_emoji"><img src="' . $wo['config']['theme_url'] . '/reaction/wow-sm.png"></div>';
								break;
								case 'sad':
									echo '<div class="inline_post_emoji inline_act_emoji"><img src="' . $wo['config']['theme_url'] . '/reaction/sad-sm.png"></div>';
								break;
								case 'angry':
									echo '<div class="inline_post_emoji inline_act_emoji"><img src="' . $wo['config']['theme_url'] . '/reaction/angry-sm.png"></div>';
								break;
								default:
							}
						?>
					</span>
				<?php } ?>
			</div>
			<?php echo $wo['WondredLikedusers']['name']; ?>
		</a>
	</span>
	
	<?php if($wo['config']['user_lastseen'] == 1 && $wo['WondredLikedusers']['showlastseen'] != 0) { ?>
	<div class="user-lastseen">
		<?php echo Wo_UserStatus($wo['WondredLikedusers']['user_id'],$wo['WondredLikedusers']['lastseen']); ?>
	</div>
	<?php } ?>
	
	<div class="user-follow-button">
		<?php echo Wo_GetFollowButton($wo['WondredLikedusers']['user_id']);?>
	</div>
</div>