<?php echo Wo_LoadPage('welcome/welcome-header');?>
<div class="wrapper">
	<div class="login forgot_pass fadeInUp animated animated_5">
		<form id="reset-form" class="fadeInUp animated animated_9" method="post">
			<p class="title"><?php echo $wo['lang']['reset_new_password_label']?></p>
			<div class="errors"></div>
			<input name="password" type="password" placeholder="<?php echo $wo['lang']['new_password'];?>" autofocus/>
			<input type="hidden" name="id" value="<?php echo $_GET['code'];?>">
			<div class="login_signup_combo">
				<div class="signup__"></div>
				<div class="login__">
					<svg class="spinner" viewBox="0 0 66 66" xmlns="http://www.w3.org/2000/svg"><circle class="spinner__path" fill="none" stroke-width="7" stroke-linecap="round" cx="33" cy="33" r="29"></circle></svg>
					<button type="submit" class="btn btn-main"><?php echo $wo['lang']['reset_password']?></button>
				</div>
			</div>
		</form>
	</div>
</div>
<div class="container"><?php echo Wo_LoadPage('footer/welcome');?></div>

<script>
var working = false;
var $this = $('#reset-form');
var $state = $this.find('.errors');
$(function() {
  $this.ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=reset_password',
    beforeSend: function() {
		working = true;
		$this.find('button').attr("disabled", true);
		$this.find('.spinner').addClass("show");
    },
    success: function(data) {
      if (data.status == 200 || data.status == 600) {
        $state.addClass('success');
        $state.html('<?php echo $wo['lang']['welcome_'] ?>');
		$this.find('.spinner').removeClass("show");
        setTimeout(function () {
         window.location.href = data.location;
        }, 1000);
      } else {
        $this.find('button').attr("disabled", false);
		$this.find('.spinner').removeClass("show");
        $state.html(data.errors);
      } 
      working = false;
    }
  });
});
</script>