<?php echo Wo_LoadPage('welcome/welcome-header');?>
<div class="wrapper">
	<div class="login forgot_pass fadeInUp animated animated_5">
		<form id="confirm-form" class="fadeInUp animated animated_9" method="post">
			<p class="title"><?php echo $wo['lang']['confirm_your_account']?></p>
			<p><?php echo $wo['lang']['sign_in_attempt']?></p>
			<p><?php echo $wo['lang']['we_have_sent_you_code']?></p>
			<div class="errors"></div>
			<input name="confirm_code" type="text" placeholder="Confirmation code" autofocus/>
			<div class="login_signup_combo">
				<div class="signup__"></div>
				<div class="login__">
					<svg class="spinner" viewBox="0 0 66 66" xmlns="http://www.w3.org/2000/svg"><circle class="spinner__path" fill="none" stroke-width="7" stroke-linecap="round" cx="33" cy="33" r="29"></circle></svg>
					<button type="submit" class="btn btn-main"><?php echo $wo['lang']['confirm']?></button>
				</div>
			</div>
		</form>
	</div>
</div>
<div class="container"><?php echo Wo_LoadPage('footer/welcome');?></div>

<script>
var working = false;
var $this = $('#confirm-form');
var $state = $this.find('.errors');
$(function() {
  $this.ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=confirm_user_unusal_login',
    beforeSend: function() {
		working = true;$this.find('button').attr("disabled", true);
		$this.find('.spinner').addClass("show");
    },
    success: function(data) {
      if (data.status == 200) {
        $state.addClass('success');
        $state.html('<?php echo $wo['lang']['welcome_'] ?>');
		$this.find('.spinner').removeClass("show");
        setTimeout(function () {
         window.location.href = data.location;
        }, 1000);
      } else {
        $this.find('button').attr("disabled", false);
		$this.find('.spinner').removeClass("show");
        $state.html(data.errors);
      }
      working = false;
    }
  });
});
</script>