<div class="welcome-footer">
	<a data-ajax="?link1=terms&type=terms" href="<?php echo Wo_SeoLink('index.php?link1=terms&type=terms');?>"><?php echo $wo['lang']['terms_of_use'];?></a>
	<a data-ajax="?link1=terms&type=privacy-policy" href="<?php echo Wo_SeoLink('index.php?link1=terms&type=privacy-policy');?>"><?php echo $wo['lang']['privacy_policy'];?></a>
   <a data-ajax="?link1=contact-us" href="<?php echo Wo_SeoLink('index.php?link1=contact-us');?>"><?php echo $wo['lang']['contact_us'];?></a>
	<a data-ajax="?link1=terms&type=about-us" href="<?php echo Wo_SeoLink('index.php?link1=terms&type=about-us');?>"><?php echo $wo['lang']['about'];?></a>
   <?php  if ($wo['config']['blogs'] == 1) { ?><a href="<?php echo Wo_SeoLink('index.php?link1=blogs');?>"><?php echo $wo['lang']['blog'];?></a><?php } ?>
   <?php
               $pages = Wo_GetCustomPages();
               if (count($pages) > 0) {
                  foreach ($pages as $key => $page) {
                  ?>
                  <a href="<?php echo Wo_SeoLink('index.php?link1=site-pages&page_name=' . $page['page_name']);?>"><?php echo $page['page_title'];?></a>
                  <?php
                 }
               }
               ?>
	<span class="dropdown dropup mobi-foot">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <svg fill="#fff" height="13" viewBox="0 0 24 24" width="13" xmlns="http://www.w3.org/2000/svg">
    <path d="M0 0h24v24H0z" fill="none"/>
    <path d="M12.87 15.07l-2.54-2.51.03-.03c1.74-1.94 2.98-4.17 3.71-6.53H17V4h-7V2H8v2H1v1.99h11.17C11.5 7.92 10.44 9.75 9 11.35 8.07 10.32 7.3 9.19 6.69 8h-2c.73 1.63 1.73 3.17 2.98 4.56l-5.09 5.02L4 19l5-5 3.11 3.11.76-2.04zM18.5 10h-2L12 22h2l1.12-3h4.75L21 22h2l-4.5-12zm-2.62 7l1.62-4.33L19.12 17h-3.24z"/>
</svg> <?php echo $wo['lang']['language'];?> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu" style="width: 60px; min-width: 95px; font-size: 12px;">
            <?php
               $langs = Wo_LangsNamesFromDB();
               if (count($langs) > 0) {
                   foreach ($langs as $key => $wo['langs']) {
                     $language = $wo['langs'];
                     $languages_name = ucfirst($wo['langs']);
                     $link = ($wo['config']['seoLink'] == 1) ? '?lang=' . $language: '?&lang=' . $language;
                ?>
               <li><a class="lang" href="<?php echo $link;?>" rel="nofollow"><?php echo $languages_name;?></a></li>
               <?php } } ?>
            </ul>
         </span>
</div>
<div class="welcome-footer-right">
	<?php 
         $copy = str_replace('{site_name}', $wo['config']['siteName'], $wo['lang']['copyrights']);
         echo $copy = str_replace('{date}', date('Y'), $copy);
         ?>
</div>