<div class="row page-margin wo_page_profile" data-page="page" data-id="<?php echo $wo['page_profile']['page_id'];?>">
	<div class="profile-container">
		<div class="card hovercard">
			<div class="cardheader user-cover">
				<?php if($wo['page_profile']['is_page_onwer'] == true) { ?>
					<form action="#" method="post" class="profile-cover-changer">
						<div class="input-group">
							<span class="input-group-btn">
								<span class="btn btn-upload-image btn-file">
									<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-camera"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
									<input type="file" name="cover" accept="image/x-png, image/jpeg" onchange="Wo_UpdateProfileCover();">
								</span>
							</span>
						</div>
						<input type="hidden" name="page_id" value="<?php echo $wo['page_profile']['page_id'];?>">
					</form>
				<?php } ?>
				<div class="user-cover-uploading-container"></div>
				<div class="user-cover-uploading-progress">
					<div class="pace-activity-parent"><div class="pace-activity"></div></div>
				</div>
				<img id="cover-image" src="<?php echo $wo['page_profile']['cover']?>" alt="<?php echo $wo['page_profile']['name']?> Cover Image"/>
			</div>
		</div>

		<div class="page-info-cont row">
			<div class="col-sm-7 col-md-7 first_row">
				<div class="user-avatar flip">
					<div class="user-avatar-uploading-container">
						<div class="user-avatar-uploading-progress">
							<div class="ball-pulse"><div></div><div></div><div></div></div>
						</div>
					</div>
					<img id="page-avatar-image" alt="<?php echo $wo['page_profile']['name']?> Profile Picture" src="<?php echo $wo['page_profile']['avatar']?>"/>
					<?php if($wo['page_profile']['is_page_onwer'] == true) { ?>
						<form action="#" method="post" class="profile-avatar-changer">
							<div class="input-group">
								<span class="input-group-btn">
									<span class="btn btn-upload-image btn-file">
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-camera"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
										<input type="file" name="avatar" accept="image/x-png, image/jpeg" onchange="Wo_UpdateProfileAvatar();">
									</span>
								</span>
							</div>
							<input type="hidden" name="page_id" id="page-id" value="<?php echo $wo['page_profile']['page_id'];?>">
						</form>
					<?php } ?>
				</div>
				<div class="info">
					<div class="title">
						<a href="<?php echo $wo['page_profile']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['page_profile']['page_name'];?>"><?php echo $wo['page_profile']['name']; ?></a>
						<?php if($wo['page_profile']['verified'] == 1) {   ?>
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="verified-color feather feather-check-circle" title="Verified Page" data-toggle="tooltip"><path d="M23,12L20.56,9.22L20.9,5.54L17.29,4.72L15.4,1.54L12,3L8.6,1.54L6.71,4.72L3.1,5.53L3.44,9.21L1,12L3.44,14.78L3.1,18.47L6.71,19.29L8.6,22.47L12,21L15.4,22.46L17.29,19.28L20.9,18.46L20.56,14.78L23,12M10,17L6,13L7.41,11.59L10,14.17L16.59,7.58L18,9L10,17Z"></path></svg>
						<?php } ?>
						<div class="page_username">@<?php echo $wo['page_profile']['username']; ?></div>
					</div>
					<div class="options-buttons">
						<span class="user-follow-button page-like-btn"><?php echo Wo_GetLikeButton($wo['page_profile']['page_id']);?></span>
						<?php if ($wo['page_profile']['is_page_onwer'] == true) { ?>
							<a href="<?php echo Wo_SeoLink('index.php?link1=page-setting&page=' .  $wo['page_profile']['page_name']); ?>" data-ajax="?link1=page-setting&page=<?php echo $wo['page_profile']['page_name'];?>" class="btn btn-info btn-sm"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-2"><polygon points="16 3 21 8 8 21 3 21 3 16 16 3"></polygon></svg> <?php echo $wo['lang']['edit']; ?></a>
						<?php } ?>
						<span class="user-follow-button page_info_cta">
							<?php echo Wo_GetCallInAction($wo['page_profile']['call_action_type'], $wo['page_profile']['call_action_type_url']);?>
						</span>
					</div>
				</div>
			</div>

			<div class="col-sm-5 col-md-5 last_row">
				<div class="row sun_simp_info">
					<div class="col-md-3 col-sm-4">
						<span class="p-mata-tag"><?php echo $wo['lang']['category']; ?></span>
					</div>
					<div class="col-md-9 col-sm-8"><span><?php echo $wo['page_profile']['category']; ?></span></div>
				</div>
				<?php  if(!empty($wo['page_profile']['phone'])) {  ?>
					<div class="row sun_simp_info">
						<div class="col-md-3 col-sm-4">
							<span class="p-mata-tag"><?php echo $wo['lang']['phone_number']; ?></span>
						</div>
						<div class="col-md-9 col-sm-8"><span><?php echo $wo['page_profile']['phone']; ?></span></div>
					</div>
				<?php  }  ?>
				<?php if(!empty($wo['page_profile']['website'])) {  ?>
					<div class="row sun_simp_info">
						<div class="col-md-3 col-sm-4">
							<span class="p-mata-tag"><?php echo $wo['lang']['website']; ?></span>
						</div>
						<div class="col-md-9 col-sm-8">
							<span><a href="<?php echo $wo['page_profile']['website']?>" target="_blank"><?php echo $wo['page_profile']['website']?></a></span>
						</div>
					</div>
				<?php } ?>
				<?php if(!empty($wo['page_profile']['facebook']) || !empty($wo['page_profile']['twitter']) || !empty($wo['page_profile']['google']) || !empty($wo['page_profile']['linkedin']) || !empty($wo['page_profile']['vk'])) { ?>
					<div class="row sun_simp_info">
						<div class="col-sm-12">
							<?php  if(!empty($wo['page_profile']['twitter'])) {  ?>
								<a class="social-btn" href="https://twitter.com/<?php echo $wo['page_profile']['twitter']?>" target="_blank">
									<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M22.46,6C21.69,6.35 20.86,6.58 20,6.69C20.88,6.16 21.56,5.32 21.88,4.31C21.05,4.81 20.13,5.16 19.16,5.36C18.37,4.5 17.26,4 16,4C13.65,4 11.73,5.92 11.73,8.29C11.73,8.63 11.77,8.96 11.84,9.27C8.28,9.09 5.11,7.38 3,4.79C2.63,5.42 2.42,6.16 2.42,6.94C2.42,8.43 3.17,9.75 4.33,10.5C3.62,10.5 2.96,10.3 2.38,10C2.38,10 2.38,10 2.38,10.03C2.38,12.11 3.86,13.85 5.82,14.24C5.46,14.34 5.08,14.39 4.69,14.39C4.42,14.39 4.15,14.36 3.89,14.31C4.43,16 6,17.26 7.89,17.29C6.43,18.45 4.58,19.13 2.56,19.13C2.22,19.13 1.88,19.11 1.54,19.07C3.44,20.29 5.7,21 8.12,21C16,21 20.33,14.46 20.33,8.79C20.33,8.6 20.33,8.42 20.32,8.23C21.16,7.63 21.88,6.87 22.46,6Z"></path></svg>
								</a>
							<?php }  if(!empty($wo['page_profile']['google'])) {  ?>
								<a class="social-btn" rel="publisher" href="https://plus.google.com/<?php echo $wo['page_profile']['google']?>" target="_blank">
									<svg xmlns="http://www.w3.org/2000/svg" width="27" height="27" viewBox="0 0 24 24"><path fill="currentColor" d="M23,11H21V9H19V11H17V13H19V15H21V13H23M8,11V13.4H12C11.8,14.4 10.8,16.4 8,16.4C5.6,16.4 3.7,14.4 3.7,12C3.7,9.6 5.6,7.6 8,7.6C9.4,7.6 10.3,8.2 10.8,8.7L12.7,6.9C11.5,5.7 9.9,5 8,5C4.1,5 1,8.1 1,12C1,15.9 4.1,19 8,19C12,19 14.7,16.2 14.7,12.2C14.7,11.7 14.7,11.4 14.6,11H8Z"></path></svg>
								</a>
							<?php }  if(!empty($wo['page_profile']['facebook'])) {  ?>
								<a class="social-btn" rel="publisher" href="https://www.facebook.com/<?php echo $wo['page_profile']['facebook']?>" target="_blank">
									<svg xmlns="http://www.w3.org/2000/svg" width="21" height="21" viewBox="0 0 24 24"><path fill="currentColor" d="M17,2V2H17V6H15C14.31,6 14,6.81 14,7.5V10H14L17,10V14H14V22H10V14H7V10H10V6A4,4 0 0,1 14,2H17Z"></path></svg>
								</a>
							<?php }  if(!empty($wo['page_profile']['linkedin'])) {  ?>
								<a class="social-btn" rel="publisher" href="https://www.linkedin.com/profile/view?id=<?php echo $wo['page_profile']['linkedin']?>" target="_blank">
									<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M21,21H17V14.25C17,13.19 15.81,12.31 14.75,12.31C13.69,12.31 13,13.19 13,14.25V21H9V9H13V11C13.66,9.93 15.36,9.24 16.5,9.24C19,9.24 21,11.28 21,13.75V21M7,21H3V9H7V21M5,3A2,2 0 0,1 7,5A2,2 0 0,1 5,7A2,2 0 0,1 3,5A2,2 0 0,1 5,3Z"></path></svg>
								</a>
							<?php } ?>
							<?php  if(!empty($wo['page_profile']['vk'])) {  ?>
								<a class="social-btn" rel="publisher" href="https://vk.com/<?php echo $wo['page_profile']['vk'];?>" target="_blank">
									<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M20.8,7.74C20.93,7.32 20.8,7 20.18,7H18.16C17.64,7 17.41,7.27 17.28,7.57C17.28,7.57 16.25,10.08 14.79,11.72C14.31,12.19 14.1,12.34 13.84,12.34C13.71,12.34 13.5,12.19 13.5,11.76V7.74C13.5,7.23 13.38,7 12.95,7H9.76C9.44,7 9.25,7.24 9.25,7.47C9.25,7.95 10,8.07 10.05,9.44V12.42C10.05,13.08 9.93,13.2 9.68,13.2C9,13.2 7.32,10.67 6.33,7.79C6.13,7.23 5.94,7 5.42,7H3.39C2.82,7 2.7,7.27 2.7,7.57C2.7,8.11 3.39,10.77 5.9,14.29C7.57,16.7 9.93,18 12.08,18C13.37,18 13.53,17.71 13.53,17.21V15.39C13.53,14.82 13.65,14.7 14.06,14.7C14.36,14.7 14.87,14.85 16.07,16C17.45,17.38 17.67,18 18.45,18H20.47C21.05,18 21.34,17.71 21.18,17.14C21,16.57 20.34,15.74 19.47,14.76C19,14.21 18.29,13.61 18.07,13.3C17.77,12.92 17.86,12.75 18.07,12.4C18.07,12.4 20.54,8.93 20.8,7.74Z" /></svg>
								</a>
							<?php } if (!empty($wo['page_profile']['youtube'])) { ?>
								<a class="social-btn" href="https://www.youtube.com/<?php echo $wo['page_profile']['youtube']?>" target="_blank">
									<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M10,15L15.19,12L10,9V15M21.56,7.17C21.69,7.64 21.78,8.27 21.84,9.07C21.91,9.87 21.94,10.56 21.94,11.16L22,12C22,14.19 21.84,15.8 21.56,16.83C21.31,17.73 20.73,18.31 19.83,18.56C19.36,18.69 18.5,18.78 17.18,18.84C15.88,18.91 14.69,18.94 13.59,18.94L12,19C7.81,19 5.2,18.84 4.17,18.56C3.27,18.31 2.69,17.73 2.44,16.83C2.31,16.36 2.22,15.73 2.16,14.93C2.09,14.13 2.06,13.44 2.06,12.84L2,12C2,9.81 2.16,8.2 2.44,7.17C2.69,6.27 3.27,5.69 4.17,5.44C4.64,5.31 5.5,5.22 6.82,5.16C8.12,5.09 9.31,5.06 10.41,5.06L12,5C16.19,5 18.8,5.16 19.83,5.44C20.73,5.69 21.31,6.27 21.56,7.17Z" /></svg>
								</a>
							<?php } ?>
						</div>
					</div>
				<?php } ?>
			</div>
		</div>  
	</div>
	
	<div class="col-md-8">
		<?php if ( $wo['loggedin'] == true && isset($_GET['type']) && $_GET['type'] == 'rating'): ?>
			<div class="list-group profile-lists">
				<div class="list-group-item">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-star"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon></svg>
					<?php echo $wo['lang']['reviews']; ?>: <span><?php echo  number_format($wo['page_profile']['rating'], 1, '.', ' '); ?></span>
				</div>
				<div class="setting-well" id="page_reviews_cont">
					<?php
						$page_reviews = Wo_GetPageReviews($wo['page_profile']['page_id']);
						if (count($page_reviews) > 0) {
							foreach ($page_reviews as $wo['review']) {
								echo Wo_LoadPage('page/review-list');
							}
						} 
						else{
							echo '<h5 class="search-filter-center-text empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-star"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon></svg>' . 'No reviews found' . '</h5>';
						}
					?>
					<div class="clear"></div>
				</div>
			</div>
			<?php if (count($page_reviews) > 0): ?>
				<div class="posts_load">
					<div class="load-more">
						<button class="btn btn-default text-center pointer" onclick="Wo_LoadPageReviews(this);">
						<i class="fa fa-arrow-down progress-icon" data-icon="arrow-down"></i> <?php echo $wo['lang']['load_more'] ?></button>
					</div>
				</div>           
			<?php endif; ?>      
		<?php endif; ?>
		
		<?php
            if (isset($_GET['type'])) {
			if ($_GET['type'] == 'invite') {
		?>
			<div class="list-group profile-lists">
				<div class="list-group-item">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
					<?php echo $wo['lang']['invite_your_frineds'];?>
				</div>
				<div class="row" style="margin: 0;">
					<?php
						if (Wo_CountPageInvites($wo['page_profile']['page_id']) == 0) {
							echo '<h5 class="search-filter-center-text empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>' . $wo['lang']['not_invite'] . '</h5>';
						} else {
							foreach (Wo_GetPageInvites($wo['page_profile']['page_id']) as $wo['UsersList']) {
							echo Wo_LoadPage('page/invite-list');
						}
						}
					?>
				</div>
				<div class="clear"></div>
			</div>
		<?php } } else { ?>
		
		<?php echo Wo_GetPagePostPublisherBox($wo['page_profile']['page_id']); ?>
		
		<?php if ($wo['loggedin'] == true) { echo Wo_LoadPage('story/filter-by'); } ?>
		
		<div id="posts" data-story-page="<?php echo $wo['page_profile']['page_id'];?>">
			<div class="pinned-post-container">
				<?php
					$pinedstory = Wo_GetPinnedPost($wo['page_profile']['page_id'], 'page');
					if (count($pinedstory) == 1) {
						foreach ($pinedstory  as $wo['story']) {
							echo Wo_LoadPage('story/content');
						}
					}
				?>
			</div>
			<?php
				$stories = Wo_GetPosts(array('filter_by' => 'all', 'page_id' => $wo['page_profile']['page_id'])); 
				if (count($stories) == 0 && count($pinedstory) == 0) {
					echo Wo_LoadPage('story/page-no-stories');
				} else {
					foreach ($stories as $wo['story']) {
						echo Wo_LoadPage('story/content');
					}
				}
			?>
		</div>
		<?php if ($wo['loggedin'] == true && count($stories) > 0) {  ?>
			<div class="load-more pointer" id="load-more-posts" onclick="Wo_GetMorePosts();">
				<span class="btn btn-default"><i class="fa fa-chevron-circle-down progress-icon" data-icon="chevron-circle-down"></i> <?php echo $wo['lang']['load_more_posts']; ?><span>
			</div>
		<?php } } ?>
		<div id="load-more-filter">
			<span class="filter-by-more hidden" data-filter-by="all"></span>
		</div>
	</div>
	
	<div class="col-md-4">
		<?php if($wo['loggedin'] == true) {  ?>
			<ul class="list-group">
				<li class="list-group-item text-muted hidden" contenteditable="false"><i class="fa fa-search progress-icon fa-fw" data-icon="search"></i></li>
				<li class="form-group inner-addon" style="margin-bottom: 0px;padding: 5px;">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search glyphicon" color="gray" style="padding: 0;margin: 11px 7px 12px 8px;"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>
					<input type="text" class="form-control search-for-posts" onkeyup="Wo_SearchForPosts(this.value);" placeholder="<?php echo $wo['lang']['search_for_posts']; ?>" style="padding-left: 37px;padding-right: 37px;" />
				</li>
			</ul>
		<?php } ?>
		
		<?php if ($wo['loggedin'] && $wo['page_profile']['user_id'] != $wo['user']['id']): ?>
			<ul class="list-group" style="padding: 6px 0px;">
				<li class="list-group-item hidden"><?php echo $wo['lang']['rating']; ?></li>
				<li class="list-group-item">
					<span class="pull-left"> 
						<a data-ajax="?link1=timeline&u=<?php echo $wo['page_profile']['page_name'];?>&type=rating" href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['page_profile']['page_name'] . '&type=rating');?>"><?php echo $wo['lang']['rating'] ?></a>:
					</span>
					<span class="page-rating">
						<fieldset>
							<?php
							$rating = Wo_PageRating($wo['page_profile']['id'], $wo['user']['user_id']);
							?>
							<input type="radio" id="star5" name="rating" value="5" />
							<label for="star5" class="rate-page" data-val="5">
								<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-star <?php echo ($rating <= 5 && $rating > 4) ? 'active' : ''; ?>"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon></svg>
							</label>
							<input type="radio" id="star4" name="rating" value="4" />
							<label for="star4" class="rate-page" data-val="4">
								<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-star <?php echo ($rating >= 4 && $rating > 3) ? 'active' : ''; ?>"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon></svg>
							</label>
							<input type="radio" id="star3" name="rating" value="3" />
							<label for="star3" class="rate-page" data-val="3">
								<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-star <?php echo ($rating >= 3 && $rating > 2) ? 'active' : ''; ?>"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon></svg>
							</label>
							<input type="radio" id="star2" name="rating" value="2" />
							<label for="star2" class="rate-page" data-val="2">
								<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-star <?php echo ($rating >= 2 && $rating > 1) ? 'active' : ''; ?>"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon></svg>
							</label>
							<input type="radio" id="star1" name="rating" value="1" />
							<label for="star1" class="rate-page" data-val="1">
								<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-star <?php echo ($rating >= 1 && $rating > 0) ? 'active' : ''; ?>"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon></svg>
							</label>
						</fieldset>
						<span class="clear"></span>
					</span>
					<span><?php echo  number_format($wo['page_profile']['rating'], 1, '.', ' '); ?></span>
				</li>
			</ul>
		<?php endif; ?>

		<ul class="list-group right_user_info" style="padding-top: 5px;">
			<li class="list-group-item hidden"></li>
			<li class="list-group-item text-muted widget-heading" contenteditable="false">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-info" style="background:#047cac;"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="16" x2="12" y2="12"></line><line x1="12" y1="8" x2="12" y2="8"></line></svg> <?php echo $wo['lang']['info']; ?>			
			</li>
			<?php if(!empty($wo['page_profile']['page_description'])) {  ?>
				<li class="list-group-item user-desc-field"><?php echo $wo['page_profile']['page_description']?></li>
			<?php } ?>
			<li class="list-group-item">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" class="feather" viewBox="0 0 24 24"><path fill="currentColor" d="M23,10C23,8.89 22.1,8 21,8H14.68L15.64,3.43C15.66,3.33 15.67,3.22 15.67,3.11C15.67,2.7 15.5,2.32 15.23,2.05L14.17,1L7.59,7.58C7.22,7.95 7,8.45 7,9V19A2,2 0 0,0 9,21H18C18.83,21 19.54,20.5 19.84,19.78L22.86,12.73C22.95,12.5 23,12.26 23,12V10M1,21H5V9H1V21Z" /></svg>
				<?php echo Wo_CountPageLikes($wo['page_profile']['page_id']);?> <?php echo $wo['lang']['people_likes_this']; ?> 
				<?php if ($wo['page_profile']['is_page_onwer'] == true) { ?>
					<span class="green">+<?php echo Wo_CountLikesThisWeek($wo['page_profile']['page_id']); ?> <?php echo $wo['lang']['this_week']; ?></span>
				<?php } ?>
			</li>
			<?php  if($wo['config']['pro'] == 1 && $wo['page_profile']['is_page_onwer'] == true) {  ?>
				<li class="list-group-item">
					<?php if ($wo['user']['is_pro'] == 1) { ?>
						<?php if ($wo['user']['pro_type'] > 1) {?>
							<?php if ($wo['page_profile']['boosted'] == 0) {?>
								<a href="<?php echo $wo['marker'];?>boosted">
									<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" class="feather" viewBox="0 0 24 24"><path fill="currentColor" d="M7,2V13H10V22L17,10H13L17,2H7Z" /></svg> <?php echo $wo['lang']['boost_page'];?>
								</a>
							<?php } else { ?>
								<a href="<?php echo $wo['marker'];?>un-boost">
									<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" class="feather" viewBox="0 0 24 24"><path fill="currentColor" d="M7,2V13H10V22L17,10H13L17,2H7Z" /></svg> <?php echo $wo['lang']['un_boost_page'];?>
								</a>
							<?php } ?>
						<?php  }  ?>
					<?php  } else {  ?>
						<a href="<?php echo Wo_SeoLink('index.php?link1=go-pro');?>">
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" class="feather" viewBox="0 0 24 24"><path fill="currentColor" d="M7,2V13H10V22L17,10H13L17,2H7Z" /></svg> <?php echo $wo['lang']['boost_page'];?>
						</a>
					<?php  }  ?>
				</li>
			<?php  }  ?>
			<?php if ($wo['loggedin'] && $wo['page_profile']['user_id'] != $wo['user']['id']) { ?>
				<li class="list-group-item">
					<a data-ajax="?link1=timeline&u=<?php echo $wo['page_profile']['page_name'];?>&type=rating" href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['page_profile']['page_name'] . '&type=rating');?>">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" class="feather" viewBox="0 0 24 24"><path fill="currentColor" d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z" /></svg> <?php echo $wo['lang']['rating'] ?>
					</a>
				</li>
			<?php  }  ?>
			<li class="list-group-item">
				<a data-ajax="?link1=timeline&u=<?php echo $wo['page_profile']['page_name'];?>&type=invite" href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['page_profile']['page_name'] . '&type=invite');?>">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" class="feather" viewBox="0 0 24 24"><path fill="currentColor" d="M15,14C12.33,14 7,15.33 7,18V20H23V18C23,15.33 17.67,14 15,14M6,10V7H4V10H1V12H4V15H6V12H9V10M15,12A4,4 0 0,0 19,8A4,4 0 0,0 15,4A4,4 0 0,0 11,8A4,4 0 0,0 15,12Z" /></svg> <?php echo $wo['lang']['page_inviate_label']; ?>
				</a>
			</li>
			<?php if ($wo['loggedin'] && !Wo_IsAdmin() && $wo['user']['id'] != $wo['page_profile']['user_id'] && !Wo_IsAdmin($wo['page_profile']['user_id'])): ?>
				<?php if (!Wo_IsReportExists($wo['page_profile']['page_id'],'page')): ?>
					<li id="report_status" class="pointer list-group-item" onclick="$('#report_page').modal('show');">
						<span class="menu-item">
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" class="feather" viewBox="0 0 24 24"><path fill="currentColor" d="M14.4,6L14,4H5V21H7V14H12.6L13,16H20V6H14.4Z" /></svg> <?php echo $wo['lang']['report_page']; ?>
						</span>
					</li>
				<?php else: ?>
					<li id="report_status" class="pointer list-group-item" onclick="Wo_ReportPage(<?php echo $wo['page_profile']['page_id']; ?>,false);">
						<span class="menu-item">
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" class="feather" viewBox="0 0 24 24"><path fill="currentColor" d="M14.4,6L14,4H5V21H7V14H12.6L13,16H20V6H14.4Z" /></svg> <?php echo $wo['lang']['unreport']; ?>
						</span>
					</li>
				<?php endif; ?>
			<?php endif; ?>
			
			<li class="list-group-item">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" class="feather" viewBox="0 0 24 24"><path fill="currentColor" d="M21,6V8H3V6H21M3,18H12V16H3V18M3,13H21V11H3V13Z" /></svg>
				<?php echo Wo_CountPagePosts($wo['page_profile']['page_id']);?> <?php echo $wo['lang']['posts']; ?>
			</li>
			
			<li class="list-group-item" style="padding-top:0; padding-bottom:0;">
                <hr>
            </li>
			<?php  if(!empty($wo['page_profile']['company'])) {  ?>
				<li class="list-group-item">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" class="feather" viewBox="0 0 24 24"><path fill="currentColor" d="M10,2H14A2,2 0 0,1 16,4V6H20A2,2 0 0,1 22,8V19A2,2 0 0,1 20,21H4C2.89,21 2,20.1 2,19V8C2,6.89 2.89,6 4,6H8V4C8,2.89 8.89,2 10,2M14,6V4H10V6H14Z" /></svg>
					<?php echo $wo['page_profile']['company']?>
				</li>
			<?php  }  ?>
			<?php if(!empty($wo['page_profile']['address'])) {  ?>
				<li class="list-group-item">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" class="feather" viewBox="0 0 24 24"><path fill="currentColor" d="M12,11.5A2.5,2.5 0 0,1 9.5,9A2.5,2.5 0 0,1 12,6.5A2.5,2.5 0 0,1 14.5,9A2.5,2.5 0 0,1 12,11.5M12,2A7,7 0 0,0 5,9C5,14.25 12,22 12,22C12,22 19,14.25 19,9A7,7 0 0,0 12,2Z" /></svg>
					<span class="pointer" onclick="$('.user-location-frame').fadeToggle();"><?php echo $wo['lang']['located_in']; ?> <?php echo $wo['page_profile']['address'];?></span>
					<?php if (!empty($wo['config']['google_map_api']) && $wo['config']['google_map'] == 1) { ?>
						<iframe class="user-location-frame" width="100%" frameborder="0" style="border:0;margin-top: 10px;display: none;" src="https://www.google.com/maps/embed/v1/place?key=<?php echo $wo['config']['google_map_api']; ?>&q=<?php echo $wo['page_profile']['address'];?>&language=en"></iframe>
					<?php } ?>
				</li>
			<?php } ?>
			
		</ul>

		<?php if($wo['loggedin'] == true) {  ?>
		<?php
			$pages = Wo_PageSug(1);
			if (count($pages) != 0) {
		?>
			<ul class="list-group sidebar-conatnier" id="sidebar-page-list-container">
				<li class="list-group-item text-muted hidden" contenteditable="false"><?php echo $wo['lang']['pages_you_may_like']; ?></li>
				<li class="list-group-item text-muted widget-heading" contenteditable="false">
					<span onclick="Wo_ReloadSideBarPages();" class="<?php echo Wo_RightToLeft('pull-right');?> refresh">
						<i class="fa fa-refresh progress-icon" data-icon="refresh"></i>
					</span> 
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-flag" style="background:#f79f58;"><path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z"></path><line x1="4" y1="22" x2="4" y2="15"></line></svg>
					<?php echo $wo['lang']['pages_you_may_like']; ?>
				</li>
				<div class="sidebar">
					<div class="sidebar-pages-may-know-container">
						<?php 
							foreach ($pages as $wo['PageList']) {
							$wo['PageList']['user_name'] = $wo['PageList']['name'];
								echo Wo_LoadPage('sidebar/sidebar-home-page-list');
							} 
						?>
					</div>
					<div class="clear"></div>
				</div>
			</ul>
		<?php } ?>
		<?php } ?>
    
		<?php 
		$sidebar_ad = Wo_GetAd('sidebar', false);
		if (!empty($sidebar_ad)) {?>
			<ul class="list-group sidebar-ad">
				<?php echo $sidebar_ad; ?>
			</ul>
		<?php } ?>
		<?php echo Wo_LoadPage('footer/sidebar-footer')?>
	</div>
</div>

<div class="modal fade" id="report_page" role="dialog">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
				<h4 class="modal-title">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-alert-triangle"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"></path><line x1="12" y1="9" x2="12" y2="13"></line><line x1="12" y1="17" x2="12" y2="17"></line></svg>
					<?php echo $wo['lang']['report_page']; ?>
				</h4>
			</div>
			<div class="modal-body">
				<textarea class="form-control" placeholder="Type text" dir="auto" rows="4" id="report-page-text-<?php echo $wo['page_profile']['page_id']; ?>"></textarea>
			</div>
			<div class="modal-footer">
				<div class="ball-pulse"><div></div><div></div><div></div></div>
				<button type="button" class="btn  btn-main" id="report-page-button" onclick="Wo_ReportPage(<?php echo $wo['page_profile']['page_id']; ?>,true)" >
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>
					<?php echo $wo['lang']['send']; ?>
				</button>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="rate_page" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
				<h4 class="modal-title">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-star"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon></svg> 
					<?php echo $wo['lang']['rate']; ?>: <?php echo $wo['page_profile']['page_title'];?>
				</h4>
			</div>
			<div class="modal-body">
				<textarea class="form-control" placeholder="<?php echo $wo['lang']['your_review']; ?>" dir="auto" rows="5" id="rating_review"></textarea>
				<input type="hidden" id="rating_value" >
			</div>
			<div class="modal-footer">
				<div class="ball-pulse"><div></div><div></div><div></div></div>
				<button type="button" class="btn  btn-main" id="rate-page-button" onclick="Wo_RatePage()" >
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-save"><path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z"></path><polyline points="17 21 17 13 7 13 7 21"></polyline><polyline points="7 3 7 8 15 8"></polyline></svg>
					<?php echo $wo['lang']['save']; ?>
				</button>
			</div>
		</div>
	</div>
</div>
<div class="modal fade in" id="page_rated" role="dialog">
	<div class="modal-dialog">
      <div class="modal-content">
        <p style="text-align: center;padding: 30px 20px;font-family: Hind,Arial;font-size: 16px;">
          <i class="fa fa-check" aria-hidden="true" style="color: green;"></i>      
          <?php echo $wo['lang']['page_rated']; ?>
        </p>
      </div>
    </div>
</div>
<!-- JS Pages functions -->
<script>
$(function () {
  if($(window).width() > 600) {
    $(".user-avatar").hover(function () {
      $('.profile-avatar-changer').fadeIn(100);
    }, function () {
      $('.profile-avatar-changer').fadeOut(100);
    });
  }
  if($(window).width() > 600) {
    $(".user-cover").hover(function () {
      $('.profile-cover-changer').fadeIn(100);
    }, function () {
      $('.profile-cover-changer').fadeOut(100);
    });
  }
  $('form.profile-avatar-changer').ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=update_page_avatar_picture',

    beforeSend: function () {
      $('.user-avatar-uploading-container,.user-avatar-uploading-progress').fadeIn(200);
    },
    success: function (data) {
      if(data.status == 200) {
        $('[id^=page-avatar-image]').attr("src", data.img);
      }
      $('.user-avatar-uploading-container, .user-avatar-uploading-progress').fadeOut(200);
    }
  });

  $('form.profile-cover-changer').ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=update_page_cover_picture',

    beforeSend: function () {
      $('.user-cover-uploading-container,.user-cover-uploading-progress').fadeIn(200);
    },
    success: function (data) {
      if(data.status == 200) {
        $('[id^=cover-image]').attr("src", data.img);
      }
      $('.user-cover-uploading-container,.user-cover-uploading-progress').fadeOut(200);
    }
  });
  <?php if ($wo['loggedin'] == true): ?>
    <?php if (!Wo_IsPageRatingExists($wo['page_profile']['page_id'],$wo['user']['id'])): ?>
      $(".rate-page").click(function(event) {
        $("#rate_page").modal().find('#rating_value').val($(this).attr('data-val'));
      });
    <?php else: ?>
      $(".rate-page").click(function(event) {
        $("#page_rated").modal();
        Wo_Delay(function(){
         $("#page_rated").modal('hide'); 
        },2000)
        return false;
      });
    <?php endif; ?>
  <?php endif;?>
});

  

function Wo_ReportPage(id = false,report = true){
    var report_text = $("#report-page-text-<?php echo $wo['page_profile']['page_id']; ?>").val();
    if (!id) {return false;}
    else if(report == true){
      if (!report_text) {return false;}  
    }
	$('#report_page').find('.modal-footer .ball-pulse').fadeIn(100);
    $.ajax({
        url: Wo_Ajax_Requests_File() + '?f=reports&s=report_page',
        type: 'POST',
        dataType: 'json',
        data: {text:report_text,page:id}
    })
    .done(function(data) {
        if(data.status == 200 && data.code == 0){
            $('#report_status').replaceWith('\
                <li id="report_status" class="list-group-item pointer" onclick="$(\'#report_page\').modal(\'show\');">\
                    <span class="menu-item"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" class="feather" viewBox="0 0 24 24"><path fill="currentColor" d="M14.4,6L14,4H5V21H7V14H12.6L13,16H20V6H14.4Z" /></svg>\
                    <?php echo $wo['lang']['report_page']; ?></span>\
                </li>');
        }

        else if (data.status == 200 && data.code == 1) {
            $("#report-page-text-<?php echo $wo['page_profile']['page_id']; ?>").val('');
            $("#report_page").modal('hide');
            $('#report_status').replaceWith('\
                <li id="report_status" class="list-group-item pointer" onclick="Wo_ReportPage(<?php echo $wo['page_profile']['page_id']; ?>,false);">\
                    <span class="menu-item"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" class="feather" viewBox="0 0 24 24"><path fill="currentColor" d="M14.4,6L14,4H5V21H7V14H12.6L13,16H20V6H14.4Z" /></svg>\
                    <?php echo $wo['lang']['unreport']; ?></span>\
                </li>');
        }
        $('#report_page').find('.modal-footer .ball-pulse').fadeOut(100);
    })
    .fail(function() {
        console.log("error");
    })
}

function Wo_UpdateProfileAvatar() {
  $("form.profile-avatar-changer").submit();
}

function Wo_UpdateProfileCover() {
  $("form.profile-cover-changer").submit();
}

function Wo_RatePage(self){

  $.ajax({
    url: Wo_Ajax_Requests_File() + '?f=pages&s=rate_page',
    type: 'POST',
    dataType: 'json',
    data: {text: $("#rating_review").val(),page_id:'<?php echo $wo['page_profile']['page_id'];?>',val:$("#rating_value").val()},
  })
  .done(function(data) {
    if (data.status == 200) {
      $("#rate_page").modal('hide');
      location.reload();
    }
    Wo_progressIconLoader($("#rate-page-button"));
  })
  .fail(function() {
    console.log("error");
  })
}

function Wo_LoadPageReviews(self = false){
  if (!self) {
    return false;
  }
  var preview_id = ($('[data-user-review]').length > 0) ? $('[data-user-review]').last().attr('data-user-review') : 0;
  $.ajax({
    url: Wo_Ajax_Requests_File(),
    type: 'GET',
    dataType: 'json',
    data: {f: 'pages',s:'load_reviews',page:'<?php echo $wo['page_profile']['page_id'];?>',after_id:preview_id},
  })
  .done(function(data) {
    if (data.status == 200) {
      $("#page_reviews_cont").append(data.html);
    }
    else{
      $(self).fadeIn('fast', function() {
        $(this).remove();
      });
    }
  })
  .fail(function() {
    console.log("error");
  })
}
</script>
<?php if (!empty($wo['page_profile']['background_image']) && $wo['page_profile']['background_image_status'] == 1) { ?>
<style>
  body {
    background: url(<?php echo Wo_GetMedia($wo['page_profile']['background_image']); ?>) fixed !important;
    background-size:100% auto;
  }
</style>
<?php } ?>