<div class="user-ad-container" id="<?php echo($wo['wo_ad_id']); ?>">
	<video id="video--<?php echo $wo['media']['storyId'];?>" onplay="Wo_AddVideoViews($(this).attr('data-post-video'))" class="video-js vjs-big-play-centered <?php echo($wo['rvad_con']); ?>" controls preload="auto" poster="<?php  echo $wo['media']['video_thumb'];?>" data-setup="{}" data-post-video="<?php echo $wo['media']['storyId'];?>" style="width:100%;height:500px;">
	    <source src="<?php echo $wo['media']['filename'];?>" type='video/mp4'>
	    <source src="<?php echo $wo['media']['filename'];?>" type='video/webm'> 
	</video>
</div>  
<script>
fluidPlayer('video--<?php echo $wo['media']['storyId'];?>', {
    layoutControls: {
        primaryColor:           "<?php echo $wo['config']['btn_background_color'];?>",
        fillToContainer: true,
    }
});
</script>