<div class="reply reply-container" id="comment_reply_<?php echo $wo['reply']['id'];?>" data-reply-id="<?php echo $wo['reply']['id'];?>">
   <a class="<?php echo Wo_RightToLeft('pull-left'); ?>" href="<?php echo $wo['reply']['publisher']['url']?>" onclick="InjectAPI('{&quot;profile_id&quot; : &quot;<?php echo $wo['reply']['publisher']['id']?>&quot;, &quot;type&quot;:&quot;<?php echo $wo['reply']['publisher']['type']?>&quot;}', event);">
   <img class="avatar <?php echo Wo_RightToLeft('pull-left'); ?>" src="<?php echo $wo['reply']['publisher']['avatar']?>" alt="avatar">
   </a>
   <div class="comment-body">
      <div class="comment-heading reply-heading">
         <span class="user-popover" data-id="<?php echo $wo['reply']['publisher']['id'];?>" data-type="<?php echo $wo['reply']['publisher']['type'];?>">
         <a href="<?php echo $wo['reply']['publisher']['url']?>" data-ajax="?link1=timeline&u=<?php echo $wo['reply']['publisher']['username'];?>"  onclick="InjectAPI('{&quot;profile_id&quot; : &quot;<?php echo $wo['reply']['publisher']['id']?>&quot;, &quot;type&quot;:&quot;<?php echo $wo['reply']['publisher']['type']?>&quot;}', event);">
            <h4 class="user">
               <?php echo $wo['reply']['publisher']['name']?>
            </h4>
         </a>
         </span>
         <?php  if($wo['reply']['publisher']['verified'] == 1) {   ?>
         <span class="verified-color" data-toggle="tooltip" title="<?php echo $wo['lang']['verified_user'];?>"><i class="fa fa-check-circle"></i></span>
         <?php } ?>
         <div class="<?php echo Wo_RightToLeft('pull-right');?> comment-options comment_edele_options">
            <?php if ($wo['reply']['post_onwer'] === true|| $wo['reply']['onwer'] === true || Wo_IsAdmin()) {?>
               <?php if ($wo['reply']['post_onwer'] === true|| $wo['reply']['onwer'] === true): ?>
               <span class="pointer"  onclick="Wo_EditReplyComment(<?php echo $wo['reply']['id']?>);">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-2"><polygon points="16 3 21 8 8 21 3 21 3 16 16 3"></polygon></svg>
               </span>
               &nbsp;
               <?php endif; ?>
               <span class="pointer" id="deleteComment" onclick="Wo_DeleteReplyComment(<?php echo $wo['reply']['id']?>);">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg>
               </span>           
            <?php } ?>
         </div>
         <span class="time ajax-time" title="<?php echo date('c',$wo['reply']['time']);?>"><?php echo $wo['reply']['time']?></span>
         <div class="reply-text" data-post-comm-reply-text="<?php echo $wo['reply']['id']?>">
         <?php echo $wo['reply']['text']?>
               
         </div>
         
         
         <div class="clear"></div>   
      </div>

        <?php if ($wo['config']['second_post_button'] == 'reaction') { ?>
            <!-- reaction -->

            <div class="like-stat stat-item" id="comment_reacted">
              <span class="like-emo replay-reactions-icons-<?php echo $wo['reply']['id']; ?>">
              <?php echo Wo_GetPostReactions($wo['reply']['id'],"replay");?>
              </span>
            </div>
        <?php } ?>

            <span class="comment-options">
				<?php if ($wo['config']['second_post_button'] == 'reaction') { ?>
					<div class="wo-reaction wo-reaction-replay stat-item" data-id="<?php echo $wo['reply']['id']; ?>" id="comment_reactions" data-id="<?php echo $wo['comment']['id']; ?>">
                <span class="like-btn like-btn-replay" data-id="<?php echo $wo['reply']['id']; ?>">
                    <?php
                    if (Wo_IsReacted($wo['reply']['id'], $wo['reply']['user_id'],"replay") === true) {    
                    echo '<span class="replay-status-reaction-'.$wo['reply']['id'].' active-like"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-thumbs-up"><path d="M14 9V5a3 3 0 0 0-3-3l-4 9v11h11.28a2 2 0 0 0 2-1.7l1.38-9a2 2 0 0 0-2-2.3zM7 22H4a2 2 0 0 1-2-2v-7a2 2 0 0 1 2-2h3"></path></svg> <span class="r_likes-'.$wo['reply']['id'].'"></span></span>';   
                    } else {   
                    echo '<span class="replay-status-reaction-'.$wo['reply']['id'].'"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-thumbs-up"><path d="M14 9V5a3 3 0 0 0-3-3l-4 9v11h11.28a2 2 0 0 0 2-1.7l1.38-9a2 2 0 0 0-2-2.3zM7 22H4a2 2 0 0 1-2-2v-7a2 2 0 0 1 2-2h3"></path></svg> <span class="r_likes-'.$wo['reply']['id'].'"></span></span>';   
                    }    
                    ?>
                </span>
                <ul class="reactions-box reactions-box-comment-replay-container-<?php echo $wo['reply']['id']; ?>" data-id="<?php echo $wo['reply']['id']; ?>" style="<?php if ($wo['language_type'] == 'rtl') {?> left: auto; <?php }else{ ?> right: auto; <?php }?>">
                    <li class="reaction reaction-like animated_2" data-reaction="Like" onclick="Wo_RegisterReplyReaction(<?php echo $wo['reply']['user_id']; ?>,<?php echo $wo['reply']['id']; ?>,'Like');">
						<div class="emoji emoji--like">
							<div class="emoji__hand"><div class="emoji__thumb"></div></div>
						</div>
					</li>
                    <li class="reaction reaction-love animated_4" data-reaction="Love" onclick="Wo_RegisterReplyReaction(<?php echo $wo['reply']['user_id']; ?>,<?php echo $wo['reply']['id']; ?>,'Love');">
						<div class="emoji emoji--love">
							<div class="emoji__heart"></div>
						</div>
					</li>
                    <li class="reaction reaction-haha animated_6" data-reaction="HaHa" onclick="Wo_RegisterReplyReaction(<?php echo $wo['reply']['user_id']; ?>,<?php echo $wo['reply']['id']; ?>,'HaHa');">
						<div class="emoji emoji--haha">
							<div class="emoji__face">
								<div class="emoji__eyes"></div>
								<div class="emoji__mouth">
									<div class="emoji__tongue"></div>
								</div>
							</div>
						</div>
					</li>
                    <li class="reaction reaction-wow animated_8" data-reaction="Wow" onclick="Wo_RegisterReplyReaction(<?php echo $wo['reply']['user_id']; ?>,<?php echo $wo['reply']['id']; ?>,'Wow');">
						<div class="emoji emoji--wow">
							<div class="emoji__face">
								<div class="emoji__eyebrows"></div>
								<div class="emoji__eyes"></div>
								<div class="emoji__mouth"></div>
							</div>
						</div>
					</li>
                    <li class="reaction reaction-sad animated_10" data-reaction="Sad" onclick="Wo_RegisterReplyReaction(<?php echo $wo['reply']['user_id']; ?>,<?php echo $wo['reply']['id']; ?>,'Sad');">
						<div class="emoji emoji--sad">
							<div class="emoji__face">
								<div class="emoji__eyebrows"></div>
								<div class="emoji__eyes"></div>
								<div class="emoji__mouth"></div>
							</div>
						</div>
					</li>
                    <li class="reaction reaction-angry animated_12" data-reaction="Angry" onclick="Wo_RegisterReplyReaction(<?php echo $wo['reply']['user_id']; ?>,<?php echo $wo['reply']['id']; ?>,'Angry');">
						<div class="emoji emoji--angry">
							<div class="emoji__face">
								<div class="emoji__eyebrows"></div>
								<div class="emoji__eyes"></div>
								<div class="emoji__mouth"></div>
							</div>
						</div>
					</li>
                </ul>
            </div>
				<?php } else { ?>
				
				
                  <span class="comment-icons">
                  <span class="pointer" id="LikeReplyComment" onclick="Wo_RegisterCommentReplyLike(<?php echo $wo['reply']['id']; ?>);">
                  <?php if($wo['reply']['is_comment_liked'] !== true) { ?>
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-thumbs-up"><path d="M14 9V5a3 3 0 0 0-3-3l-4 9v11h11.28a2 2 0 0 0 2-1.7l1.38-9a2 2 0 0 0-2-2.3zM7 22H4a2 2 0 0 1-2-2v-7a2 2 0 0 1 2-2h3"></path></svg>
                  <?php } else { ?>
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-thumbs-up active-like"><path d="M14 9V5a3 3 0 0 0-3-3l-4 9v11h11.28a2 2 0 0 0 2-1.7l1.38-9a2 2 0 0 0-2-2.3zM7 22H4a2 2 0 0 1-2-2v-7a2 2 0 0 1 2-2h3"></path></svg>
                  <?php } ?>
                  </span> 
                  <span id="comment-reply-likes">
                  <?php echo $wo['reply']['comment_likes'];?>
                  </span> · 
                  </span>
                  <span class="pointer" id="WonderReplyComment" onclick="Wo_RegisterCommentReplyWonder(<?php echo $wo['reply']['id']; ?>);">
                  <?php if($wo['reply']['is_comment_wondered'] !== true) { ?>
                              <?php echo $wo['second_post_button_icon'];?>
                  <?php } else {  ?>
                              <span class="active-wonder"><?php echo $wo['second_post_button_icon'];?></span>
                  <?php } ?>
                  </span>
                  <span id="comment-reply-wonders">
                  <?php echo $wo['reply']['comment_wonders'];?>
                  </span> · 
            </span>

      <?php } ?>
      <div class="hidden" data-post-comm-reply-edit="<?php echo $wo['reply']['id']?>">
            <br>
            <textarea class="edit-box form-control" onkeydown="Wo_UpdatCommReply(<?php echo $wo['reply']['id']?>,event,this)"></textarea>
      </div>
   </div>
   <?php echo Wo_LoadPage('modals/delete-comment-reply');?>
</div>