<div class="user-data nearby_user_wrapper col-md-4 text-center" id="<?php echo $wo['UsersList']['user_data']['id']; ?>">
  <div class="avatar">
      <img src="<?php echo $wo['UsersList']['user_data']['avatar'];?>" alt="<?php echo $wo['UsersList']['user_data']['name']; ?> Profile Picture" />
    </div>
  <span class="user-popover" data-id="<?php echo $wo['UsersList']['user_data']['id'];?>" data-type="<?php echo $wo['UsersList']['user_data']['type'];?>">
  <a href="<?php echo $wo['UsersList']['user_data']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['UsersList']['user_data']['username'];?>" class="user_wrapper_link"><?php echo $wo['UsersList']['user_data']['name']; ?></a>
  </span>
  
  
  
  <?php if($wo['config']['user_lastseen'] == 1 && $wo['UsersList']['user_data']['showlastseen'] != 0): ?>
  <div class="user-lastseen">
    <?php
      if ($wo['UsersList']['user_data']['age'] && $wo['UsersList']['user_data']['birth_privacy'] == 0) {
        echo $wo['UsersList']['user_data']['age'];
      } else {
        echo Wo_UserStatus($wo['UsersList']['user_data']['user_id'], $wo['UsersList']['user_data']['lastseen']);
      }
    ?>
  </div>

  <?php endif; ?>
  
    <div class="user-map-button">
	<?php if (!empty($wo['UsersList']['user_geoinfo']) && (!empty($wo['user']['lat']) && !empty($wo['user']['lng'])) && ($wo['UsersList']['distance'] > 0)): ?>
     <small data-toggle='tooltip' title="<?php echo $wo['lang']['show_location']; ?>">
       <span onclick="Wo_ShowUserLocationMap('<?php echo $wo['UsersList']['user_geoinfo']?>');">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-map-pin"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg> <?php echo $wo['lang']['close_to_u']; ?> <?php echo number_format($wo['UsersList']['distance'],3); ?>/k
       </span>
     </small>
	 <?php endif; ?>
    </div>
  
<div class="user-follow-button">
    <?php echo Wo_GetFollowButton($wo['UsersList']['user_data']['user_id']);?>
  </div>
  
  <div class="clear"></div>
</div>
