<div class="container-fluid">
    <div class="block-header">
        <h2>Manage Features > Games > Manage Games</h2>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h2>Manage Games</h2>
                </div>
                <div class="body">
                   <input type="hidden" id="hash_id" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                   <div class="clearfix"></div>
                   <div class="table-responsive1">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                                <tr>
                                      <th>ID</th>
					                  <th>Name</th>
					                  <th>Players</th>
					                  <th>Added</th>
					                  <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                               <?php 
				                foreach (Wo_GetAllGames(50000) as $wo['gamelist']) {
				                  echo Wo_LoadAdminPage('manage-games/list');
				                }
				               ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->

<script>
$(function () {
	$('table').DataTable();
});

jQuery(document).ready(function($) {
   $(".delete-film").click(function(event) {
	    	$("#delete-film").attr('data-film-ident', $(this).attr('id')).modal('show');
	    });
});

function Wo_DeleteGame(game_id) {
  if (confirm("Are you sure you want to delete this game?'") == false) {
    return false;
  }
  $('#GameID_' + game_id).fadeOut(300, function() {
    $(this).remove();
  });
  $.get(Wo_Ajax_Requests_File(),{f:'admin_setting',s:'delete_game',game_id: game_id});
}
</script>