<div class="page-margin">
	<div class="row">
		<div class="col-md-12">
			<div class="nav navbar-nav pull-right movies-search hidden-xs">
				<div class="w100">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search" color="#384047"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>
					<input type="text" placeholder="<?php echo $wo['lang']['search']; ?>" id="search-movies">
				</div>
				<ul class="search-result" id="search-movies-result"></ul>
			</div>
			<div>
				<ul id="links_cont" class="movies-top-breadcrumb">
					<li class="links_cont_item active"><a href="<?php echo Wo_SeoLink('index.php?link1=movies') ?>"><?php echo $wo['lang']['movies']; ?></a></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"><?php echo $wo['lang']['genre']; ?> <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"><path fill="currentColor" d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z" /></svg></a>
						<ul class="dropdown-menu clearfix" role="menu">
							<?php foreach ($wo['film-genres'] as $g_key => $genre): ?>
								<li><a href="<?php echo Wo_SeoLink('index.php?link1=movies-genre&genre='.$g_key); ?>"><?php echo $genre; ?></a></li>
							<?php endforeach;?>
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"><?php echo $wo['lang']['country']; ?> <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"><path fill="currentColor" d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z" /></svg></a>
						<ul class="dropdown-menu clearfix" role="menu">
							<?php foreach ($wo['countries'] as $c_key => $country): ?>
								<li><a href="<?php echo Wo_SeoLink('index.php?link1=movies-country&country='.$c_key); ?>"><?php echo $country;?></a></li>
							<?php endforeach; ?>
						</ul>
					</li>
					<li class="links_cont_item movies-subheadnav" data-movies="rec"><a href="javascript:void(0);"><?php echo $wo['lang']['recommended']; ?></a></li>
					<li class="links_cont_item movies-subheadnav" data-movies="new"><a href="javascript:void(0);"><?php echo $wo['lang']['new']; ?></a></li>
					<li class="links_cont_item movies-subheadnav" data-movies="mtw"><a href="javascript:void(0);"><?php echo $wo['lang']['most_watched']; ?></a></li>
				</ul>
				<div class="clear"></div>
			</div>
			<div class="movies row">
				<div class="w100 movies-inner sun_movies_list">
					<?php if (count($wo['movies']) > 0): ?>
						<?php foreach ($wo['movies'] as $wo['film']): ?>
							<?php echo Wo_LoadPage("movies/includes/films-list"); ?>
						<?php endforeach ?>
					<?php else: ?>
						<?php echo '<h5 class="search-filter-center-text empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-film"><rect x="2" y="2" width="20" height="20" rx="2.18" ry="2.18"></rect><line x1="7" y1="2" x2="7" y2="22"></line><line x1="17" y1="2" x2="17" y2="22"></line><line x1="2" y1="12" x2="22" y2="12"></line><line x1="2" y1="7" x2="7" y2="7"></line><line x1="2" y1="17" x2="7" y2="17"></line><line x1="17" y1="17" x2="22" y2="17"></line><line x1="17" y1="7" x2="22" y2="7"></line></svg> '. $wo['lang']['no_movies_found'] .' </h5>';?>
					<?php endif; ?>
				</div>
				<div class="col-md-12 col-lg-12 col-sm-12 col-sx-12">
					<div class="posts_load">
						<?php if (count($wo['movies']) > 26): ?>
						<div class="load-more">
							<button class="btn btn-default text-center wo_load_more load-more-movies" data-movies-type="all">
								<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z"></path></svg></span> <?php echo $wo['lang']['load_more'] ?>
							</button>
						</div>
						<?php endif ?>
					</div>
				</div>
			</div>
		</div>
	</div>
	<?php echo Wo_LoadPage("movies/includes/footer"); ?>
</div>