<div class="wo_settings_page profile-lists sun_sett_page">
	<h3><?php echo $wo['lang']['members'];?></h3>
   <div class="setting-well">
      <?php
         $requests = Wo_GetGroupSettingMembers($wo['setting']['id']);
         if (count($requests) > 0) {
            foreach ($requests as $wo['member']) {
                echo Wo_LoadPage('group-setting/members-list');
            }
         } else {
            echo '<h5 class="search-filter-center-text empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg> ' . $wo['lang']['no_members_found'] . '</h5>';
         }
         ?>
      <div class="clear"></div>
   </div>
</div>