<div class="page-margin list-group"> 
	<div class="center-container" style="text-align: center;">
		<h1>
			<span class="zmdi-hc-stack zmdi-hc-lg bouncemation" style="-webkit-filter: drop-shadow(0px 9px 7px #fb8c0082);filter: drop-shadow(0px 9px 7px #fb8c0082);">
				<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #FB8C00;"></i>
				<i class="zmdi zmdi-money-off zmdi-hc-stack-1x zmdi-hc-inverse"></i>
			</span>
		</h1>
        <h3><?php echo $wo['lang']['oops_something_went_wrong'];?></h3>
        <a href="<?php echo Wo_SeoLink('index.php?link1=go-pro');?>" data-ajax="?link1=go-pro" class="mdbtn wabe btn btn-lg btn-main">
			<i class="zmdi zmdi-replay zmdi-hc-fw"></i><?php echo $wo['lang']['try_again'];?>
		</a>
      </div>
</div>
<style>
body {padding-left: 0px;}
.navbar-default {padding-right: 0px;}
@media (min-width: 1200px){
body {padding-left: 0px;padding-right: 200px;}
.navbar-default {padding-right: 0px;}
}
@media (min-width: 1500px){
body {padding-left: 0px;padding-right: 260px;}
}
@media (max-width: 990px) {
body {padding-left: 0px;overflow-x: auto;}
}
</style>