<?php
if ($wo['page_data']['page_type'] == 0) {
?>
<div class="page-margin">
    <?php echo htmlspecialchars_decode($wo['page_data']['page_content']);?>
</div>
<?php
} else {
?>
<div class="page-margin">
   <div class="list-group wo_terms_page red-list">
      <h3><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg> <?php echo $wo['page_data']['page_title']?></h3>
      <div class="setting-well">
        <?php echo htmlspecialchars_decode($wo['page_data']['page_content']);?>
      </div>
   </div>
</div>
<?php } ?>