<div class="col-xs-6 col-sm-4" data-page-id="<?php echo $wo['PageList']['page_id']?>">
	<div class="search-user-profile" style="background: #fff;">
		<a id="user-full-name" href="<?php echo $wo['PageList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['PageList']['username']?>">
			<div class="avatar">
				<img id="updateImage-<?php echo $wo['PageList']['page_id']?>" alt="<?php echo $wo['PageList']['name']?> Profile Picture" src="<?php echo $wo['PageList']['avatar']?>">
			</div>
			<div class="info">
				<div class="title" style="top: -18px;margin-left: 7px;">
					<span class="user-popover" data-id="<?php echo $wo['PageList']['id'];?>" data-type="<?php echo $wo['PageList']['type'];?>">
						<?php echo $wo['PageList']['user_name'];?>
						<!--<?php if ($wo['PageList']['verified'] == 1) { ?> <i class="fa fa-check-circle verified-color" data-toggle="tooltip" title="<?php echo $wo['lang']['verified_user'];?>"></i> <?php } ?>-->
					</span>
				</div>
			</div>
		</a>
    </div>
</div>