<tr class="setting-event" id="EventID_<?php echo $wo['event']['id']?>" >
   <td><?php echo $wo['event']['id']?></td>
   <td>
      <a href="<?php echo $wo['event']['url']; ?>">LINK</a>
   </td>
   <td>
      <a href="<?php echo $wo['event']['user_data']['url']; ?>">
        <img src="<?php echo $wo['event']['user_data']['avatar']; ?>" class="setting-avatar" >
         <?php echo $wo['event']['user_data']['name']; ?>
         <?php echo $wo['event']['poster_id']; ?>
      </a>
   </td>
   <td>
     <div class="ajax-time">
         <?php echo ($wo['event']['start_date']);?>
     </div>
   </td>
   <td>
      <button type="button" class="delete-event btn btn-danger waves-effect waves-light" id="<?php echo $wo['event']['id']?>">DELETE</button>
   </td>
</tr>