<style>
@font-face {
    font-family: OpenSansLight;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/OpenSansLight/OpenSansLight.woff") format("woff");
    font-weight: normal;
}
@font-face {
    font-family: OpenSansRegular;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/OpenSansRegular/OpenSansRegular.woff") format("woff");
    font-weight: normal;
}
@font-face {
    font-family: OpenSansSemiBold;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/OpenSansSemiBold/OpenSansSemiBold.woff") format("woff");
    font-weight: normal;
}
@font-face {
    font-family: OpenSansBold;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/OpenSansBold/OpenSansBold.woff") format("woff");
    font-weight: normal;
}
.navbar-default {
    background: #4d91ea; border: none;
    height:45px;box-shadow: 0 1px 4px rgba(0, 0, 0, 0.2);
}
.navbar-nav.left_part_header .search-container {
	background: #4d91ea;
}
.round-check input[type="checkbox"]:checked + label:before {
    background: #4d91ea !important;
}
.group-messages-wrapper a{
    color: #4d91ea !important;
}
ul.profile-completion-bar li.completion-bar div.completion-bar-status {
    background: #4d91ea !important;
}
.featured-users{
    background: #fff !important;
}
.result-bar {
    background: #4d91ea !important;
}
.avtive {
    border-color: #4d91ea !important;
}
.left-sidebar ul li a i {
    color: #4d91ea !important;
}
.cs-loader-inner, .main  {
    color: #4d91ea;
}
.login input:focus, ul.profile-completion-bar li.completion-bar div.completion-bar-wrapper {
    border-color: #4d91ea !important;
}
.login:not(.loading) button:hover {
    background: #2e7be5 !important;
    color: #ffffff;
}

#search-nearby-users .nearby-users-relationship-collapse li.active .friends_toggle{
    border-color: #4d91ea;
}
#search-nearby-users .nearby-users-relationship-collapse li.active .friends_toggle:after{
    background: #4d91ea;
}
.login button, .wo_search_page .nav-tabs li.active a {
    background: #4d91ea !important;
    color: #ffffff !important;
}

.mejs-controls .mejs-time-rail .mejs-time-current, .mejs-controls .mejs-horizontal-volume-slider .mejs-horizontal-volume-current, .mejs-controls .mejs-volume-button .mejs-volume-slider .mejs-volume-current {
    background-color: #4d91ea !important;
    background: #4d91ea !important;
    background-image: #4d91ea !important;
}
.navbar-default .navbar-nav>.open>a, .navbar-default .navbar-nav>.open>a:focus, .navbar-default .navbar-nav>.open>a:hover {
    color: <?php echo $wo['config']['header_color'];?> !important;
    background-color: #2e7be5 !important;
}
.navbar-default .navbar-nav>.active>a, .navbar-default .navbar-nav>.active>a:focus, .navbar-default .navbar-nav>.active>a:hover, .nav-names li:hover {
    color: <?php echo $wo['config']['header_color'];?> !important;
    background-color: <?php echo $wo['config']['header_hover_border'];?> !important;
}
body {
    background-color: <?php echo $wo['config']['body_background'];?>;
}
.navbar-default .navbar-nav>li>a {
    color: <?php echo $wo['config']['header_color'];?>;
    font-size: 13px;
}
a.unread-update, .head_clos_srch {
    color: <?php echo $wo['config']['header_color'];?> !important;
}
.btn-main {
    color: #ffffff;
    background-color: #4d91ea;
    border-color: #4d91ea;
}
.btn-main:hover {
    color: <?php echo $wo['config']['btn_hover_color'];?>;
    background-color: #2e7be5;
    border-color: #2e7be5;
}
.active-wonder {
    color: #4d91ea;
}
.admin-panel .col-md-9 .list-group-item:first-child, .setting-panel .col-md-8 .list-group-item:first-child, .profile-lists .list-group-item:first-child, .col-md-8 .list-group-item:first-child, .col-md-3.custom .list-group-item:first-child, .col-sm-4 .list-group-item:first-child, .col-md-7 .list-group-item:first-child, .col-md-9 .list-group-item:first-child, .red-list .list-group-item:first-child, .active.list-group-item:first-child {
     color: #444;
     background-color: #fcfcfc;
     border-bottom: 1px solid #f1f1f1;
     padding: 18px;
}
.admin-panel .col-md-9 .list-group-item:first-child a, .setting-panel .col-md-8 .list-group-item:first-child a, .profile-lists .list-group-item:first-child a, .col-md-8 .list-group-item:first-child a, .col-md-7 .list-group-item:first-child a, .active.list-group-item:first-child a {
    color: #444 !important;
}
.list-group-item.black-list.active-list, .red-list.active-list {
    color: #ffffff;
    background-color: #4d91ea;
}
.list-group-item.black-list {
    background: #4d91ea;
}
.profile-top-line {
    background-color: #4d91ea;
}
#bar {
    background-color: #4d91ea;
}
.list-group-item.black-list a{
    color: #ffffff;
}
.list-group-item.black-list.active-list a{
    color: #4d91ea;
}
.main-color, .small-text a {
    color: #4d91ea !important;
}
.nav-tabs>li.active>a, .nav-tabs>li.active>a:focus, .nav-tabs>li.active>a:hover {
    color: #ffffff;
    cursor: default;
    color: #4d91ea;
    border-bottom: 1px solid #4d91ea;
    background-color: transparent
}
.btn-active {
    color: #ffffff;
    background: #4d91ea;
    outline: none;
    border: 1px solid #4d91ea
}
.btn-active:hover, .btn-active:focus {
    border: 1px solid #2e7be5;
    color: <?php echo $wo['config']['btn_hover_color'];?>;
    background: #2e7be5;
}
.btn-active-color:hover {
    background: #2e7be5;
}
.chat-tab .online-toggle {
    background: #4d91ea;
}
.profile-style .user-follow-button button.btn-active, .btn-login, .btn-register {
    background: #4d91ea;
    color: #ffffff;
}
.profile-style .user-follow-button button.btn-active:hover, .btn-login:hover, .btn-login:focus, .btn-register:hover, .btn-register:focus {
    color: <?php echo $wo['config']['btn_hover_color'];?>;
    background: #2e7be5;
}
.panel-login>.panel-heading a.active {
    color: #4d91ea;
    font-size: 18px;
}
.hash {
    color: #4d91ea;
}
.message-text .hash {
    color: #fff !important;
}
.search-container .search-input {
    color: #fff!important;
    background: #0147a9 !important;
}
.chat-messages-wrapper .outgoing {
    background: #4d91ea;
}
.message p {
    color: #fff;
}
.text-sender-container .outgoing .message-model .message {
    background: #4d91ea;
}
 
.incoming .message. p {
    color: #555;
}
.incoming.message p {
    color: #555;
}
.incoming .message p {
    color: #555;
}
.normal-container {
    width: 100%;
    height: 100%;
    margin-top: 15px;
}
.active.fa-thumbs-up {
    color: #4d91ea;
}
.api-ex-urls {
    background-color: #4d91ea; color: #ffffff;
}
.user-username {
    color: #4d91ea;
}
.upload-image {
    border: 3px dashed #4d91ea;
}
.events-tab-list li { background-color: #4d91ea; }
.events-tab-list li:hover { background-color: #4d91ea; }
.active-e-tab { background-color: #4d91ea !important; }
.main { color: #4d91ea !important; }
.events-list-dropup-menu ul li a:hover { background: #4d91ea; }
.usr-offline { color: #4d91ea; }
.blog-dd-ul li span:hover, .blog-dd-ul li a:hover { background: #4d91ea !important; }
.blog_publ {background: #4d91ea ; border: 1px solid #4d91ea ; }

.slide-film-desc:hover, .movies-top-breadcrumb li:hover, .movies-top-breadcrumb li a:hover{
    color: #4d91ea !important;
}
.movies h3.latest-movies, h3.recommended-movies {
    border-left: 3px solid  #4d91ea;
}

.wo_user_profile .user-bottom-nav li .menuactive {
    border-bottom: 2px solid #4d91ea;
    color:#4d91ea;
}


<?php 
if ($wo['config']['chatSystem'] == 1 && $wo['page'] != 'get_news_feed' && $wo['page'] != 'welcome' && $wo['page'] != '404' && $wo['page'] != 'movies' && $wo['loggedin'] == true && $wo['page'] != 'messages' && $wo['page'] != 'start_up') { ?>
body, .navbar-default, .wo_about_wrapper_parent{padding-right: 205px;}
@media (min-width: 1420px) {
body, .navbar-default, .wo_about_wrapper_parent{padding-right: 240px;}.sun_blog_head {right: 240px;}
}
@media (max-width:1140px){.wo_about_wrapper_parent{padding-right: 0px;}}
.sun_blog_head {right: 205px;}
<?php } ?>

<?php if($wo['language_type'] == 'rtl' && $wo['config']['chatSystem'] == 1 && $wo['page'] != 'get_news_feed' && $wo['page'] != 'welcome' && $wo['page'] != '404' && $wo['page'] != 'movies' && $wo['page'] != 'messages' && $wo['page'] != 'start_up' && $wo['loggedin'] == true) { ?>
body, .navbar-default, .wo_about_wrapper_parent{padding-left: 205px;padding-right: 0px;}
@media (max-width:1140px){.wo_about_wrapper_parent{padding-left: 0px;}}
<?php } ?>

.post .panel.active_shadow {
    box-shadow: 0 0 0 1.5px #4d91ea !important;
}

.ui-widget-header .ui-state-default {
    background-color: #4d91ea;
}

.reaction-like::before {
    content: "<?php echo $wo['lang']['like'];?>";
}
.reaction-love::before {
    content: "<?php echo $wo['lang']['love'];?>";
}
.reaction-haha::before {
    content: "<?php echo $wo['lang']['haha'];?>";
}
.reaction-wow::before {
    content: "<?php echo $wo['lang']['wow'];?>";
}
.reaction-sad::before {
    content: "<?php echo $wo['lang']['sad'];?>";
}
.reaction-angry::before {
    content: "<?php echo $wo['lang']['angry'];?>";
}

.navbar-default .dropdown-menu.ani-acc-menu >li>a:hover {
    color: #ffffff;background-color: #4d91ea;
}

@media (min-width: 992px){
#wo_msg_right_prt .text-sender-container .outgoing .message-model .message p {
    color: #ffffff;background-color: #4d91ea;
}

#wo_nw_msg_page .messages-recipients-list .msg_ava_name {
    color: <?php echo $wo['config']['header_color'];?> !important;
}
#wo_nw_msg_page .messages-recipients-list.active .msg_ava_name {
    color: #333 !important;
}
}
<?php if ($wo['config']['google_map'] == 0) { ?>
#filterby-post li {
    width: 16.5%;
}
<?php }?>


.sun_input input:focus, .sun_input textarea:focus, .sun_input select:focus{border-color:#4d91ea}
.loading::before {background-color: #4d91ea;}

<?php if($wo['page'] == 'home') { ?>
#wo_post_stat_button > .stat-item:nth-child(2) svg {
	margin-right: 3px;
}
<?php } ?>
</style>