<style>
	
	.ads-navbar-wrapper{
		width: 100%;
		overflow: hidden;
		margin-top: 20px;
		background-color: #a84849;
	}

	.ads-cont-wrapper{
		width: 100%;
		overflow: hidden;
		margin-top: 30px;
	}
	.ads-cont-wrapper a{
		text-decoration: none;
	}

	.ads-cont-wrapper .table th{
		font-family: 'Hind', sans-serif;
		font-weight: normal;
	}


	.ads-cont-wrapper .table td{
		vertical-align: middle;
		padding: 20px 10px !important;
	    background-color: #fff;
	    box-shadow: 0 1px 0 0 #e3e4e8, 0 0 0 1px #f1f1f1;
	    font-size: 13px;
	    font-family: 'Hind', sans-serif;

	}
	.create-ads-cont{
		background-color: #fff;
		margin-top: 30px;
		box-shadow: 0 1px 0 0 #e3e4e8, 0 0 0 1px #f1f1f1;
		padding-top: 30px;
		padding-bottom: 30px;
		font-family: 'Hind', sans-serif;
	}
	.create-ads-cont .create-ads-inner-left{
		border-right: 1px  solid #f1f1f1;
	}

	.create-ads-cont small{
		font-size: 12px;
	}
	.create-ads-cont input,textarea{
		font-size: 12px;
	}

	.create-ads-cont #select-ads-img{
		width: 100%;
		max-height: 230px;
		overflow: hidden;
		cursor: pointer;
	}

	.create-ads-cont #select-ads-img img{
		width: 100% !important;
		height: 100% !important;
	}

	.create-ads-cont #select-ads-img .img{
		width: 100%;
		height: 150px;
		background-color: #f9f9f9;
		color: #999;
		text-align: center;
		font-size: 19px;
		cursor: pointer;
		box-shadow: 0 1px 0 0 #e3e4e8, 0 0 0 1px #f1f1f1;
		padding-top: 55px;
		border-radius: 3px;
		margin: 1px;

	}

	.create-ads-cont .ads-audience{
		width: 100%;
		height: 190px;
		overflow-x: scroll;
	}

	.create-ads-cont button.cancel{
		margin-right: 20px;
		background: rgb(246, 247, 249);
	}

	.create-ads-cont .ads-audience p{
		padding: 0 5px;
		margin: 0 5px;
		line-height: 15px;
	}
	#replenish-user-account small{
		margin-bottom: 5px;
		display: inline-block;
	}
	    
</style>