<div class="page-margin">
	<div class="row">
<div class="col-md-2 leftcol"><?php echo Wo_LoadPage("movies/includes/header"); ?></div>
		<div class="col-md-10 singlecol">
		<div>
			<ul class="breadcrumb movies-top-breadcrumb hidden-xs">
			    <li><i class="fa fa-home"></i> <a href="<?php echo $wo['site_url']; ?>"><?php echo $wo['config']['siteName'] ?></a></li>
			    <li>
				    <a href="<?php echo Wo_SeoLink('index.php?link1=movies') ?>">
				    <?php echo $wo['lang']['movies']; ?>
				    </a>
			    </li>
			    <li><?php echo $wo['lang']['country']; ?></li>
			    <li class="main"><?php echo $wo['country']; ?></li>
			</ul>
			<div class="clear"></div>
		</div>
			
		<div class="movies">

			
			<div class="w100 movies-inner">
				<?php if (count($wo['movies']) > 0): ?>
					<?php foreach ($wo['movies'] as $wo['film']): ?>
						<?php echo Wo_LoadPage("movies/includes/films-list"); ?>
					<?php endforeach ?>
				<?php else: ?>
					<?php echo '<h5 class="search-filter-center-text empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-film"><rect x="2" y="2" width="20" height="20" rx="2.18" ry="2.18"></rect><line x1="7" y1="2" x2="7" y2="22"></line><line x1="17" y1="2" x2="17" y2="22"></line><line x1="2" y1="12" x2="22" y2="12"></line><line x1="2" y1="7" x2="7" y2="7"></line><line x1="2" y1="17" x2="7" y2="17"></line><line x1="17" y1="17" x2="22" y2="17"></line><line x1="17" y1="7" x2="22" y2="7"></line></svg> '. $wo['lang']['no_movies_found'] .' </h5>';?>
				<?php endif; ?>

			</div>

		

			<div class="col-md-12 col-lg-12 col-sm-12 col-sx-12">
			 	<div class="posts_load">
				    <?php if (count($wo['movies']) > 26): ?>
					<div class="load-more">
	                    <button class="btn btn-default text-center pointer load-more-movies" data-movies-type="country" data-country="<?php echo strtolower($wo['country']); ?>">
	                    <i class="fa fa-arrow-down progress-icon" data-icon="arrow-down"></i> <?php echo $wo['lang']['load_more'] ?></button>
	                </div>
	                <?php endif ?>
				</div>
			</div>
		
		</div>
	</div>
	
</div>
</div>

<?php echo Wo_LoadPage("movies/includes/footer"); ?>