<div class="user-data" id="hdrmmbrlst" data-user-id="<?php echo $wo['UsersList']['user_id'];?>" style="width: inherit;margin-right: 0px;margin-bottom: 0px;display:none">
	<a href="<?php echo $wo['UsersList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['UsersList']['username'];?>">
		<div class="avatar">
			<img src="<?php echo $wo['UsersList']['avatar'];?>" alt="<?php echo $wo['UsersList']['name']; ?> Profile Picture" style="margin-right: 0;width: 30px;height: 30px;border-radius:50%"/>
		</div>
	</a>
</div>
