<li>
	<a href="javascript:void(0);" class="see_all_stories" data_story_user_id="<?php echo $wo['user_status']['user_data']['user_id']?>" data_story_type="friends">
		<div class="story_loder"><svg width="38" height="38" viewBox="0 0 38 38" xmlns="http://www.w3.org/2000/svg" stroke="#fff"> <g fill="none" fill-rule="evenodd"> <g transform="translate(1 1)" stroke-width="2"> <circle stroke-opacity=".5" cx="18" cy="18" r="18"/> <path d="M36 18c0-9.94-8.06-18-18-18"> <animateTransform attributeName="transform" type="rotate" from="0 18 18" to="360 18 18" dur="1s" repeatCount="indefinite"/> </path> </g> </g> </svg></div>
		<img src="<?php echo $wo['user_status']['thumb']['filename'];?>" alt="<?php echo $wo['user_status']['user_data']['user_id']?>">
		<span>
			<img src="<?php echo $wo['user_status']['user_data']['avatar']?>" alt="<?php echo $wo['user_status']['user_data']['user_id']?>" >
			<p><?php if($wo['user_status']['user_data']['first_name']) { ?>
				<?php echo $wo['user_status']['user_data']['first_name']; ?>
			<?php } else { ?>
			<?php if($wo['user_status']['user_data']['username']) { ?>
				<?php echo $wo['user_status']['user_data']['username']; ?>
			<?php } ?>
			<?php } ?></p>
		</span>
	</a> 
</li>