<div class="col-sm-6 events-list-wrapper" data-event="<?php echo($wo['event']['id']);?>">
	<div class="events-list-cover">
		<div class="event_cover">
			<div class="intrst_btn"><?php echo Wo_GetInterestedButton($wo['event']['id']);?></div>
			<a href="<?php echo $wo['event']['url']; ?>" data-ajax="?link1=show-event&eid=<?php echo($wo['event']['id']);?>"><img src="<?php echo $wo['event']['cover']; ?>" class="events-list-cover-img"></a>
			<div class="event-l-info">
				<div class="info_prt">
					<h3 class="events-list-name"><a href="<?php echo $wo['event']['url']; ?>" data-ajax="?link1=show-event&eid=<?php echo($wo['event']['id']);?>"><?php echo $wo['event']['name']; ?></a></h3>
					<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M12,11.5A2.5,2.5 0 0,1 9.5,9A2.5,2.5 0 0,1 12,6.5A2.5,2.5 0 0,1 14.5,9A2.5,2.5 0 0,1 12,11.5M12,2A7,7 0 0,0 5,9C5,14.25 12,22 12,22C12,22 19,14.25 19,9A7,7 0 0,0 12,2Z" /></svg> <?php echo $wo['event']['location'];?></span>
					<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M19,19H5V8H19M16,1V3H8V1H6V3H5C3.89,3 3,3.89 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V5C21,3.89 20.1,3 19,3H18V1M17,12H12V17H17V12Z" /></svg> <?php echo $wo['event']['start_date'];?></span>
				</div>
				<div class="user-follow-button">
					<?php echo Wo_GetGoingButton($wo['event']['id']);?>
				</div>
			</div>
		</div>
	</div>
	<div class="clear"></div>
</div>