<div class="user-fetch sun_popover">
	<div class="hover_offset">
		<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="300" height="100" viewBox="0 0 600 200">
			<defs><clipPath id="clipping"><polygon points="50,10 60,0 70,10 50,10"></polygon></clipPath></defs>
			<image xlink:href="<?php echo $wo['popover']['cover']?>" width="600" height="200" clip-path="url(#clipping)"></image>
		</svg>
	</div>
	<div class="user-cover" style="background-image: url(<?php echo $wo['popover']['cover']?>);"></div>
	<div class="upop_mid">
		<div class="user-avatar">
			<img src="<?php echo $wo['popover']['avatar']; ?>" alt="">
		</div>
		<div class="upop_mid_innr">
			<div class="user-name">
				<a href="<?php echo $wo['popover']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['popover']['group_name']?>"><?php echo $wo['popover']['name']; ?></a>
			</div>
			<ul class="user-information">
				<li>
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M5.5,7A1.5,1.5 0 0,1 4,5.5A1.5,1.5 0 0,1 5.5,4A1.5,1.5 0 0,1 7,5.5A1.5,1.5 0 0,1 5.5,7M21.41,11.58L12.41,2.58C12.05,2.22 11.55,2 11,2H4C2.89,2 2,2.89 2,4V11C2,11.55 2.22,12.05 2.59,12.41L11.58,21.41C11.95,21.77 12.45,22 13,22C13.55,22 14.05,21.77 14.41,21.41L21.41,14.41C21.78,14.05 22,13.55 22,13C22,12.44 21.77,11.94 21.41,11.58Z" /></svg> <?php echo $wo['popover']['category'];?>
				</li>
				<li>
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M16,13C15.71,13 15.38,13 15.03,13.05C16.19,13.89 17,15 17,16.5V19H23V16.5C23,14.17 18.33,13 16,13M8,13C5.67,13 1,14.17 1,16.5V19H15V16.5C15,14.17 10.33,13 8,13M8,11A3,3 0 0,0 11,8A3,3 0 0,0 8,5A3,3 0 0,0 5,8A3,3 0 0,0 8,11M16,11A3,3 0 0,0 19,8A3,3 0 0,0 16,5A3,3 0 0,0 13,8A3,3 0 0,0 16,11Z" /></svg> <?php echo Wo_CountGroupMembers($wo['popover']['id']);?>
				</li>
			</ul>
		</div>
	</div>
	<div class="clear"></div>
	<div class="user-footer">
		<div class="user-buttons text-center">
			<div class="user-button user-follow-button"><?php echo Wo_GetJoinButton($wo['popover']['id']); ?></div>
		</div>
	</div>
	<div class="clear"></div>
</div>