<div class="profile-style user-data" data-page-id="<?php echo $wo['GroupList']['id'];?>">
  <a href="<?php echo $wo['GroupList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['GroupList']['username']?>">
    <div class="avatar <?php echo Wo_RightToLeft('pull-left');?>">
      <img src="<?php echo $wo['GroupList']['avatar'];?>" alt="<?php echo $wo['GroupList']['name']; ?> Profile Picture" />
    </div>
    <?php echo $wo['GroupList']['name']; ?>
  </a>
  <div class="user-lastseen">
    <?php echo $wo['lang']['members'];?>: <?php echo Wo_CountGroupMembers($wo['GroupList']['id']); ?>
  </div>
  <div class="user-follow-button">
    <?php echo Wo_GetJoinButton($wo['GroupList']['id']);?>
  </div>
</div>