<div class="thread-replies" data-thread-reply="<?php echo $wo['threadreply']['id']; ?>" id="reply-<?php echo $wo['threadreply']['id']; ?>">
	<div class="col-md-2">
		<a href="<?php echo ($wo['threadreply']['user_data']['url']); ?>"><h4 class="text-center user-title-thread main">
			<?php echo ($wo['threadreply']['user_data']['username']); ?>
		</h4>
		</a>
		<div class="text-center">
		<a href="<?php echo ($wo['threadreply']['user_data']['url']); ?>"><img src="<?php echo $wo['threadreply']['user_data']['avatar']; ?>" alt="Avatar" class="avatar" width="90"></a>
		</div>
		<hr>
		<p class="small text-center">
			<?php echo $wo['lang']['joined']; ?>: 
			<?php echo Wo_Time_Elapsed_String($wo['threadreply']['user_data']['joined']); ?>	
		</p>
		<p class="small text-center">
			<?php if ($wo['threadreply']['user_data']['admin'] == 1): ?>
			<?php echo $wo['lang']['site_admin']; ?>
			<?php else: ?>
				<?php echo $wo['lang']['registered']; ?>
			<?php endif; ?>
		</p>
	</div>
	<div class="col-md-10">
		<h4 class="time <?php echo Wo_RightToLeft('pull-left');?> ">
			<?php if ($wo['threadreply']['post_quoted'] == 1): ?>
				<i class="fa fa-reply" aria-hidden="true"></i> 
			<?php else: ?>
				<i class="fa fa-reply-all" aria-hidden="true"></i> 
			<?php endif; ?>
			<span> <?php echo Wo_Time_Elapsed_String($wo['threadreply']['posted_time']); ?></span>
		</h4>
		<div class="<?php echo Wo_RightToLeft('pull-right');?> ">
			<a class="btn btn-default btn-sm" href="<?php echo $wo['threadreply']['reply-url']; ?>">
		   		<i class="fa fa-reply" aria-hidden="true"></i> 
		    </a>
		    <?php if ($wo['threadreply']['is_owner'] || $wo['threadreply']['is_admin']): ?>
			    <a class="btn btn-default btn-sm" href="<?php echo $wo['threadreply']['edit-url']; ?>">
			        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>        
		        </a>
				<a class="btn btn-default delete-reply btn-sm" id="<?php echo $wo['threadreply']['id']; ?>">
					<i class="fa fa-trash" aria-hidden="true"></i>
				</a>
		    <?php endif; ?>
	       <a href="#reply-<?php echo $wo['threadreply']['id']; ?>" class="btn btn-default btn-sm">
	       		<i class="fa fa-link" aria-hidden="true"></i>
	       </a>
		</div>

		<div class="clear"></div>

		<hr>
		<div class="small">
			<?php echo Wo_BbcodeToHtml($wo['threadreply']['post_text']); ?>
		</div>

	</div>

	<div class="clear"></div>
</div>
