<ul class="list-group sun_side_widget" id="sidebar-pages-list-container">
	<li class="list-group-item text-muted hidden" contenteditable="false"><?php echo $wo['lang']['more_info']; ?></li>
	<h3 class="sun_side_widget_title">
		<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#03A9F4" d="M12,6A3,3 0 0,0 9,9A3,3 0 0,0 12,12A3,3 0 0,0 15,9A3,3 0 0,0 12,6M6,8.17A2.5,2.5 0 0,0 3.5,10.67A2.5,2.5 0 0,0 6,13.17C6.88,13.17 7.65,12.71 8.09,12.03C7.42,11.18 7,10.15 7,9C7,8.8 7,8.6 7.04,8.4C6.72,8.25 6.37,8.17 6,8.17M18,8.17C17.63,8.17 17.28,8.25 16.96,8.4C17,8.6 17,8.8 17,9C17,10.15 16.58,11.18 15.91,12.03C16.35,12.71 17.12,13.17 18,13.17A2.5,2.5 0 0,0 20.5,10.67A2.5,2.5 0 0,0 18,8.17M12,14C10,14 6,15 6,17V19H18V17C18,15 14,14 12,14M4.67,14.97C3,15.26 1,16.04 1,17.33V19H4V17C4,16.22 4.29,15.53 4.67,14.97M19.33,14.97C19.71,15.53 20,16.22 20,17V19H23V17.33C23,16.04 21,15.26 19.33,14.97Z"></path></svg> 
		<a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=groups');?>" data-ajax="?link1=timeline&u=<?php echo $wo['user_profile']['username']?>&type=groups"><?php echo $wo['lang']['groups'];?></a>
		<span><?php echo $wo['user_profile']['details']['groups_count'];?></span>
	</h3>
	<li>
		<div class="sidebar-groups-container sun_prof_foll_ing">
			<?php 
			foreach (Wo_GetUsersGroups($wo['user_profile']['user_id'], 9, array('in' => 'profile_sidebar', 'groups_data' => $wo['user_profile']['groups_data'])) as $wo['GroupList']) {
				$wo['GroupList']['name'] = mb_substr($wo['GroupList']['name'], 0, 10, "utf-8");
				echo Wo_LoadPage('sidebar/sidebar-groups-list');
			}
			?>
		</div>
	</li>
	<li><div class="clear"></div></li>
</ul>