<ul class="profile-completion-bar sun_side_widget" data-profile-completion="<?php echo array_sum($wo['pr_complition']); ?>">
	<li class="completion-bar">
        <div class="completion-bar-wrapper">
            <div class="completion-bar-status" style="width: <?php echo array_sum($wo['pr_complition']); ?>%;">
            </div>
        </div>
    </li>
	<h3 class="sun_side_widget_title">
		<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#9c27b0" d="M3,5H9V11H3V5M5,7V9H7V7H5M11,7H21V9H11V7M11,15H21V17H11V15M5,20L1.5,16.5L2.91,15.09L5,17.17L9.59,12.59L11,14L5,20Z"></path></svg> <?php echo $wo['lang']['pr_completion']; ?>
		<span class="completion-bar-percentage"><?php echo array_sum($wo['pr_complition']); ?>%</span>
	</h3>
    <hr>
    <?php if (empty($wo['pr_complition'][1])): ?>
        <li class="completion-step" id="add-profile-avatar">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M19,13H13V19H11V13H5V11H11V5H13V11H19V13Z" /></svg>
			<?php echo $wo['lang']['ad_pr_picture']; ?>   
        </li>
    <?php else: ?>
        <li class="completion-step">
           <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="green" d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z" /></svg>
           <span class="completed"> <?php echo $wo['lang']['ad_pr_picture']; ?></span>  
        </li>
    <?php endif; ?>
    <li class="completion-step">
        <?php if (!empty($wo['pr_complition'][2])): ?>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="green" d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z" /></svg>
            <span class="completed"> <?php echo $wo['lang']['add_ur_name']; ?> </span>
        <?php else: ?>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M19,13H13V19H11V13H5V11H11V5H13V11H19V13Z" /></svg>
            <a href="<?php echo Wo_SeoLink('index.php?link1=setting&page=profile-setting');?>" data-ajax="?link1=setting&page=profile-setting"> <?php echo $wo['lang']['add_ur_name']; ?>  </a>
        <?php endif; ?>
    </li>
    <li class="completion-step">
        <?php if (!empty($wo['pr_complition'][3])): ?>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="green" d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z" /></svg>
            <span class="completed"> <?php echo $wo['lang']['ad_ur_workplace']; ?> </span>
        <?php else: ?>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M19,13H13V19H11V13H5V11H11V5H13V11H19V13Z" /></svg>
            <a href="<?php echo Wo_SeoLink('index.php?link1=setting&page=profile-setting');?>" data-ajax="?link1=setting&page=profile-setting"> <?php echo $wo['lang']['ad_ur_workplace']; ?> </a> 
        <?php endif; ?>
    </li>
    <li class="completion-step">
        <?php if (!empty($wo['pr_complition'][4])): ?>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="green" d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z" /></svg>
            <span class="completed"><?php echo $wo['lang']['ad_ur_country']; ?></span>
        <?php else: ?>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M19,13H13V19H11V13H5V11H11V5H13V11H19V13Z" /></svg>
            <a href="<?php echo Wo_SeoLink('index.php?link1=setting&page=general-setting');?>" data-ajax="?link1=setting&page=general-setting"><?php echo $wo['lang']['ad_ur_country']; ?></a>
        <?php endif; ?>
    </li>
    <li class="completion-step">
        <?php if (!empty($wo['pr_complition'][5])): ?>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="green" d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z" /></svg>
            <span class="completed"><?php echo $wo['lang']['ad_ur_address']; ?></span>
        <?php else: ?>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M19,13H13V19H11V13H5V11H11V5H13V11H19V13Z" /></svg>
            <a href="<?php echo Wo_SeoLink('index.php?link1=setting&page=profile-setting');?>" data-ajax="?link1=setting&page=profile-setting"><?php echo $wo['lang']['ad_ur_address']; ?></a>
        <?php endif; ?>
    </li>
</ul>

<script>
jQuery(document).ready(function($) {
	$("#add-profile-avatar").click(function(event) {
		$('.profile-avatar-changer').find('input').trigger('click');
	});
});
</script>