<div class="container-fluid">
    <div class="block-header">
        <h2>Manage Features > Articles (Blog)</h2>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h2>Manage Articles (Blog)</h2>
                </div>
                <div class="body">
                   <input type="hidden" id="hash_id" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                   <div class="clearfix"></div>
                   <div class="table-responsive1">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                                <tr>
                                      <th>ID</th>
					                  <th>Link</th>
					                  <th>Author</th>
					                  <th>Posted</th>
					                  <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                              <?php 
        				                foreach (Wo_GetBlogs(array('limit' => 900000)) as $wo['blog']) {
        				                  echo Wo_LoadAdminPage('manage-articles/list');
        				                }
				                          ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
<script>
$(function () {
	$('table').DataTable();
});

function Wo_DeleteBlog(id) {
  if (confirm("Are you sure you want to delete this blog?'") == false) {
    return false;
  }
  $('#BlogID_' + id).fadeOut(300, function() {
    $(this).remove();
  });
  $.get(Wo_Ajax_Requests_File(),{f:'delete-my-blog',id: id});
}
</script>